# Measures of Model Fit

When the model is identified, then $\Sigma_{sample}$ can be used to derive parameter estimates that yield a covariance matrix ($\widehat\Sigma_{model}$) that is as close as possible to the observed sample covariance matrix. In general, when the discrepancies between $\Sigma_{sample}$ and $\widehat\Sigma_{model}$ are large, this indicates that the specified model cannot give a good description of the data and therefore one might question whether the model is true in the population, i.e., whether the model is misspecified. For just-identified models, the model parameters can usually be estimated so that $\widehat\Sigma_{model}$ equals $\Sigma_{sample}$. Evaluation of model fit is therefore uninformative. The model that is specified might not necessarily be the ‘true’ model, but there is not enough information to evaluate possible misspecification of the model as a whole. For models that are over identified (i.e., that have positive degrees of freedom) the evaluation of model fit may be informative as it can give an indication as to what extent the discrepancies between $\Sigma_{sample}$ and $\widehat\Sigma_{model}$ can be attributed to misspecification of the model. Below we first discuss the $χ^2$ test of ‘exact fit’, then we explain the evaluation of ‘approximate fit’, and give a short overview of other descriptive measures of model fit. We also discuss the evaluation of differences in model fit, and finally show how to obtain all these measures of model fit in `lavaan`.

## The chi-squared test of exact fit
The $χ^2$ test of exact fit is the basic statistical evaluation of overall model fit for over-identified SEMs. It is used to evaluate the following hypothesis:

```{=tex}
\begin{equation}
\Sigma_{population} = \Sigma_{model},
(\#eq:11-01)
\end{equation}
```

where $\Sigma_{population}$ refers to the matrix of population variances and covariances of the observed variables, and $\Sigma_{model}$ refers to the population matrix of variances and covariances as implied by the path model. $\Sigma_{model}$ is a function of model parameters (following Equations 3.09 and 3.10). If the model gives a true description of reality then model is equal to the population variances and covariances population. However, these population matrices cannot be directly observed and therefore their values are unknown. Instead, the matrix of observed covariances sample is taken as an estimate of the population covariance matrix, and  ̂model is the covariance matrix as implied by model parameters derived from the sample estimates. Because the sample covariance matrix and estimated model-implied covariance matrix are only estimates of their corresponding population covariance matrices, it is possible that  ̂population ≠  ̂model, even if population = model. Figure 11.1 gives a graphical representation of the population covariance matrices (population and model) and the sample covariance matrices (sample and  ̂model), and the different types of discrepancies that play a role in model fit evaluation. The term ‘sample discrepancy’ refers to the observed differences between the sample covariance matrix and the model-implied covariance matrix as derived from model parameter estimates. The term ‘population discrepancy’ refers to the differences between the population covariance matrix and the population model-implied covariance matrix. 
