<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>13 Latent Growth Curve Models | Compendium Structural Equation Modeling in Educational Research</title>
  <meta name="description" content="13 Latent Growth Curve Models | Compendium Structural Equation Modeling in Educational Research" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="13 Latent Growth Curve Models | Compendium Structural Equation Modeling in Educational Research" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="LJGroot/SEM-Compendium" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="13 Latent Growth Curve Models | Compendium Structural Equation Modeling in Educational Research" />
  
  
  

<meta name="author" content="Suzanne Jak and Terrence D. Jorgensen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fitting-path-models-with-multilevel-data.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html"><i class="fa fa-check"></i><b>1</b> Regression as Mean- and Covariance-Structure Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#installing-lavaan"><i class="fa fa-check"></i><b>1.1</b> Installing <code>lavaan</code></a></li>
<li class="chapter" data-level="1.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#types-of-data-used-in-sem"><i class="fa fa-check"></i><b>1.2</b> Types of Data Used in SEM</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#raw-data"><i class="fa fa-check"></i><b>1.2.1</b> Raw Data</a></li>
<li class="chapter" data-level="1.2.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#summary-statistics-from-raw-data"><i class="fa fa-check"></i><b>1.2.2</b> Summary Statistics from Raw Data</a></li>
<li class="chapter" data-level="1.2.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#importing-summary-data"><i class="fa fa-check"></i><b>1.2.3</b> Importing Summary Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#regression-review"><i class="fa fa-check"></i><b>1.3</b> Regression Review</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#linear-regression-models"><i class="fa fa-check"></i><b>1.3.1</b> Linear Regression Models</a></li>
<li class="chapter" data-level="1.3.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#matrix-notation"><i class="fa fa-check"></i><b>1.3.2</b> Matrix Notation</a></li>
<li class="chapter" data-level="1.3.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#interpreting-and-estimating-coefficients"><i class="fa fa-check"></i><b>1.3.3</b> Interpreting and Estimating Coefficients</a></li>
<li class="chapter" data-level="1.3.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#syntax-examples-with-raw-data"><i class="fa fa-check"></i><b>1.3.4</b> Syntax Examples with Raw Data</a></li>
<li class="chapter" data-level="1.3.5" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#categorical-predictors"><i class="fa fa-check"></i><b>1.3.5</b> Categorical Predictors</a></li>
<li class="chapter" data-level="1.3.6" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#constant-vs.-varying-slopes"><i class="fa fa-check"></i><b>1.3.6</b> Constant vs. Varying Slopes</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#summary-statistics"><i class="fa fa-check"></i><b>1.4</b> Summary Statistics</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#reimport-data"><i class="fa fa-check"></i><b>1.4.1</b> Reimport Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#raw-data-vs.-summary-statistics"><i class="fa fa-check"></i><b>1.4.2</b> Raw Data vs. Summary Statistics</a></li>
<li class="chapter" data-level="1.4.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#what-is-covariance"><i class="fa fa-check"></i><b>1.4.3</b> What Is Covariance?</a></li>
<li class="chapter" data-level="1.4.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#interpreting-covariance"><i class="fa fa-check"></i><b>1.4.4</b> Interpreting Covariance</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#covariance-matrix"><i class="fa fa-check"></i><b>1.5</b> Covariance Matrix</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#ols-with-summary-statistics-beta-mathbfx-mathbfx-1-mathbfx-mathbfy"><i class="fa fa-check"></i><b>1.5.1</b> OLS with Summary Statistics: <span class="math inline">\(\beta = (\mathbf{X}^{&#39;} \mathbf{X})^{-1} \mathbf{X}^{&#39;} \mathbf{y}\)</span></a></li>
<li class="chapter" data-level="1.5.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#intercepts-and-means"><i class="fa fa-check"></i><b>1.5.2</b> Intercepts and Means</a></li>
<li class="chapter" data-level="1.5.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#intercepts-and-means-1"><i class="fa fa-check"></i><b>1.5.3</b> Intercepts and Means</a></li>
<li class="chapter" data-level="1.5.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#what-are-mean-and-covariance-structures"><i class="fa fa-check"></i><b>1.5.4</b> What Are Mean and Covariance <em>Structures</em>?</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#references"><i class="fa fa-check"></i><b>1.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><i class="fa fa-check"></i><b>2</b> Using <code>lavaan</code> to Run Regression and ANOVA as a SEM</a>
<ul>
<li class="chapter" data-level="2.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#prepare-data-and-workspace"><i class="fa fa-check"></i><b>2.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#import-example-data"><i class="fa fa-check"></i><b>2.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="2.1.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#load-lavaan-into-workspace"><i class="fa fa-check"></i><b>2.1.2</b> Load <code>lavaan</code> into Workspace</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multiple-regression-in-sem"><i class="fa fa-check"></i><b>2.2</b> Multiple Regression in SEM</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#lavaan-syntax"><i class="fa fa-check"></i><b>2.2.1</b> <code>lavaan</code> Syntax</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#caveats-with-sem"><i class="fa fa-check"></i><b>2.3</b> Caveats with SEM</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#model-comparison-with-ols"><i class="fa fa-check"></i><b>2.3.1</b> Model Comparison with OLS</a></li>
<li class="chapter" data-level="2.3.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#model-comparison-with-lavaan"><i class="fa fa-check"></i><b>2.3.2</b> Model Comparison with <code>lavaan</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#moderation-caveats"><i class="fa fa-check"></i><b>2.3.3</b> Moderation Caveats</a></li>
<li class="chapter" data-level="2.3.4" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#summary-of-caveats"><i class="fa fa-check"></i><b>2.3.4</b> Summary of Caveats</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multigroup-sem"><i class="fa fa-check"></i><b>2.4</b> Multigroup SEM</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#group-specific-intercepts-in-ols"><i class="fa fa-check"></i><b>2.4.1</b> Group-Specific Intercepts in OLS</a></li>
<li class="chapter" data-level="2.4.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#group-specific-intercepts-in-sem"><i class="fa fa-check"></i><b>2.4.2</b> Group-Specific Intercepts in SEM?</a></li>
<li class="chapter" data-level="2.4.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multiple-groups-in-sem"><i class="fa fa-check"></i><b>2.4.3</b> Multiple Groups in SEM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="path-models.html"><a href="path-models.html"><i class="fa fa-check"></i><b>3</b> Path Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="path-models.html"><a href="path-models.html#illustrative-example"><i class="fa fa-check"></i><b>3.1</b> Illustrative example</a></li>
<li class="chapter" data-level="3.2" data-path="path-models.html"><a href="path-models.html#conceptual-explanation"><i class="fa fa-check"></i><b>3.2</b> Conceptual explanation</a></li>
<li class="chapter" data-level="3.3" data-path="path-models.html"><a href="path-models.html#matrix-explanation"><i class="fa fa-check"></i><b>3.3</b> Matrix explanation</a></li>
<li class="chapter" data-level="3.4" data-path="path-models.html"><a href="path-models.html#path-analysis-using-lavaan"><i class="fa fa-check"></i><b>3.4</b> Path analysis using lavaan</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="path-models.html"><a href="path-models.html#installing-lavaan-1"><i class="fa fa-check"></i><b>3.4.1</b> Installing lavaan</a></li>
<li class="chapter" data-level="3.4.2" data-path="path-models.html"><a href="path-models.html#fitting-a-path-model"><i class="fa fa-check"></i><b>3.4.2</b> Fitting a path model</a></li>
<li class="chapter" data-level="3.4.3" data-path="path-models.html"><a href="path-models.html#syntax-shortcuts"><i class="fa fa-check"></i><b>3.4.3</b> Syntax shortcuts</a></li>
<li class="chapter" data-level="3.4.4" data-path="path-models.html"><a href="path-models.html#extracting-results-from-lavaan-output-in-matrix-form"><i class="fa fa-check"></i><b>3.4.4</b> Extracting results from lavaan output in matrix form</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="path-models.html"><a href="path-models.html#references-1"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
<li class="chapter" data-level="3.6" data-path="path-models.html"><a href="path-models.html#appendix-3"><i class="fa fa-check"></i><b>3.6</b> Appendix I. Derivations of equation 3.08 and 3.09</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html"><i class="fa fa-check"></i><b>4</b> Standard Errors and Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#standard-errors"><i class="fa fa-check"></i><b>4.1</b> Standard Errors</a></li>
<li class="chapter" data-level="4.2" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#likelihood-based-confidence-intervals"><i class="fa fa-check"></i><b>4.2.1</b> Likelihood-based confidence intervals</a></li>
<li class="chapter" data-level="4.2.2" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#bootstrapped-confidence-intervals"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrapped confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#obtaining-standard-errors-and-confidence-intervals-in-lavaan"><i class="fa fa-check"></i><b>4.3</b> Obtaining standard errors and confidence intervals in <code>lavaan</code></a></li>
<li class="chapter" data-level="4.4" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#references-2"><i class="fa fa-check"></i><b>4.4</b> <strong>References</strong></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html"><i class="fa fa-check"></i><b>5</b> Direct, Indirect, and Total Effects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#testing-significance-of-indirect-effects"><i class="fa fa-check"></i><b>5.1</b> Testing significance of indirect effects</a></li>
<li class="chapter" data-level="5.2" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#higher-order-indirect-effects"><i class="fa fa-check"></i><b>5.2</b> Higher order indirect effects</a></li>
<li class="chapter" data-level="5.3" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#using-matrix-algebra-to-calculate-total-total-indirect-and-specific-indirect-effects"><i class="fa fa-check"></i><b>5.3</b> Using matrix algebra to calculate total, total indirect and specific indirect effects</a></li>
<li class="chapter" data-level="5.4" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#calculating-total-total-indirect-and-specific-indirect-effects-using-lavaan-output"><i class="fa fa-check"></i><b>5.4</b> Calculating total, total indirect and specific indirect effects using lavaan output</a></li>
<li class="chapter" data-level="5.5" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#calculating-specific-indirect-effects-in-lavaan"><i class="fa fa-check"></i><b>5.5</b> Calculating specific indirect effects in lavaan</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html"><i class="fa fa-check"></i><b>6</b> Calculating Standardized Parameter Estimates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardized-regression-coefficients"><i class="fa fa-check"></i><b>6.1</b> Standardized regression coefficients</a></li>
<li class="chapter" data-level="6.2" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardized-residual-factor-variances-and-covariances"><i class="fa fa-check"></i><b>6.2</b> Standardized residual factor variances and covariances</a></li>
<li class="chapter" data-level="6.3" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#calculating-standardized-coefficients-in-r-using-lavaan-results"><i class="fa fa-check"></i><b>6.3</b> Calculating standardized coefficients in R using lavaan results</a></li>
<li class="chapter" data-level="6.4" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#request-standardized-output-with-lavaan"><i class="fa fa-check"></i><b>6.4</b> Request standardized output with lavaan</a></li>
<li class="chapter" data-level="6.5" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardizing-indirect-and-total-effects"><i class="fa fa-check"></i><b>6.5</b> Standardizing indirect and total effects</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="identification.html"><a href="identification.html"><i class="fa fa-check"></i><b>7</b> Identification</a>
<ul>
<li class="chapter" data-level="7.1" data-path="identification.html"><a href="identification.html#assessment-of-identification-using-the-elements-of-σ_population-and-sigma_model"><i class="fa fa-check"></i><b>7.1</b> Assessment of identification using the elements of <span class="math inline">\(Σ_{population}\)</span> and <span class="math inline">\(\Sigma_{model}\)</span></a></li>
<li class="chapter" data-level="7.2" data-path="identification.html"><a href="identification.html#assessing-identification-through-heuristics-rules-of-thumb"><i class="fa fa-check"></i><b>7.2</b> Assessing identification through heuristics (rules of thumb)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="identification.html"><a href="identification.html#the-recursive-rule"><i class="fa fa-check"></i><b>7.2.1</b> The recursive rule</a></li>
<li class="chapter" data-level="7.2.2" data-path="identification.html"><a href="identification.html#the-order-condition"><i class="fa fa-check"></i><b>7.2.2</b> The order condition</a></li>
<li class="chapter" data-level="7.2.3" data-path="identification.html"><a href="identification.html#the-rank-condition"><i class="fa fa-check"></i><b>7.2.3</b> The rank condition</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="identification.html"><a href="identification.html#assessment-of-empirical-model-identification-using-lavaan"><i class="fa fa-check"></i><b>7.3</b> Assessment of empirical model identification using <code>lavaan</code></a></li>
<li class="chapter" data-level="7.4" data-path="identification.html"><a href="identification.html#appendix-7"><i class="fa fa-check"></i><b>7.4</b> Appendix I</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="identification.html"><a href="identification.html#algebraic-assessment-of-identification-using-elements-of-sigma_population-and-sigma_model"><i class="fa fa-check"></i><b>7.4.1</b> Algebraic assessment of identification using elements of <span class="math inline">\(\Sigma_{population}\)</span> and <span class="math inline">\(\Sigma_{model}\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="autoregression.html"><a href="autoregression.html"><i class="fa fa-check"></i><b>8</b> Autoregression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="autoregression.html"><a href="autoregression.html#autoregression-models-with-predictors"><i class="fa fa-check"></i><b>8.1</b> Autoregression models with predictors</a></li>
<li class="chapter" data-level="8.2" data-path="autoregression.html"><a href="autoregression.html#cross-lagged-panel-models"><i class="fa fa-check"></i><b>8.2</b> Cross-lagged panel models</a></li>
<li class="chapter" data-level="8.3" data-path="autoregression.html"><a href="autoregression.html#references-3"><i class="fa fa-check"></i><b>8.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html"><i class="fa fa-check"></i><b>9</b> Model Specification and Model Identification</a>
<ul>
<li class="chapter" data-level="9.0.1" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#from-theory-to-model"><i class="fa fa-check"></i><b>9.0.1</b> From theory to model</a></li>
<li class="chapter" data-level="9.0.2" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#model-parsimony"><i class="fa fa-check"></i><b>9.0.2</b> Model parsimony</a></li>
<li class="chapter" data-level="9.0.3" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#a-priori-model-specification"><i class="fa fa-check"></i><b>9.0.3</b> A priori model specification</a></li>
<li class="chapter" data-level="9.0.4" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#post-hoc-model-modification"><i class="fa fa-check"></i><b>9.0.4</b> Post hoc model modification</a></li>
<li class="chapter" data-level="9.1" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#backward-and-forward-specification-searches"><i class="fa fa-check"></i><b>9.1</b> Backward and forward specification searches</a></li>
<li class="chapter" data-level="9.2" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#correlation-residuals"><i class="fa fa-check"></i><b>9.2</b> Correlation residuals</a></li>
<li class="chapter" data-level="9.3" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#modification-indices"><i class="fa fa-check"></i><b>9.3</b> Modification indices</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#cross-validation"><i class="fa fa-check"></i><b>9.3.1</b> Cross-validation</a></li>
<li class="chapter" data-level="9.3.2" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#calculating-correlation-residuals-in-lavaan"><i class="fa fa-check"></i><b>9.3.2</b> Calculating correlation residuals in lavaan</a></li>
<li class="chapter" data-level="9.3.3" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#requesting-mis-and-sepcs-in-lavaan"><i class="fa fa-check"></i><b>9.3.3</b> Requesting MIs and (S)EPCs in lavaan</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="model-specification-and-model-identification.html"><a href="model-specification-and-model-identification.html#references-4"><i class="fa fa-check"></i><b>9.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>10</b> Estimation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estimation.html"><a href="estimation.html#improper-solutions"><i class="fa fa-check"></i><b>10.1</b> Improper Solutions</a></li>
<li class="chapter" data-level="10.2" data-path="estimation.html"><a href="estimation.html#specifying-starting-values-in-lavaan"><i class="fa fa-check"></i><b>10.2</b> Specifying starting values in lavaan</a></li>
<li class="chapter" data-level="10.3" data-path="estimation.html"><a href="estimation.html#alternative-estimators"><i class="fa fa-check"></i><b>10.3</b> Alternative estimators</a></li>
<li class="chapter" data-level="10.4" data-path="estimation.html"><a href="estimation.html#robust-estimators"><i class="fa fa-check"></i><b>10.4</b> Robust estimators</a></li>
<li class="chapter" data-level="10.5" data-path="estimation.html"><a href="estimation.html#requesting-alternative-and-robust-estimators-in-lavaan"><i class="fa fa-check"></i><b>10.5</b> Requesting alternative and robust estimators in lavaan</a></li>
<li class="chapter" data-level="10.6" data-path="estimation.html"><a href="estimation.html#alternative-calculation-of-the-ml-discrepancy-function-when-analysing-raw-data"><i class="fa fa-check"></i><b>10.6</b> Alternative calculation of the ML discrepancy function when analysing raw data</a></li>
<li class="chapter" data-level="10.7" data-path="estimation.html"><a href="estimation.html#using-fiml-to-analyse-raw-data-with-missing-values-in-lavaan"><i class="fa fa-check"></i><b>10.7</b> Using FIML to analyse raw data with missing values in lavaan</a></li>
<li class="chapter" data-level="10.8" data-path="estimation.html"><a href="estimation.html#references-5"><i class="fa fa-check"></i><b>10.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html"><i class="fa fa-check"></i><b>11</b> Path Analysis with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="11.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#prepare-data-and-workspace-1"><i class="fa fa-check"></i><b>11.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#import-example-data-1"><i class="fa fa-check"></i><b>11.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="11.1.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#summarize-data"><i class="fa fa-check"></i><b>11.1.2</b> Summarize Data</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#regression-models-for-binary-variables"><i class="fa fa-check"></i><b>11.2</b> Regression Models for Binary Variables</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#fit-a-logistic-regression-model"><i class="fa fa-check"></i><b>11.2.1</b> Fit a Logistic Regression Model</a></li>
<li class="chapter" data-level="11.2.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#fit-a-probit-regression-model"><i class="fa fa-check"></i><b>11.2.2</b> Fit a Probit Regression Model</a></li>
<li class="chapter" data-level="11.2.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#compare-models"><i class="fa fa-check"></i><b>11.2.3</b> Compare Models</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#latent-response-variable"><i class="fa fa-check"></i><b>11.3</b> Latent Response Variable</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#ordinal-outcomes"><i class="fa fa-check"></i><b>11.3.1</b> Ordinal Outcomes</a></li>
<li class="chapter" data-level="11.3.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-thresholds"><i class="fa fa-check"></i><b>11.3.2</b> Estimating Thresholds</a></li>
<li class="chapter" data-level="11.3.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-polychoric-correlations"><i class="fa fa-check"></i><b>11.3.3</b> Estimating Polychoric Correlations</a></li>
<li class="chapter" data-level="11.3.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-an-sem-with-estimated-input"><i class="fa fa-check"></i><b>11.3.4</b> Estimating an SEM with Estimated Input</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#mediation-model-with-categorical-outcomes"><i class="fa fa-check"></i><b>11.4</b> Mediation Model with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimate-mediation-models"><i class="fa fa-check"></i><b>11.4.1</b> Estimate Mediation Models</a></li>
<li class="chapter" data-level="11.4.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#interpreting-coefficients"><i class="fa fa-check"></i><b>11.4.2</b> Interpreting Coefficients</a></li>
<li class="chapter" data-level="11.4.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#delta-vs.-theta-parameterizations"><i class="fa fa-check"></i><b>11.4.3</b> Delta vs. Theta Parameterizations</a></li>
<li class="chapter" data-level="11.4.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#decomposing-total-effects"><i class="fa fa-check"></i><b>11.4.4</b> Decomposing Total Effects</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#references-6"><i class="fa fa-check"></i><b>11.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html"><i class="fa fa-check"></i><b>12</b> Fitting path models with multilevel data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#intraclass-correlation"><i class="fa fa-check"></i><b>12.1</b> Intraclass correlation</a></li>
<li class="chapter" data-level="12.2" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#multilevel-structure-as-a-nuisance-correcting-for-the-dependency"><i class="fa fa-check"></i><b>12.2</b> Multilevel structure as a nuisance: Correcting for the dependency</a></li>
<li class="chapter" data-level="12.3" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#two-level-path-models"><i class="fa fa-check"></i><b>12.3</b> Two-level path models</a></li>
<li class="chapter" data-level="12.4" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#obtaining-iccs-and-estimates-of-sigma_textw-and-sigma_textb"><i class="fa fa-check"></i><b>12.4</b> Obtaining ICCs, and estimates of <span class="math inline">\(\Sigma_\text{W}\)</span> and <span class="math inline">\(\Sigma_\text{B}\)</span></a></li>
<li class="chapter" data-level="12.5" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#fitting-a-two-level-path-model"><i class="fa fa-check"></i><b>12.5</b> Fitting a two-level path model</a></li>
<li class="chapter" data-level="12.6" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#references-7"><i class="fa fa-check"></i><b>12.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html"><i class="fa fa-check"></i><b>13</b> Latent Growth Curve Models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#prepare-data-and-workspace-2"><i class="fa fa-check"></i><b>13.1</b> Prepare Data and Workspace</a></li>
<li class="chapter" data-level="13.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#random-intercept-model"><i class="fa fa-check"></i><b>13.2</b> Random Intercept Model</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#specification-and-estimation"><i class="fa fa-check"></i><b>13.2.1</b> Specification and Estimation</a></li>
<li class="chapter" data-level="13.2.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#interpret-results"><i class="fa fa-check"></i><b>13.2.2</b> Interpret Results</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#linear-growth-model"><i class="fa fa-check"></i><b>13.3</b> Linear Growth Model</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#model-fit-and-comparison"><i class="fa fa-check"></i><b>13.3.1</b> Model Fit and Comparison</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#unrestricted-growth-models"><i class="fa fa-check"></i><b>13.4</b> Unrestricted Growth Models</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#latent-basis-curve"><i class="fa fa-check"></i><b>13.4.1</b> Latent Basis Curve</a></li>
<li class="chapter" data-level="13.4.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#saturated-growth-model"><i class="fa fa-check"></i><b>13.4.2</b> Saturated Growth Model</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#explaining-growth-factors"><i class="fa fa-check"></i><b>13.5</b> Explaining Growth Factors</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#time-invariant-level-2-predictors"><i class="fa fa-check"></i><b>13.5.1</b> Time-Invariant (Level-2) Predictors</a></li>
<li class="chapter" data-level="13.5.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#time-varying-level-1-predictors"><i class="fa fa-check"></i><b>13.5.2</b> Time-Varying (Level-1) Predictors</a></li>
<li class="chapter" data-level="13.5.3" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#parallel-growth-curves"><i class="fa fa-check"></i><b>13.5.3</b> Parallel Growth Curves</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#latent-indicators-of-growth-factors"><i class="fa fa-check"></i><b>13.6</b> Latent Indicators of Growth Factors</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#common-factors"><i class="fa fa-check"></i><b>13.6.1</b> Common Factors</a></li>
<li class="chapter" data-level="13.6.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#discrete-indicators"><i class="fa fa-check"></i><b>13.6.2</b> Discrete Indicators</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#multigroup-growth-models"><i class="fa fa-check"></i><b>13.7</b> Multigroup Growth Models</a></li>
<li class="chapter" data-level="13.8" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#references-8"><i class="fa fa-check"></i><b>13.8</b> References</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Compendium Structural Equation Modeling in Educational Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="latent-growth-curve-models" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">13</span> Latent Growth Curve Models<a href="latent-growth-curve-models.html#latent-growth-curve-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In structural equation modeling (SEM), multiple indicators of a construct can be modeled using exploratory/confirmatory factor analysis (E/CFA). A latent common factor (or common cause) is posited as being the source of shared variance among the observed indicators, and the measurement models for multiple common factors can be embedded within a larger SEM.</p>
<p>This chapter introduces another type of common factor, often called a <strong>growth factor</strong>. Rather than repeatedly measuring a construct with <em>different</em> indicators of that construct (e.g., “I feel …”: happy, glad, cheerful, joyous), growth factors are measured by the <em>same</em> indicator on multiple occasions. Growth factors are interpreted as patterns of change in the indicators’ expected values, where the type of pattern is defined by the factor loadings.</p>
<p>In this chapter we first import and summarize example data, then we use a single-factor model to illustrate differences between growth factors and other common factors (e.g., specification and interpretation). Readers familiar with multilevel modeling (MLM) will benefit from a brief comparison between MLM and SEM for the same data. Next, we 2-factor model for linear growth (again comparing it to a MLM for change) and saturated growth model (comparing it to repeated-measures ANOVA). We conclude by discussing important caveats with some common extensions to the latent growth curve model (LGCM):</p>
<ul>
<li>predictors of growth</li>
<li>latent indicators of growth</li>
<li>comparing growth across groups</li>
</ul>
<div id="prepare-data-and-workspace-2" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Prepare Data and Workspace<a href="latent-growth-curve-models.html#prepare-data-and-workspace-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="latent-growth-curve-models.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code></pre></div>
<p>For illustration, we will use summary statistics reported by Duncan and Duncan (1996, pp. 329–330). <code>alc</code>ohol, <code>cig</code>arette, and cannabis use (<code>thc</code>) were each measured annually for 4 years using a 5-point scale:</p>
<ol style="list-style-type: decimal">
<li>never used</li>
<li>previous but not current use</li>
<li>current use of &lt; 4 times per month)</li>
<li>current use of 4–29 times per month</li>
<li>current use of <span class="math inline">\(\ge 30\)</span> times per month</li>
</ol>
<p>We also imported 2 variables measured at the beginning of the study:</p>
<ul>
<li><code>age</code> (recruited between 11 and 15 years old)</li>
<li><code>peer</code> encouragement, measured by summing 3 items (<code>alc</code>, <code>cig</code>, <code>thc</code>) using a 5-point Likert scale indicating how much their best friend encouraged use of that substance</li>
</ul>
<p>The following summary statistics were observed for the <span class="math inline">\(N=321\)</span> adolescents who provided complete data in all 4 years.</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="latent-growth-curve-models.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="do">## variable names</span></span>
<span id="cb289-2"><a href="latent-growth-curve-models.html#cb289-2" aria-hidden="true" tabindex="-1"></a>vn <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">&quot;alc&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>), <span class="fu">paste0</span>(<span class="st">&quot;cig&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>), <span class="fu">paste0</span>(<span class="st">&quot;thc&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),<span class="st">&quot;age&quot;</span>,<span class="st">&quot;peer&quot;</span>)</span>
<span id="cb289-3"><a href="latent-growth-curve-models.html#cb289-3" aria-hidden="true" tabindex="-1"></a><span class="do">## mean vector</span></span>
<span id="cb289-4"><a href="latent-growth-curve-models.html#cb289-4" aria-hidden="true" tabindex="-1"></a>duncanM <span class="ot">&lt;-</span> <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="fl">2.271</span>, <span class="fl">2.560</span>, <span class="fl">2.694</span>, <span class="fl">2.965</span>,    <span class="fl">1.847</span>, <span class="fl">2.043</span>, <span class="fl">2.227</span>, <span class="fl">2.510</span>,</span>
<span id="cb289-5"><a href="latent-growth-curve-models.html#cb289-5" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">1.510</span>, <span class="fl">1.672</span>, <span class="fl">1.828</span>, <span class="fl">1.947</span>,   <span class="fl">13.108</span>, <span class="fl">6.193</span>), <span class="at">nm =</span> vn)</span>
<span id="cb289-6"><a href="latent-growth-curve-models.html#cb289-6" aria-hidden="true" tabindex="-1"></a><span class="do">## they reported variances (squared SDs)</span></span>
<span id="cb289-7"><a href="latent-growth-curve-models.html#cb289-7" aria-hidden="true" tabindex="-1"></a>sqSDs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.004</span>,  .<span class="dv">922</span>,  .<span class="dv">832</span>,  .<span class="dv">846</span>,    <span class="fl">1.305</span>, <span class="fl">1.536</span>, <span class="fl">1.645</span>, <span class="fl">1.888</span>,</span>
<span id="cb289-8"><a href="latent-growth-curve-models.html#cb289-8" aria-hidden="true" tabindex="-1"></a>            .<span class="dv">807</span>,  .<span class="dv">896</span>, <span class="fl">1.074</span>, <span class="fl">1.125</span>,    <span class="fl">2.216</span>, <span class="fl">8.844</span>)</span>
<span id="cb289-9"><a href="latent-growth-curve-models.html#cb289-9" aria-hidden="true" tabindex="-1"></a><span class="do">## correlation matrix (lower triangle)</span></span>
<span id="cb289-10"><a href="latent-growth-curve-models.html#cb289-10" aria-hidden="true" tabindex="-1"></a>tri <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.000</span>,</span>
<span id="cb289-11"><a href="latent-growth-curve-models.html#cb289-11" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">640</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-12"><a href="latent-growth-curve-models.html#cb289-12" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">586</span>,  .<span class="dv">670</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-13"><a href="latent-growth-curve-models.html#cb289-13" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">454</span>,  .<span class="dv">566</span>,  .<span class="dv">621</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-14"><a href="latent-growth-curve-models.html#cb289-14" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">568</span>,  .<span class="dv">451</span>,  .<span class="dv">390</span>,  .<span class="dv">357</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-15"><a href="latent-growth-curve-models.html#cb289-15" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">531</span>,  .<span class="dv">449</span>,  .<span class="dv">360</span>,  .<span class="dv">360</span>,  .<span class="dv">850</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-16"><a href="latent-growth-curve-models.html#cb289-16" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">494</span>,  .<span class="dv">449</span>,  .<span class="dv">380</span>,  .<span class="dv">425</span>,  .<span class="dv">783</span>,  .<span class="dv">815</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-17"><a href="latent-growth-curve-models.html#cb289-17" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">387</span>,  .<span class="dv">393</span>,  .<span class="dv">344</span>,  .<span class="dv">473</span>,  .<span class="dv">617</span>,  .<span class="dv">702</span>,  .<span class="dv">779</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-18"><a href="latent-growth-curve-models.html#cb289-18" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">602</span>,  .<span class="dv">431</span>,  .<span class="dv">408</span>,  .<span class="dv">346</span>,  .<span class="dv">706</span>,  .<span class="dv">648</span>,  .<span class="dv">576</span>,  .<span class="dv">543</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-19"><a href="latent-growth-curve-models.html#cb289-19" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">522</span>,  .<span class="dv">460</span>,  .<span class="dv">394</span>,  .<span class="dv">403</span>,  .<span class="dv">644</span>,  .<span class="dv">689</span>,  .<span class="dv">687</span>,  .<span class="dv">535</span>,  .<span class="dv">759</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-20"><a href="latent-growth-curve-models.html#cb289-20" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">499</span>,  .<span class="dv">461</span>,  .<span class="dv">440</span>,  .<span class="dv">472</span>,  .<span class="dv">542</span>,  .<span class="dv">592</span>,  .<span class="dv">676</span>,  .<span class="dv">566</span>,  .<span class="dv">671</span>,  .<span class="dv">790</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-21"><a href="latent-growth-curve-models.html#cb289-21" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">398</span>,  .<span class="dv">385</span>,  .<span class="dv">358</span>,  .<span class="dv">472</span>,  .<span class="dv">452</span>,  .<span class="dv">522</span>,  .<span class="dv">594</span>,  .<span class="dv">644</span>,  .<span class="dv">533</span>,  .<span class="dv">642</span>,  .<span class="dv">793</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-22"><a href="latent-growth-curve-models.html#cb289-22" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">497</span>,  .<span class="dv">370</span>,  .<span class="dv">429</span>,  .<span class="dv">326</span>,  .<span class="dv">418</span>,  .<span class="dv">409</span>,  .<span class="dv">337</span>,  .<span class="dv">205</span>,  .<span class="dv">456</span>,  .<span class="dv">413</span>,  .<span class="dv">345</span>,  .<span class="dv">248</span>, <span class="fl">1.000</span>,</span>
<span id="cb289-23"><a href="latent-growth-curve-models.html#cb289-23" aria-hidden="true" tabindex="-1"></a>          .<span class="dv">336</span>,  .<span class="dv">398</span>,  .<span class="dv">300</span>,  .<span class="dv">276</span>,  .<span class="dv">397</span>,  .<span class="dv">433</span>,  .<span class="dv">386</span>,  .<span class="dv">318</span>,  .<span class="dv">388</span>,  .<span class="dv">522</span>,  .<span class="dv">421</span>,  .<span class="dv">342</span>,  .<span class="dv">273</span>, <span class="dv">1</span>)</span>
<span id="cb289-24"><a href="latent-growth-curve-models.html#cb289-24" aria-hidden="true" tabindex="-1"></a><span class="do">## scale tri to make covariance matrix</span></span>
<span id="cb289-25"><a href="latent-growth-curve-models.html#cb289-25" aria-hidden="true" tabindex="-1"></a>duncanCOV <span class="ot">&lt;-</span> <span class="fu">getCov</span>(<span class="at">x =</span> tri, <span class="at">sds =</span> <span class="fu">sqrt</span>(sqSDs), <span class="at">names =</span> vn)</span>
<span id="cb289-26"><a href="latent-growth-curve-models.html#cb289-26" aria-hidden="true" tabindex="-1"></a><span class="do">## sample size</span></span>
<span id="cb289-27"><a href="latent-growth-curve-models.html#cb289-27" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">321</span></span></code></pre></div>
</div>
<div id="random-intercept-model" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Random Intercept Model<a href="latent-growth-curve-models.html#random-intercept-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s focus on a single measure—alcohol use—measured on 4 occasions for each of <span class="math inline">\(N=321\)</span> adolescents. A random-intercept model for Subject <span class="math inline">\(i\)</span>’s alcohol use in Year <span class="math inline">\(t\)</span> is frequently depicted in MLM as:</p>
<p><span class="math display">\[\begin{align}
y_{i,t} &amp;= \beta_{i,0} + \varepsilon_{i,t} \label{eq:ri} \\
        &amp;= (\gamma_{0} + u_i) + \varepsilon_{i,t} \label{eq:ri-decomp}
\end{align}\]</span></p>
<p>indicating that each Subject <span class="math inline">\(i\)</span> has their own intercept, so the random intercept <span class="math inline">\(\beta_{i,0}\)</span> is itself a variable. As Eq. <span class="math inline">\(\ref{eq:ri-decomp}\)</span> shows, the average intercept can be depicted as the sum of 2 components:</p>
<ul>
<li>the average intercept (<span class="math inline">\(\gamma_{0}\)</span>)
<ul>
<li>This is the grand mean because there are no other predictors.</li>
</ul></li>
<li>individual deviations around <span class="math inline">\(\gamma_{0}\)</span> (i.e., <span class="math inline">\(u_i\)</span>)
<ul>
<li>This is how much each subject’s mean differs from the grand mean.</li>
<li>This can also be interpreted as a Level-2 residual</li>
</ul></li>
</ul>
<p>The Level-1 residual (<span class="math inline">\(\varepsilon_{i,t}\)</span>) is how much each subject’s time-specific alcohol use differs from their average alcohol use. Both residuals have distributional assumptions, often depicted as normally distributed with some variance:</p>
<p><span class="math display">\[u_i \sim \mathcal{N}(0, \tau_0) \ \ \ , \ \ \ \varepsilon_{i,t} \sim \mathcal{N}(0, \sigma)\]</span></p>
<p>This MLM can also be represented as a SEM. In fact, <em>random effects</em> are latent variables (Mehta &amp; Neale, 2005; Skrondal &amp; Rabe-Hesketh, 2004). The SEM representation of Eqs. <span class="math inline">\(\ref{eq:ri}\)</span>–<span class="math inline">\(\ref{eq:ri-decomp}\)</span> looks superficially different: there are different symbols, and Subject <span class="math inline">\(i\)</span>’s <span class="math inline">\(t=1, \dots, T\)</span> measurements are stored in a single vector <span class="math inline">\(\mathbf{y}_i\)</span>:</p>
<p><span class="math display">\[\begin{align*}
\mathbf{y}_i    &amp;= \Lambda \mathbf{\eta}_i + \varepsilon_i \\
\mathbf{\eta}_i &amp;= \alpha + \zeta_i
\end{align*}\]</span></p>
<p>Note that many parameters from the full SEM are missing (e.g., indicator intercepts <span class="math inline">\(\tau\)</span> and latent regressions <span class="math inline">\(\mathbf{B}\)</span>) because they are merely 0 in this model. But the nonzero components of this SEM can all be mapped onto the MLM above (Bauer, 2003; Curran, 2003; Singer &amp; Willett, 2003, ch. 8):</p>
<p><span class="math display">\[\mathbf{\eta}_i=\beta_{0,i} \ \ , \ \ \alpha=\gamma_0 \ \ , \ \ \zeta_i=u_i    \ \ , \ \ \varepsilon_i=\varepsilon_i \ \ , \ \ \Lambda=\mathbf{1}\]</span></p>
<p>Note that the factor-loading matrix is merely a vector of ones, filling the role of the constant in a regression model. That is, a vector of ones is treated as a predictor, and its “slope” is the regression model’s intercept. The role of factor loadings in a LGCM is counter-intuitive because in most SEMs, we think of them as slopes. Instead, the loadings of a growth factor instead map onto observed variables in a multilevel regression, and random coefficients (<span class="math inline">\(\beta_{0,i}\)</span>) are represented by the latent variables (growth factors: <span class="math inline">\(\mathbf{\eta}_i\)</span>).</p>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(1\)</span>. Random intercept model for alcohol-use data from Duncan and Duncan (1996).</p>
<p>The path diagram above illuminates the differences between a growth factor (here, a random intercept) and a common factor. First, factor loadings in a CFA are freely estimated, and they indicate how strongly an indicator is related to the common factor. In a LGCM, <strong>factor loadings are fixed to specify how the growth factor is interpreted</strong>. A random intercept’s loadings are all 1 because every occasion’s <span class="math inline">\(y_i\)</span> is weighted equally to calculate the Subject <span class="math inline">\(i\)</span>’s overall mean.</p>
<p>Second, indicator intercepts in a CFA are freely estimated, and are the indicators’ expected values when the common factor = 0. Because the common-factor mean is typically constrained to zero for identification, indicator intercepts are often simply the indicator means. In a LGCM, indicator intercepts are fixed to zero, but the growth-factor mean is freely estimated. Thus, the only reason that an indicator’s model-implied mean differs from zero is if the latent intercept’s mean differs from zero. This is a primary feature of an LGCM: <strong>the mean structure of the indicators is captured entirely by the mean structure of the growth factors</strong>. Thus, this random-intercept model reflects the hypothesis that the mean (<span class="math inline">\(\alpha_1\)</span>: here, average alcohol use) is equal across occasions, although the means can still vary across subjects (<span class="math inline">\(\psi_{1,1}\)</span>).</p>
<p>The mean structure of the latent curve model is a special case of the mean structure of a “normal” factor model, where the mean structure is given by: <span class="math inline">\(\mu=\tau+\mathbf{\Lambda}\kappa\)</span>, where <span class="math inline">\(\mu\)</span> (“mu”) is a column vector of model-implied means of the observed variables, <span class="math inline">\(\tau\)</span> (“tau”) is a column vector of indicator intercepts, <span class="math inline">\(\mathbf{\Lambda}\)</span> (“lambda”) is a matrix of factor loadings, and <span class="math inline">\(\kappa\)</span> (“kappa”) is a column vector of latent growth-factor means. Because all growth indicators have intercepts fixed to 0, the equation for the mean structure simplifies to <span class="math inline">\(\mu=\mathbf{\Lambda}\kappa\)</span>. And because this chapter includes examples for growth factors being predicted by other variables (a “full SEM”), we will refer to both means and intercepts of growth factors as <span class="math inline">\(\alpha\)</span> (the path-model notation).</p>
<div id="specification-and-estimation" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> Specification and Estimation<a href="latent-growth-curve-models.html#specification-and-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following <code>lavaan</code> model syntax specifies the model from Figure 1.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="latent-growth-curve-models.html#cb290-1" aria-hidden="true" tabindex="-1"></a>mod.ri <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings for random intercept</span></span>
<span id="cb290-2"><a href="latent-growth-curve-models.html#cb290-2" aria-hidden="true" tabindex="-1"></a><span class="st">    INTERCEPT =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4</span></span>
<span id="cb290-3"><a href="latent-growth-curve-models.html#cb290-3" aria-hidden="true" tabindex="-1"></a><span class="st">  ## residual variances</span></span>
<span id="cb290-4"><a href="latent-growth-curve-models.html#cb290-4" aria-hidden="true" tabindex="-1"></a><span class="st">    alc1 ~~ alc1</span></span>
<span id="cb290-5"><a href="latent-growth-curve-models.html#cb290-5" aria-hidden="true" tabindex="-1"></a><span class="st">    alc2 ~~ alc2</span></span>
<span id="cb290-6"><a href="latent-growth-curve-models.html#cb290-6" aria-hidden="true" tabindex="-1"></a><span class="st">    alc3 ~~ alc3</span></span>
<span id="cb290-7"><a href="latent-growth-curve-models.html#cb290-7" aria-hidden="true" tabindex="-1"></a><span class="st">    alc4 ~~ alc4</span></span>
<span id="cb290-8"><a href="latent-growth-curve-models.html#cb290-8" aria-hidden="true" tabindex="-1"></a><span class="st">  ## latent mean and variance</span></span>
<span id="cb290-9"><a href="latent-growth-curve-models.html#cb290-9" aria-hidden="true" tabindex="-1"></a><span class="st">    INTERCEPT ~ 1</span></span>
<span id="cb290-10"><a href="latent-growth-curve-models.html#cb290-10" aria-hidden="true" tabindex="-1"></a><span class="st">    INTERCEPT ~~ INTERCEPT</span></span>
<span id="cb290-11"><a href="latent-growth-curve-models.html#cb290-11" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb290-12"><a href="latent-growth-curve-models.html#cb290-12" aria-hidden="true" tabindex="-1"></a>fit.ri <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.ri, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb290-13"><a href="latent-growth-curve-models.html#cb290-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sample.nobs =</span> N)</span></code></pre></div>
<p>The <code>lavaan</code> package has a dedicated <code>growth()</code> package, with default <code>lavOptions()</code> that make sense for a LGCM:</p>
<ul>
<li><code>int.ov.free = FALSE</code> leaves indicator intercepts fixed to zero</li>
<li><code>int.lv.free = TRUE</code> freely estimates latent intercepts/means</li>
<li><code>auto.var = TRUE</code> freely estimates all variances</li>
<li><code>auto.cov.lv.x = TRUE</code> freely estimates covariances among exogenous latent variables</li>
</ul>
<p>So a shorter syntax could simply specify the factor loadings for the growth factor(s):</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="latent-growth-curve-models.html#cb291-1" aria-hidden="true" tabindex="-1"></a>mod.ri <span class="ot">&lt;-</span> <span class="st">&#39; INTERCEPT =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4 &#39;</span></span>
<span id="cb291-2"><a href="latent-growth-curve-models.html#cb291-2" aria-hidden="true" tabindex="-1"></a>fit.ri <span class="ot">&lt;-</span> <span class="fu">growth</span>(mod.ri, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb291-3"><a href="latent-growth-curve-models.html#cb291-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sample.nobs =</span> N)</span></code></pre></div>
<p>However, as LGCMs become more complex (e.g., latent indicators of growth), this set of <code>lavOptions()</code> becomes problematic. Thus, we advise and demonstrate using the basic <code>lavaan()</code> function, either with fully specified model syntax or by explicitly setting <code>lavOptions()</code> that make sense. For example:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="latent-growth-curve-models.html#cb292-1" aria-hidden="true" tabindex="-1"></a>mod.ri <span class="ot">&lt;-</span> <span class="st">&#39; INTERCEPT =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4 &#39;</span></span>
<span id="cb292-2"><a href="latent-growth-curve-models.html#cb292-2" aria-hidden="true" tabindex="-1"></a>fit.ri <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.ri, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb292-3"><a href="latent-growth-curve-models.html#cb292-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="interpret-results" class="section level3 hasAnchor" number="13.2.2">
<h3><span class="header-section-number">13.2.2</span> Interpret Results<a href="latent-growth-curve-models.html#interpret-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The results in the <code>summary()</code> output indicate that the grand mean alcohol use in this sample is 2.638, which is between “previous but not current use” and “&lt; 4 times per month” on the 1–5 scale.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="latent-growth-curve-models.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(fit.ri, <span class="at">output =</span> <span class="st">&quot;pretty&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   INTERCEPT =~                                                          
##     alc1              1.000                               1.000    1.000
##     alc2              1.000                               1.000    1.000
##     alc3              1.000                               1.000    1.000
##     alc4              1.000                               1.000    1.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##     INTERCEPT         2.638    0.045   59.223    0.000    2.551    2.725
##    .alc1              0.000                               0.000    0.000
##    .alc2              0.000                               0.000    0.000
##    .alc3              0.000                               0.000    0.000
##    .alc4              0.000                               0.000    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .alc1              0.646    0.059   11.026    0.000    0.531    0.761
##    .alc2              0.321    0.035    9.293    0.000    0.253    0.389
##    .alc3              0.257    0.030    8.467    0.000    0.198    0.317
##    .alc4              0.549    0.051   10.729    0.000    0.449    0.650
##     INTERCEPT         0.541    0.051   10.697    0.000    0.442    0.640</code></pre>
<p>The <code>INTERCEPT</code> variance indicates that individual subjects’ means vary <span class="math inline">\(SD = \sqrt{0.541} = 0.736\)</span> around the grand mean, frequently referred to as the Level-2 variance in a MLM. Whereas a MLM only estimates a single Level-1 residual variance, the SEM approach is more flexible in allowing Level-1 residuals to be heteroskedastic across time (i.e., the degree to which time-specific observations deviate from subject means). The <span class="math inline">\(H_0\)</span> of homoskedasticity could be tested by comparing this fitted model to one in which the residual variances are constrained to equality.</p>
</div>
</div>
<div id="linear-growth-model" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Linear Growth Model<a href="latent-growth-curve-models.html#linear-growth-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A linear LGCM has two growth factors:</p>
<ul>
<li>a random intercept (the subject’s initial status)</li>
<li>a random slope (the subject’s rate of change)</li>
</ul>
<p>In order to prevent confusion of the terms intercept and slope with other model parameters, we will refer to the growth factors as initial status and rate of change (Singer &amp; Willett, 2003).</p>
<p>Each growth factor has a mean (the average initial status and rate of change across subjects) and a variance (individual differences in initial status and rate of change). Just as in MLM, the random intercept and random slope can covary.</p>
<p>Recall that the factor loadings in a LGCM are specified to according to how the growth factors should be interpreted—specifically, the loadings in <span class="math inline">\(\mathbf{\Lambda}\)</span> correspond to the matrix of predictors (<span class="math inline">\(\mathbf{X}\)</span>) in a regression model. Thus, it is more appropriate to think of <span class="math inline">\(\mathbf{\Lambda}\)</span> as observed data and of the growth factors as slopes (which vary across subjects). In addition to a column of ones (to estimate the latent intercept), the matrix of factor loadings for linear growth includes a column of values indicating how <em>time</em> should be coded. Figure 2 depicts a common choice for coding time: the number of years (or other units) elapsed since the beginning of the study.</p>
<p><span class="math display">\[\mathbf{X}_i \Longleftrightarrow \mathbf{\Lambda} = \begin{bmatrix} 1 &amp; 0 \\ 1 &amp; 1 \\ 1 &amp; 2 \\ 1 &amp; 3\end{bmatrix}\]</span></p>
<p>The first row of loadings implies that the expected value of the first indicator is only a function of the first growth factor’s mean, because the second column contains a zero. For each subsequent row, that indicator’s expected value is a sum of the mean initial-status plus increasing amounts of the mean rate of change. Specifically, the mean rate of change is multiplied by the second column’s loading, similar to a regular regression, in which the slope (rate of change: <span class="math inline">\(\beta_1\)</span>) is multiplied by the value of time.</p>
<p>Note that these specified loadings are arbitrary. We could code time using a different occasion as the reference, such as the last occasion:</p>
<p><span class="math display">\[\mathbf{X}_i \Longleftrightarrow \mathbf{\Lambda} = \begin{bmatrix} 1 &amp; -3 \\ 1 &amp; -2 \\ 1 &amp; -1 \\ 1 &amp; 0\end{bmatrix}\]</span></p>
<p>Using this alternative coding scheme, the mean rate-of-change would remain the same, but the mean of the latent intercept would instead be interpreted as the average status at the <em>end</em> of the study (<em>final</em> status, rather than <em>initial</em> status). However, we will proceed by coding 0 for the first occasion so that the latent intercept represents initial status.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(2\)</span>. Linear growth model for alcohol-use data from Duncan and Duncan (1996).</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="latent-growth-curve-models.html#cb295-1" aria-hidden="true" tabindex="-1"></a>mod.lin <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings</span></span>
<span id="cb295-2"><a href="latent-growth-curve-models.html#cb295-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4</span></span>
<span id="cb295-3"><a href="latent-growth-curve-models.html#cb295-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~          1*alc2 + 2*alc3 + 3*alc4</span></span>
<span id="cb295-4"><a href="latent-growth-curve-models.html#cb295-4" aria-hidden="true" tabindex="-1"></a><span class="st">  ## factor covariance</span></span>
<span id="cb295-5"><a href="latent-growth-curve-models.html#cb295-5" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Rate.Change</span></span>
<span id="cb295-6"><a href="latent-growth-curve-models.html#cb295-6" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb295-7"><a href="latent-growth-curve-models.html#cb295-7" aria-hidden="true" tabindex="-1"></a>fit.lin <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.lin, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb295-8"><a href="latent-growth-curve-models.html#cb295-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb295-9"><a href="latent-growth-curve-models.html#cb295-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.lin, <span class="at">std =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-11 ended normally after 27 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
##                                                       
##   Number of observations                           321
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                 8.174
##   Degrees of freedom                                 5
##   P-value (Chi-square)                           0.147
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status =~                                                        
##     alc1              1.000                               0.836    0.820
##     alc2              1.000                               0.836    0.889
##     alc3              1.000                               0.836    0.931
##     alc4              1.000                               0.836    0.895
##   Rate.Change =~                                                        
##     alc2              1.000                               0.195    0.208
##     alc3              2.000                               0.391    0.435
##     alc4              3.000                               0.586    0.628
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status ~~                                                        
##     Rate.Change      -0.080    0.023   -3.504    0.000   -0.489   -0.489
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.000                               0.000    0.000
##    .alc2              0.000                               0.000    0.000
##    .alc3              0.000                               0.000    0.000
##    .alc4              0.000                               0.000    0.000
##     Init.Status       2.291    0.054   42.558    0.000    2.739    2.739
##     Rate.Change       0.220    0.018   12.342    0.000    1.128    1.128
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.341    0.051    6.660    0.000    0.341    0.328
##    .alc2              0.306    0.033    9.337    0.000    0.306    0.346
##    .alc3              0.274    0.030    9.224    0.000    0.274    0.339
##    .alc4              0.309    0.046    6.726    0.000    0.309    0.354
##     Init.Status       0.700    0.077    9.064    0.000    1.000    1.000
##     Rate.Change       0.038    0.010    3.665    0.000    1.000    1.000</code></pre>
<p>The initial-status mean indicates average alcohol use began as 2.291, and the rate-of-change mean indicates average alcohol use increased by 0.220 per year. The standardized solution is not particularly meaningful for some LGCM parameters (e.g., loadings, latent means), but it is helpful for interpreting the size of the (significant) covariance between initial status and rate of change. The substantial factor correlation (<span class="math inline">\(-0.489\)</span>) indicates that adolescents who drank <em>less</em> at the beginning of the study tended to increase the drinking at a <em>higher</em> annual rate.</p>
<div id="model-fit-and-comparison" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Model Fit and Comparison<a href="latent-growth-curve-models.html#model-fit-and-comparison" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The model-fit test statistic in the <code>summary()</code> output does not provide any evidence against the <span class="math inline">\(H_0\)</span> that linear change is sufficiently complex to describe the data, <span class="math inline">\(\chi^2(5)=8.174, p=.147\)</span>. Linear change is the simplest functional form of change, and significant latent mean, <span class="math inline">\(z=12.342, p&lt;.001\)</span>, indicates that the model cannot be made simpler by omitting linear change. We can verify this by testing whether the random-intercept model statistically differs from the linear growth model in which it is nested. Because the linear-growth loadings are all fixed values, the random-intercept model can be seen as a linear-growth model in which the latent rate of change has a mean and variance of zero (in which case it cannot covary with another factor).</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="latent-growth-curve-models.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit.ri, fit.lin) <span class="co"># or anova(fit.ri, fit.lin)</span></span></code></pre></div>
<pre><code>## Chi-Squared Difference Test
## 
##         Df    AIC    BIC   Chisq Chisq diff Df diff Pr(&gt;Chisq)    
## fit.lin  5 2963.8 2997.7   8.174                                  
## fit.ri   8 3128.8 3151.4 179.175        171       3  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The linear growth model captures the observed data patterns significantly better than the random-intercept model, <span class="math inline">\(\chi^2(3)=171.001, p&lt;.001\)</span>.</p>
<p>The standard baseline model for calculating incremental-fit indices (e.g., CFI, TLI) is merely the statistical-independence model:</p>
<ul>
<li>all covariances fixed to zero</li>
<li>means and variances are freely estimated</li>
</ul>
<p>But this model is not nested within all competing LGCMs Even the linear-growth model places more constraints on the mean structure than the standard independence model, and it also constrains the model-implied variances. Thus, Widamin and Thompson (2003) recommended a more constrained null/baseline model in which all means (and all variances) of repeatedly measured variables are constrained to equality (representing no change in those values).</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="latent-growth-curve-models.html#cb299-1" aria-hidden="true" tabindex="-1"></a>mod.null <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="fu">paste0</span>(<span class="st">&quot;alc&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">collapse =</span> <span class="st">&quot; + &quot;</span>), <span class="st">&quot;~ m*1&quot;</span>),</span>
<span id="cb299-2"><a href="latent-growth-curve-models.html#cb299-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">paste0</span>(<span class="st">&quot;alc&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="st">&quot; ~~ v*alc&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>))</span>
<span id="cb299-3"><a href="latent-growth-curve-models.html#cb299-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(mod.null, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>) <span class="co"># print model syntax to see what the code above does</span></span></code></pre></div>
<pre><code>## alc1 + alc2 + alc3 + alc4 ~ m*1
## alc1 ~~ v*alc1
## alc2 ~~ v*alc2
## alc3 ~~ v*alc3
## alc4 ~~ v*alc4</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="latent-growth-curve-models.html#cb301-1" aria-hidden="true" tabindex="-1"></a>fit.null <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.null, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb301-2"><a href="latent-growth-curve-models.html#cb301-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sample.nobs =</span> N)</span></code></pre></div>
<p>This model is nested within the LGCMs.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="latent-growth-curve-models.html#cb302-1" aria-hidden="true" tabindex="-1"></a>semTools<span class="sc">::</span><span class="fu">net</span>(fit.null, fit.ri, fit.lin)</span></code></pre></div>
<pre><code>## 
##         If cell [R, C] is TRUE, the model in row R is nested within column C.
## 
##         If the models also have the same degrees of freedom, they are equivalent.
## 
##         NA indicates the model in column C did not converge when fit to the
##         implied means and covariance matrix from the model in row R.
## 
##         The hidden diagonal is TRUE because any model is equivalent to itself.
##         The upper triangle is hidden because for models with the same degrees
##         of freedom, cell [C, R] == cell [R, C].  For all models with different
##         degrees of freedom, the upper diagonal is all FALSE because models with
##         fewer degrees of freedom (i.e., more parameters) cannot be nested
##         within models with more degrees of freedom (i.e., fewer parameters).
##         
##                    fit.lin fit.ri fit.null
## fit.lin (df = 5)                          
## fit.ri (df = 8)    TRUE                   
## fit.null (df = 12) TRUE    TRUE</code></pre>
<p>Thus, it can be used to calculate incremental fit indices, which requires using the <code>fitMeasures()</code> function rather than merely <code>summary(..., fit = TRUE)</code>.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="latent-growth-curve-models.html#cb304-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit.lin, <span class="fu">c</span>(<span class="st">&quot;cfi&quot;</span>,<span class="st">&quot;tli&quot;</span>), <span class="at">baseline.model =</span> fit.null)</span></code></pre></div>
<pre><code>##   cfi   tli 
## 0.995 0.988</code></pre>
</div>
</div>
<div id="unrestricted-growth-models" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Unrestricted Growth Models<a href="latent-growth-curve-models.html#unrestricted-growth-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="latent-growth-curve-models.html#cb306-1" aria-hidden="true" tabindex="-1"></a>mod.thc <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings</span></span>
<span id="cb306-2"><a href="latent-growth-curve-models.html#cb306-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*thc1 + 1*thc2 + 1*thc3 + 1*thc4</span></span>
<span id="cb306-3"><a href="latent-growth-curve-models.html#cb306-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~          1*thc2 + 2*thc3 + 3*thc4</span></span>
<span id="cb306-4"><a href="latent-growth-curve-models.html#cb306-4" aria-hidden="true" tabindex="-1"></a><span class="st">  ## factor covariance</span></span>
<span id="cb306-5"><a href="latent-growth-curve-models.html#cb306-5" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Rate.Change</span></span>
<span id="cb306-6"><a href="latent-growth-curve-models.html#cb306-6" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb306-7"><a href="latent-growth-curve-models.html#cb306-7" aria-hidden="true" tabindex="-1"></a>fit.thc <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.thc, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb306-8"><a href="latent-growth-curve-models.html#cb306-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb306-9"><a href="latent-growth-curve-models.html#cb306-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.thc, <span class="at">std =</span> <span class="cn">TRUE</span>)</span>
<span id="cb306-10"><a href="latent-growth-curve-models.html#cb306-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb306-11"><a href="latent-growth-curve-models.html#cb306-11" aria-hidden="true" tabindex="-1"></a>mod.cig <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings</span></span>
<span id="cb306-12"><a href="latent-growth-curve-models.html#cb306-12" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*cig1 + 1*cig2 + 1*cig3 + 1*cig4</span></span>
<span id="cb306-13"><a href="latent-growth-curve-models.html#cb306-13" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~          1*cig2 + 2*cig3 + 3*cig4</span></span>
<span id="cb306-14"><a href="latent-growth-curve-models.html#cb306-14" aria-hidden="true" tabindex="-1"></a><span class="st">  ## factor covariance</span></span>
<span id="cb306-15"><a href="latent-growth-curve-models.html#cb306-15" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Rate.Change</span></span>
<span id="cb306-16"><a href="latent-growth-curve-models.html#cb306-16" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb306-17"><a href="latent-growth-curve-models.html#cb306-17" aria-hidden="true" tabindex="-1"></a>fit.cig <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.cig, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb306-18"><a href="latent-growth-curve-models.html#cb306-18" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb306-19"><a href="latent-growth-curve-models.html#cb306-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.cig, <span class="at">std =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Although linear growth appears sufficient to explain these data, this will not always be the case. When a linear-growth model does not fit well, standardized residuals from <code>lavResiduals()</code> can reveal which summary statistics the model fails to reproduce closely. Large residuals for indicator means imply the mean structure is too restrictive, in which case an exploratory growth model can help to reveal how much more complex the latent trajectory is.</p>
<p>Note that this would be a switch from confirmatory to exploratory methods, so you would no longer be <em>testing</em> or (<em>dis</em>)confirming a hypothesis; instead, you would be <em>generating</em> a hypothesis or <em>revising</em> your theory. Transparency is vitally important to the scientific process, so clearly communicate in your report when you are conducting confirmatory vs. exploratory research, preferably in separate sections. That is, <strong>first test your theory</strong> using <em>a priori</em> hypotheses; if your data disconfirm your expectations, then begin looking for evidence in the data of how your theory should be revised.</p>
<p>Note also that specific hypotheses of nonlinear growth might be expected based on a study design. For example, trajectories might be expected to differ before and after a particular occasion (a <em>change-point</em>, e.g., an intervention or an important life event). In such cases, a <em>piecewise</em>-growth model can be specified, in which there is are separate latent rate-of-change factors whose loadings are specified to capture changes in means among indicators before and after the change-point.</p>
<p>There are a couple of options for exploratory LGCMs, described below.</p>
<div id="latent-basis-curve" class="section level3 hasAnchor" number="13.4.1">
<h3><span class="header-section-number">13.4.1</span> Latent Basis Curve<a href="latent-growth-curve-models.html#latent-basis-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The most popular is the <em>latent basis curve</em>, which resembles the linear model but only fixes 2 loadings for the rate-of-change factor, freeing the others to capture non-specific change patterns. For example, fixing the first 2 loadings to 0 and 1, respectively, sets the (average) amount of change between the first 2 occasions as a baseline. This is depicted in the path diagram below (left panel).</p>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(3\)</span>. Latent basis models for alcohol-use data from Duncan and Duncan (1996).</p>
<p>The script below specifies the model depicted in the left panel of Figure 3.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="latent-growth-curve-models.html#cb307-1" aria-hidden="true" tabindex="-1"></a>fit.basis12 <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.basis12, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb307-2"><a href="latent-growth-curve-models.html#cb307-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb307-3"><a href="latent-growth-curve-models.html#cb307-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.basis12)[<span class="fu">paste0</span>(<span class="st">&quot;Rate.Change=~alc&quot;</span>, <span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>)]</span></code></pre></div>
<pre><code>## Rate.Change=~alc3 Rate.Change=~alc4 
##          1.502240          2.466024</code></pre>
<p>The two fixed loadings determine the interpretation of the latent mean <span class="math inline">\(\alpha_2\)</span>, which is no longer a constant rate of change but rather the amount of <strong>change that occurred between the reference occasions</strong>.
Each estimated loading tells us how much (average) change occurred at that occasion since the first (or whichever occasion’s loading is fixed to 0), <strong>relative to</strong> the amount of change between the first 2 occasions. That is, there is a 1-unit increase in time, represented between the loadings of <code>alc1</code> and <code>alc2</code>. If change were <em>perfectly</em> linear, we would expect the estimated loadings to continue increasing by 1 unit at a time (assuming the occasions are evenly spread out, as they are in these annual measurements). However, we observe something different:</p>
<ul>
<li>There is only a 0.5-unit increase in the loadings from <code>alc2</code> to <code>alc3</code>, indicating that only half as much (average) change occurred between those 2 occasions than between the first 2 occasions.</li>
<li>There is a (nearly) 1-unit increase in the loadings from <code>alc3</code> to <code>alc4</code>, indicating that about as much change occurred between those occasions as between the first 2 occasions.</li>
</ul>
<p>This model estimates the average rate of change to be (<span class="math inline">\(0.281\)</span>), the unrestricted change pattern during this 4-year span appears to be an increase of <span class="math inline">\(0.281\)</span> units, then <span class="math inline">\(0.1405\)</span> units, then <span class="math inline">\(0.281\)</span> units again. To test whether this deviation from linearity can be accounted for by mere sampling error, we can conduct a nested model comparison:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="latent-growth-curve-models.html#cb309-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit.lin, fit.basis12) <span class="co"># or anova(fit.lin, fit.basis12)</span></span></code></pre></div>
<pre><code>## Chi-Squared Difference Test
## 
##             Df    AIC    BIC Chisq Chisq diff Df diff Pr(&gt;Chisq)  
## fit.basis12  3 2962.7 3004.2 3.114                                
## fit.lin      5 2963.8 2997.7 8.174     5.0601       2    0.07966 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We cannot reject the null hypothesis that linearity is sufficiently complex.</p>
<p>Another example of a latent basis curve fixes the first and <em>last</em> loadings to 0 and 1, respectively, with similar implications for interpretation. The script below specifies the model depicted in the right panel of Figure 3.</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="latent-growth-curve-models.html#cb311-1" aria-hidden="true" tabindex="-1"></a>fit.basis14 <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.basis14, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb311-2"><a href="latent-growth-curve-models.html#cb311-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb311-3"><a href="latent-growth-curve-models.html#cb311-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.basis14)[<span class="fu">paste0</span>(<span class="st">&quot;Rate.Change=~alc&quot;</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>)]</span></code></pre></div>
<pre><code>## Rate.Change=~alc2 Rate.Change=~alc3 
##         0.4055110         0.6091749</code></pre>
<p>Here, the baseline amount of change is set by comparing the first and last occasions. Again, if change were <em>perfectly</em> linear, we would expect the estimated loadings to increase by a constant amount, but we see a similar pattern as the first basis model above.</p>
<ul>
<li>There is a 0.4-unit increase in the loadings from <code>alc1</code> to <code>alc2</code></li>
<li>The increase in loadings from <code>alc2</code> to <code>alc3</code> is about half that (0.2 units)</li>
<li>Then the loadings increase from <code>alc3</code> to <code>alc4</code> by about as much as the increase between the first 2 occasions</li>
</ul>
<p>This basis model is statistically equivalent to the first basis model, so they yield identical model fit with <em>proportionally</em> equivalent estimated loadings. Likewise, the estimated latent mean is proportionally higher because it reflects the average amount of change between Years 1 and 4.</p>
<p>A latent basis model is flexible in terms of the factor loadings, which are somewhat easy to interpret. However, there is a “hidden” <em>proportionality assumption</em> represented by estimating only a single latent variance for rate of change (<span class="math inline">\(\psi_{2,2}\)</span>; Wu &amp; Lang, 2016). Although some software (e.g., M<em>plus</em> and <code>OpenMx</code>) can be tricked into relaxing this assumption (McNeish, 2020), an alternative model (described next) can be even more useful for exploratory purposes.</p>
</div>
<div id="saturated-growth-model" class="section level3 hasAnchor" number="13.4.2">
<h3><span class="header-section-number">13.4.2</span> Saturated Growth Model<a href="latent-growth-curve-models.html#saturated-growth-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A saturated model fits perfectly by definition, although the perfect fit is arbitrary because all information from summary statistics was used to estimate parameters to reproduce those summary statistics (i.e., <span class="math inline">\(df=0\)</span>). However, because we are in hypothesis-generating <em>exploratory mode</em>, testing a hypothesis of fit is not necessarily a priority.</p>
<p>In this section, we show how to fit a saturated LGCM by using polynomial contrast codes to specify the loadings (Voelkle &amp; McKnight, 2012). In the GLM or MLM, polynomial contrast codes can be used to represent a predictor that is an ordinal grouping variable, which is often a continuous variable that is merely measured in discrete units. In our example, time is measured only in whole years, discounting differences in days or months.</p>
<ul>
<li><em>Note</em>: In fact, a limitation of wide-format approaches for longitudinal data (LGCM and repeated-measures ANOVA) is that time must be treated discretely. In long-format approaches (e.g., MLM), predictors like time can be represented continuously, capturing more detail about individual differences in measurement schedules, thus providing more information about true developmental trajectories.</li>
</ul>
<p>A polynomial is the power to which a variable is raised. For example, a linear effect is merely the first power (<span class="math inline">\(x^1=x\)</span>), but a quadratic effect is the second power (<span class="math inline">\(x^2\)</span>) and a cubic effect is the third power (<span class="math inline">\(x^3\)</span>), etc. Any number raised to the zero power is 1 (<span class="math inline">\(x^0=1\)</span>), which is the constant used to estimate the intercept. Thus, even linear models are a polynomial model, but only up to the first power. When we measure a variable on <span class="math inline">\(t=1, \dots, T\)</span> occasions, we can estimate up to the <span class="math inline">\(T-1\)</span> power, for the same reason that differences between <span class="math inline">\(g=1, \dots, G\)</span> groups can be represented by <span class="math inline">\(G-1\)</span> dummy codes. Our example has <span class="math inline">\(T=4\)</span> occasions, so we can estimate up to power 3; another way to think of it is that we <strong>do</strong> estimate <span class="math inline">\(T=4\)</span> polynomial effects, but we begin with 0 (the intercept) rather than 1 (the linear slope). Note that a saturated LGCM could simply use the same loadings for the latent intercept and linear slope, then a quadratic (and cubic) factor can have loadings that are the squared (and cubed) values of the linear-slope’s loadings; however, we can avoid possible (multi)collinearity of growth factors by specifying orthogonal contrast codes instead (Voelkle &amp; McKnight, 2012).</p>
<p>Polynomial contrast codes can be obtained in R using the <code>contr.poly()</code> function, whose first argument is the number of occasions (<span class="math inline">\(T=4\)</span>):</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="latent-growth-curve-models.html#cb313-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.poly</span>(<span class="dv">4</span>) <span class="co"># .L = linear, .Q = quadratic, .C = cubic</span></span></code></pre></div>
<pre><code>##              .L   .Q         .C
## [1,] -0.6708204  0.5 -0.2236068
## [2,] -0.2236068 -0.5  0.6708204
## [3,]  0.2236068 -0.5 -0.6708204
## [4,]  0.6708204  0.5  0.2236068</code></pre>
<p>If we have unequally spaced measurements (e.g., measured at ages 7, 9, 12, and 13), we can indicate this using the <code>scores=</code> argument: <code>contr.poly(4, scores = c(7, 9, 12, 13))</code>.</p>
<p>Rather than fixing loadings of the latent intercept to 1, we can specify a “<strong>center</strong>cept” (Wainer, 2000) as <span class="math inline">\(\frac{1}{\sqrt{T}}\)</span> (<span class="math inline">\(\frac{1}{2}\)</span>). The advantage of specifying the latent “level” (rather than initial status) in this way is that its variance (<span class="math inline">\(\psi_{1,1}\)</span>) captures individual differences in grand means, not merely individual differences at a particular occasion or in the middle of all occasions (Voelkle &amp; McKnight, 2012, p. 26).</p>
<p>Finally, because there is a growth factor for each occasion, the entire covariance structure can be reproduced in the latent space (factor (co)variances). Thus, we must fix indicators’ residual variances to zero, as depicted in Figure 4.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-73-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(4\)</span>. Saturated growth model for alcohol-use data from Duncan and Duncan (1996).</p>
<p>The script below specifies the model in Figure 4, fits the model, and prints the estimated latent means for interpretation.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="latent-growth-curve-models.html#cb315-1" aria-hidden="true" tabindex="-1"></a>mod.sat <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings</span></span>
<span id="cb315-2"><a href="latent-growth-curve-models.html#cb315-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Level  =~    .5*alc1 +    .5*alc2 +    .5*alc3 +   .5*alc4</span></span>
<span id="cb315-3"><a href="latent-growth-curve-models.html#cb315-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Linear =~ -.671*alc1 + -.224*alc2 +  .224*alc3 + .671*alc4</span></span>
<span id="cb315-4"><a href="latent-growth-curve-models.html#cb315-4" aria-hidden="true" tabindex="-1"></a><span class="st">    Quad   =~    .5*alc1 +   -.5*alc2 +   -.5*alc3 +   .5*alc4</span></span>
<span id="cb315-5"><a href="latent-growth-curve-models.html#cb315-5" aria-hidden="true" tabindex="-1"></a><span class="st">    Cubic  =~ -.224*alc1 +  .671*alc2 + -.671*alc3 + .224*alc4</span></span>
<span id="cb315-6"><a href="latent-growth-curve-models.html#cb315-6" aria-hidden="true" tabindex="-1"></a><span class="st">  ## residual variances</span></span>
<span id="cb315-7"><a href="latent-growth-curve-models.html#cb315-7" aria-hidden="true" tabindex="-1"></a><span class="st">    alc1 ~~ 0*alc1</span></span>
<span id="cb315-8"><a href="latent-growth-curve-models.html#cb315-8" aria-hidden="true" tabindex="-1"></a><span class="st">    alc2 ~~ 0*alc2</span></span>
<span id="cb315-9"><a href="latent-growth-curve-models.html#cb315-9" aria-hidden="true" tabindex="-1"></a><span class="st">    alc3 ~~ 0*alc3</span></span>
<span id="cb315-10"><a href="latent-growth-curve-models.html#cb315-10" aria-hidden="true" tabindex="-1"></a><span class="st">    alc4 ~~ 0*alc4</span></span>
<span id="cb315-11"><a href="latent-growth-curve-models.html#cb315-11" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb315-12"><a href="latent-growth-curve-models.html#cb315-12" aria-hidden="true" tabindex="-1"></a>fit.sat <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.sat, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb315-13"><a href="latent-growth-curve-models.html#cb315-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>,</span>
<span id="cb315-14"><a href="latent-growth-curve-models.html#cb315-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">auto.cov.lv.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb315-15"><a href="latent-growth-curve-models.html#cb315-15" aria-hidden="true" tabindex="-1"></a>PE.sat <span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(fit.sat, <span class="at">output =</span> <span class="st">&quot;pretty&quot;</span>)</span>
<span id="cb315-16"><a href="latent-growth-curve-models.html#cb315-16" aria-hidden="true" tabindex="-1"></a>PE.sat[PE.sat<span class="sc">$</span>op <span class="sc">==</span> <span class="st">&quot;~1&quot;</span>, ]</span></code></pre></div>
<pre><code>## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##     alc1              0.000                               0.000    0.000
##     alc2              0.000                               0.000    0.000
##     alc3              0.000                               0.000    0.000
##     alc4              0.000                               0.000    0.000
##     Level             5.245    0.088   59.649    0.000    5.073    5.417
##     Linear            0.495    0.040   12.386    0.000    0.417    0.574
##     Quad             -0.009    0.031   -0.287    0.774   -0.071    0.053
##     Cubic             0.065    0.030    2.216    0.027    0.008    0.123</code></pre>
<p>The latent quadratic trend is not significant, but the cubic one is. A quadratic curve (i.e., a parabola) can only change directions once (i.e., from increasing to decreasing, or from decreasing to increasing). A cubic curve can change directions twice (and a 4th-order curve can change direction 3 times, etc.). This result is consistent with what we observed with the latent basis model, when the increase was steeper, then less steep, then steeper again. Unfortunately, we have no way to test whether this developmental trajectory truly follows a cubic (3rd-order) trend using only <span class="math inline">\(3+1=4\)</span> occasions—recall that <span class="math inline">\(df=0\)</span>. If we were to generate a hypothesis about nonlinear change, it would need to be confirmed with new data gather from a design with more measurement occasions. But in this case, also recall that we could not reject the <span class="math inline">\(H_0\)</span> of linear change because the linear model does not fit significantly worse than a saturated model (such as the one above).</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="latent-growth-curve-models.html#cb317-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit.lin, <span class="fu">c</span>(<span class="st">&quot;chisq&quot;</span>,<span class="st">&quot;df&quot;</span>,<span class="st">&quot;pvalue&quot;</span>), <span class="at">output =</span> <span class="st">&quot;pretty&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Model Test User Model:
## 
##   Test statistic                                 8.174
##   Degrees of freedom                                 5
##   P-value                                        0.147</code></pre>
<p>Fixing both the quadratic and cubic factor means to zero would not lead to rejecting the <span class="math inline">\(H_0\)</span> (<span class="math inline">\(p=.08\)</span>), so this is a lesson in guarding against using multiple tests to conduct exploratory analyses. If you employ a saturated or latent-basis model, bear in mind that they are exploratory, and it is safer to interpret the informative parameters descriptively in order to generate (not test) new hypotheses derived from the data.</p>
<div id="alternative-contrast-codes" class="section level4 hasAnchor" number="13.4.2.1">
<h4><span class="header-section-number">13.4.2.1</span> Alternative Contrast Codes<a href="latent-growth-curve-models.html#alternative-contrast-codes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When estimating growth factors from intervention studies, linear growth might not be reasonable because we hypothesize means will change immediately after the intervention but not after. For example, in a pretest, posttest, follow-up design, our hypotheses might be:</p>
<ul>
<li><span class="math inline">\(H_1\)</span>: Parenting intervention will reduce parent–child conflicts</li>
<li><span class="math inline">\(H_2\)</span>: The effect will be stable after intervention</li>
</ul>
<p>The piecewise growth model we mentioned at the beginning of Section 4 would be appropriate in principle, but it would not be practical because there are only 3 occasions with a changepoint between the first 2 occasions (pretest and posttest).</p>
<p>Instead, we can simply apply a different set of contrast codes than the polynomials discussed above. Helmert contrast codes would be appropriate to test whether pretest scores differ from <strong>both</strong> posttest and follow-up scores (<span class="math inline">\(H_1\)</span>) and whether follow-up scores differ from initial posttest scores (<span class="math inline">\(H_2\)</span>). The factor loadings below would allow these hypotheses to be tested:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Intercept</th>
<th align="right">Pre.v.After</th>
<th align="right">Post.v.Follow</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Pretest</td>
<td align="right"><span class="math inline">\(\frac{1}{\sqrt{3}}\)</span></td>
<td align="right">-2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Posttest</td>
<td align="right"><span class="math inline">\(\frac{1}{\sqrt{3}}\)</span></td>
<td align="right">1</td>
<td align="right">-1</td>
</tr>
<tr class="odd">
<td align="left">Follow-up</td>
<td align="right"><span class="math inline">\(\frac{1}{\sqrt{3}}\)</span></td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>This “growth” trajectory would be saturated, but 3 occasions already does not allow for sufficient <em>df</em> to test strong hypotheses about fit (e.g., a quadratic factor would already make it saturated). But relevant and sensible hypotheses that follow from such a 3-occasion intervention study can be answered using these contrast codes.</p>
</div>
</div>
</div>
<div id="explaining-growth-factors" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> Explaining Growth Factors<a href="latent-growth-curve-models.html#explaining-growth-factors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Growth-factor variances represent individual differences in developmental trajectories. The literature often distinguishes two related concepts:</p>
<ul>
<li>Individual <strong>differences</strong> occur <em>between</em> subjects</li>
<li>Individual <strong>change</strong> occurs <em>within</em> a subject</li>
</ul>
<p>Thus, growth-curve models (in MLM or SEM) simultaneously model <strong>inter</strong>-individual differences in <strong>intra</strong>-individual change.</p>
<p>It is possible to estimate latent trajectories while statistically controlling for Level-1 covariates that only vary <em>within</em> subjects. These are often called <em>time-varying</em> predictors.</p>
<p>It is also possible to explain inter-individual differences in latent trajectories, using Level-2 predictors that only vary <em>between</em> subjects. These are often called <em>time-invariate</em> predictors.</p>
<p>Either type of predictor introduces moderation of (or by) time, which is not as familiar as moderation represented by interactions in regression models. Here, too, a comparison with MLM will facilitate interpretation of moderated effects in LGCMs using SEM. The fundamental principle to bear in mind is the basic meaning of moderation: the relationship between two variables is a function of a third variable. To this end, we briefly review statistical interaction in a regression model, wherein moderation is represented by a product between predictors.</p>
<p><span class="math display" id="eq:int">\[\begin{equation} \begin{split} \label{eq:int}
Y_i &amp;= \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \beta_3 X_{i1} X_{i2} + \varepsilon_i \\
    &amp;= (\beta_0 + \beta_1 X_{i1}) + (\beta_2 + \beta_3 X_{i1}) \times X_{i2} + \varepsilon_i \\
    &amp;= \vartheta_0 + \vartheta_1 X_{i2} + \varepsilon_i
\end{split}
\tag{13.1}
\end{equation}\]</span></p>
<p>By grouping the terms in the second row of Eq. @ref{eq:int}, we can reinterpret it as a simple regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X_2\)</span> (the third row of Eq. @ref{eq:int}). But the intercept and slope are themselves variables because they depend on (are functions of) <span class="math inline">\(X_1\)</span>.</p>
<ul>
<li>Simple intercepts: <span class="math inline">\(\vartheta_0 = \beta_0 + \beta_1 X_{i1}\)</span></li>
<li>Simple slopes: <span class="math inline">\(\vartheta_1 = \beta_2 + \beta_3 X_{i1}\)</span></li>
</ul>
<p>Recall the moderation is symmetric, so the terms in Eq. @ref{eq:int} could also be grouped such that the effect of <span class="math inline">\(X_1\)</span> depends on <span class="math inline">\(X_2\)</span>. Moderation can also be interpreted in both directions in a LGCM, but it is not as obvious how because time is not an explicit variable in the model, as other predictors are.</p>
<p>Before proceeding, consider that growth factors are variables in a SEM. They can therefore be predictors as well as outcomes, even in the same model. Growth factors have already been treated as predictors of occasion-specific indicators in the sections above, but they could also predict subject-level outcome variables (e.g., to investigate whether the rate of increased alcohol consumption predictors a student’s academic performance). The following sections only elaborate on predictors of growth factors and correlations among latent trajectories, but bear in mind that more complex models are possible.</p>
<div id="time-invariant-level-2-predictors" class="section level3 hasAnchor" number="13.5.1">
<h3><span class="header-section-number">13.5.1</span> Time-Invariant (Level-2) Predictors<a href="latent-growth-curve-models.html#time-invariant-level-2-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Level-2 predictors vary between subjects, so they can explain between-subject differences in trajectories, which are represented by growth factors. Although Duncan and Duncan (1996) had several such covariates, our example data include the following two subject-level predictors: <code>age</code> at the beginning of the study and <code>peer</code> encouragement to consume illicit substances. Consider the MLM for growth, which extends Eq. <span class="math inline">\(\ref{eq:ri}\)</span> by adding time as a predictor. Below, we intersperse some equivalent SEM symbols as reminders of how the MLM and SEM frameworks map onto each other (Bauer, 2003; Curran, 2003; Singer &amp; Willett, 2003, ch. 8).</p>
<p><span class="math display" id="eq:L1">\[\begin{equation}
\text{Level 1: } y_{i,t} &amp;= \beta_{i,0} + \beta_{i,1} \text{Time}_{i,t} + \varepsilon_{i,t} = \textcolor{blue}{\Lambda \mathbf{\eta}_i + \varepsilon_i}
\tag{13.2}
\end{equation}\]</span>
<span class="math display" id="eq:L2">\[\begin{equation}
  \text{Level 2: } \beta_{i,0} &amp;= \textcolor{blue}{(\eta_0=)} \gamma_{0,0} + \gamma_{0,1} \text{Age}_i + \gamma_{0,2} \text{Peer-Influence}_i + u_{0,i} \label{eq:L2int+pred} \\
  \beta_{i,1} &amp;= \textcolor{blue}{(\eta_1=)} \gamma_{1,0} + \gamma_{1,1} \text{Age}_i + \gamma_{1,2} \text{Peer-Influence}_i + u_{1,i}
\tag{13.3}
\end{equation}\]</span>
<span class="math display" id="eq:Combined">\[\begin{equation}
\text{Combined: } y_{i,t} &amp;= \gamma_{0,0} + \gamma_{0,1} \text{Age}_i + \gamma_{0,2} \text{Peer-Influence}_i + \gamma_{1,0} \text{Time}_{i,t} \label{eq:L2main} \\
  &amp;+ \gamma_{1,1} (\text{Age}_i \times \text{Time}_{i,t}) + \gamma_{1,2} (\text{Peer-Influence}_i \times \text{Time}_{i,t}) \label{eq:L2ints} \\
  &amp;+ u_{0,i} + u_{1,i} \text{Time}_{i,t} + \varepsilon_{i,t} \ \ \textcolor{gray}{\text{(joint residual)}}
\tag{13.4}
\end{equation}\]</span></p>
<p>The path diagram below depicts age and peer influence as observed variables that predict growth factors, conforming to how <code>?lavaan::model.syntax</code> works. In the background, <code>lavaan</code> internally represents observed predictors as single-indicator factors. Thus, age and peer influence are assigned <span class="math inline">\(\eta_3\)</span> and <span class="math inline">\(\eta_4\)</span>, respectively, in the path diagram below.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-75-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(5\)</span>. Linear growth model for alcohol-use data from Duncan and Duncan (1996) with subject-level predictors of growth factors.</p>
<p>The LGCM script below specifies a measurement model for the growth factors (Eq. <span class="math inline">\(\ref{eq:L1}\)</span>) and a structural model that includes both predictors of initial status (Eq. <span class="math inline">\(\ref{eq:L2int+pred}\)</span>) and rate of change (Eq. <span class="math inline">\(\ref{eq:L2slope+pred}\)</span>). We will consider the combined model in Eqs. <span class="math inline">\(\ref{eq:L2main}\)</span>–<span class="math inline">\(\ref{eq:L2res}\)</span> further when we interpret the structural model.</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="latent-growth-curve-models.html#cb319-1" aria-hidden="true" tabindex="-1"></a>mod.pred2 <span class="ot">&lt;-</span> <span class="st">&#39; ##### MEASUREMENT MODEL</span></span>
<span id="cb319-2"><a href="latent-growth-curve-models.html#cb319-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4</span></span>
<span id="cb319-3"><a href="latent-growth-curve-models.html#cb319-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~          1*alc2 + 2*alc3 + 3*alc4</span></span>
<span id="cb319-4"><a href="latent-growth-curve-models.html#cb319-4" aria-hidden="true" tabindex="-1"></a><span class="st">##### STRUCTURAL MODEL</span></span>
<span id="cb319-5"><a href="latent-growth-curve-models.html#cb319-5" aria-hidden="true" tabindex="-1"></a><span class="st">  ## Level-2 predictors of growth trajectories</span></span>
<span id="cb319-6"><a href="latent-growth-curve-models.html#cb319-6" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status + Rate.Change ~ age + peer</span></span>
<span id="cb319-7"><a href="latent-growth-curve-models.html#cb319-7" aria-hidden="true" tabindex="-1"></a><span class="st">  ## factor (residual) covariance</span></span>
<span id="cb319-8"><a href="latent-growth-curve-models.html#cb319-8" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Rate.Change</span></span>
<span id="cb319-9"><a href="latent-growth-curve-models.html#cb319-9" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb319-10"><a href="latent-growth-curve-models.html#cb319-10" aria-hidden="true" tabindex="-1"></a>fit.pred2 <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.pred2, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb319-11"><a href="latent-growth-curve-models.html#cb319-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb319-12"><a href="latent-growth-curve-models.html#cb319-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.pred2, <span class="at">std =</span> <span class="cn">TRUE</span>, <span class="at">rsq =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-11 ended normally after 43 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        13
##                                                       
##   Number of observations                           321
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                23.607
##   Degrees of freedom                                 9
##   P-value (Chi-square)                           0.005
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status =~                                                        
##     alc1              1.000                               0.841    0.832
##     alc2              1.000                               0.841    0.887
##     alc3              1.000                               0.841    0.936
##     alc4              1.000                               0.841    0.902
##   Rate.Change =~                                                        
##     alc2              1.000                               0.203    0.214
##     alc3              2.000                               0.406    0.452
##     alc4              3.000                               0.609    0.653
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status ~                                                         
##     age               0.269    0.031    8.579    0.000    0.320    0.476
##     peer              0.086    0.016    5.455    0.000    0.102    0.303
##   Rate.Change ~                                                         
##     age              -0.033    0.012   -2.700    0.007   -0.163   -0.243
##     peer             -0.008    0.006   -1.227    0.220   -0.037   -0.110
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##  .Init.Status ~~                                                        
##    .Rate.Change      -0.054    0.020   -2.741    0.006   -0.424   -0.424
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.000                               0.000    0.000
##    .alc2              0.000                               0.000    0.000
##    .alc3              0.000                               0.000    0.000
##    .alc4              0.000                               0.000    0.000
##    .Init.Status      -1.774    0.399   -4.447    0.000   -2.108   -2.108
##    .Rate.Change       0.703    0.156    4.505    0.000    3.462    3.462
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.315    0.047    6.645    0.000    0.315    0.308
##    .alc2              0.320    0.033    9.834    0.000    0.320    0.356
##    .alc3              0.275    0.029    9.373    0.000    0.275    0.341
##    .alc4              0.301    0.045    6.634    0.000    0.301    0.346
##    .Init.Status       0.427    0.056    7.587    0.000    0.603    0.603
##    .Rate.Change       0.038    0.010    3.740    0.000    0.914    0.914
## 
## R-Square:
##                    Estimate
##     alc1              0.692
##     alc2              0.644
##     alc3              0.659
##     alc4              0.654
##     Init.Status       0.397
##     Rate.Change       0.086</code></pre>
<p>Although we can reject the omnibus <span class="math inline">\(H_0\)</span> of perfect data–model correspondence, <span class="math inline">\(\chi^2(9)=23.607, p=.005\)</span>, inspection of standardized residuals (<code>lavResiduals(fit.pred2)</code> output not shown) suggests the misfit is merely the accumulation of several minor discrepancies between observed and expected summary statistics. So we will proceed to interpret the model parameters.</p>
<ul>
<li><em>Note</em>: If one were interested in interpreting an incremental fit index (e.g., CFI) for this model, the custom null model in Section 3.1 must be appended by including the Level-2 predictors, whose means and variances are also estimated. But because they are exogenous covariates, the null model should also estimate the <code>age~~peer</code> covariance.</li>
</ul>
<p>The estimated intercept for the initial-status factor is <span class="math inline">\(\alpha_0=-1.774\)</span>, which is the expected alcohol use when all predictors (<code>age</code>, <code>peer</code>, <em>and Time</em>) are 0. In this case, it is an extrapolation beyond the data because no subjects began the study at birth, and peer-influence was measured on a 1–5 scale.</p>
<div id="simple-effects" class="section level4 hasAnchor" number="13.5.1.1">
<h4><span class="header-section-number">13.5.1.1</span> Simple Effects<a href="latent-growth-curve-models.html#simple-effects" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are 3 predictors with simple effects in Eq. <span class="math inline">\(\ref{eq:L2main}\)</span>: <code>age</code>, <code>peer</code>, and Time. But their effects are not represented in the same way in a LGCM. First, we focus on the effects of time-invariant predictors.</p>
<p>Both effects of Level-2 predictors on initial status were significant (<span class="math inline">\(p&lt;.001, R^2=39.7\%\)</span>), indicating that when the study began, adolescents who were older and whose best friends more strongly encouraged illicit-substance use exhibited more frequent alcohol consumption. Standardized slopes indicator both effects were medium, but unstandardized slopes are interpretable in the given units. Specifically, each year older increases their expected initial alcohol consumption by <span class="math inline">\(\gamma_{0,1}=0.269\)</span> units, for a given level of peer influence. And at a given age, one (Likert-scale) unit higher peer influence increases their expected initial alcohol consumption by <span class="math inline">\(\gamma_{0,2}=0.086\)</span> units.</p>
<p>The simple effects of <code>age</code> and <code>peer</code> are conditional on Time = 0 (the beginning of the study), but we might be interested in probing their effects at other occasions. To obtain simple effects of time-invariant predictors conditional on other occasions, simply change the reference occasion in <span class="math inline">\(\mathbf{\Lambda}\)</span> and fit the (statistically equivalent) model. For example, we could set the rate-of-change factor loadings to <span class="math inline">\(\lambda_{2,.}=-1, 0, 1, 2\)</span>, which would make the latent intercept interpreted as the level at the second occasion. Thus, the simple effects of <code>age</code> and <code>peer</code> would be conditional on Time = 1 year after the study began.</p>
<p>The simple effect of Time, on the other hand, is not an explicit regression slope in a LGCM. Instead, it is a latent variable: the rate-of-change factor. The simple effect of Time, therefore, is the estimated intercept (<span class="math inline">\(\alpha_1=0.703\)</span>) of the rate-of-change factor (i.e., the average rate of change, conditional on <code>age</code> = 0 and <code>peer</code> = 0). As with the estimated initial-status intercept, this is an extrapolation beyond the data. If one were interested in interpreting simple slopes of Time for particular (observed) values of <code>age</code> and <code>peer</code>, one could center <code>age</code> and <code>peer</code> at those values and fit the statistically equivalent model.</p>
</div>
<div id="moderation-effects" class="section level4 hasAnchor" number="13.5.1.2">
<h4><span class="header-section-number">13.5.1.2</span> Moderation Effects<a href="latent-growth-curve-models.html#moderation-effects" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The interactions in Eq. <span class="math inline">\(\ref{eq:L2ints}\)</span> are represented by the predictors’ effects on the rate-of-change factor, which explained <span class="math inline">\(R^2=8.6\%\)</span> of between-subjects variance in growth trajectories. That is, the effect of Time depends on both <code>age</code> and <code>peer</code>. The form of the model facilitates describing the nature of this interaction when Time is the focal predictor. At a given level of peer influence, one year older <strong>decreases the effect of Time on alcohol consumption</strong> by <span class="math inline">\(\gamma_{1,1}=-0.033\)</span> units/year. The effect of peer influence (given age) was not significant, implying no evidence moderation of Time’s effect by peer influence.</p>
<p>We did not estimate an <code>age</code> <span class="math inline">\(\times\)</span> <code>peer</code> interaction, so the LGCM also did not estimate a 3-way interaction. This is not possible in our example because doing so would require raw data to calculate the product term and include it as an additional predictor of growth factors. The 3-way interaction would be represented by the <code>age</code> <span class="math inline">\(\times\)</span> <code>peer</code> product term’s effect on the rate-of-change factor, while the product’s (simple) 2-way interaction would be represented by its effect on the initial-status factor.</p>
</div>
</div>
<div id="time-varying-level-1-predictors" class="section level3 hasAnchor" number="13.5.2">
<h3><span class="header-section-number">13.5.2</span> Time-Varying (Level-1) Predictors<a href="latent-growth-curve-models.html#time-varying-level-1-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Level-1 predictors vary within subjects, as does Time. Thus, we can estimate the effect of Time while <em>statistically controlling for</em> time-varying predictors. Our example data includes annual <code>cig</code>arette use, which would be included in the Level-1 component of a MLM for growth.</p>
<p><span class="math display">\[\begin{equation} \label{eq:L1pred}
\text{AlcUse}_{i,t} = \beta_{i,0} + \beta_{i,1} \text{Time}_{i,t} + \beta_2 \text{CigUse}_{i,t} + \beta_3 (\text{Time}_{i,t} \times \text{CigUse}_{i,t}) + \varepsilon_{i,t}
\end{equation}\]</span></p>
<p>Notice that Eq. <span class="math inline">\(\ref{eq:L1pred}\)</span> only includes a fixed (not random) effect of cigarette use. The possibility of including a random effect for both Time and cigarette use is one of the ways in which MLM is more flexible than SEM. Notice also that Eq. <span class="math inline">\(\ref{eq:L1pred}\)</span> includes a Time <span class="math inline">\(\times\)</span> cigarette-use interaction effect (<span class="math inline">\(\beta_3\)</span>). This is how moderation is represented in a regression model, but moderation of Time by a Level-1 variable in LGCM is quite different, involving more than one parameter.</p>
<p>The path diagram below depicts both alcohol and cigarette use as observed variables, with the latter predicting the former. However, <code>lavaan</code>’s internal LISREL representation does not have a parameter matrix for regressions among observed variables (M<em>plus</em> does, and the RAM representation used by the <code>OpenMx</code> package only has a single matrix with all slopes among observed and latent variables). So internally, <code>lavaan</code> “promotes” alcohol and cigarette use variables to latent variables corresponding to their single indicators. However, to keep the path diagram readable, this is overlooked and the slopes are labeled simply as <span class="math inline">\(\beta\)</span>s.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-77-1.svg" width="672" /></p>
<p><em>Figure</em> <span class="math inline">\(6\)</span>. Linear growth model for alcohol-use data from Duncan and Duncan (1996), controlling for cigarette-use data.</p>
<p>The LGCM script below specifies a measurement model for the growth factors, but also regresses each indicator on the level-1 covariate at the same occasion. The latter parameters are labeled so that we can apply equality <code>constraints=</code> in the <code>lavaan()</code> call, to exclude moderation between Time and cigarette use.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="latent-growth-curve-models.html#cb321-1" aria-hidden="true" tabindex="-1"></a>mod.pred1 <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings</span></span>
<span id="cb321-2"><a href="latent-growth-curve-models.html#cb321-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4</span></span>
<span id="cb321-3"><a href="latent-growth-curve-models.html#cb321-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~          1*alc2 + 2*alc3 + 3*alc4</span></span>
<span id="cb321-4"><a href="latent-growth-curve-models.html#cb321-4" aria-hidden="true" tabindex="-1"></a><span class="st">  ## factor covariance</span></span>
<span id="cb321-5"><a href="latent-growth-curve-models.html#cb321-5" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Rate.Change</span></span>
<span id="cb321-6"><a href="latent-growth-curve-models.html#cb321-6" aria-hidden="true" tabindex="-1"></a><span class="st">  ## Level-1 covariates</span></span>
<span id="cb321-7"><a href="latent-growth-curve-models.html#cb321-7" aria-hidden="true" tabindex="-1"></a><span class="st">    alc1 ~ b1*cig1</span></span>
<span id="cb321-8"><a href="latent-growth-curve-models.html#cb321-8" aria-hidden="true" tabindex="-1"></a><span class="st">    alc2 ~ b2*cig2</span></span>
<span id="cb321-9"><a href="latent-growth-curve-models.html#cb321-9" aria-hidden="true" tabindex="-1"></a><span class="st">    alc3 ~ b3*cig3</span></span>
<span id="cb321-10"><a href="latent-growth-curve-models.html#cb321-10" aria-hidden="true" tabindex="-1"></a><span class="st">    alc4 ~ b4*cig4</span></span>
<span id="cb321-11"><a href="latent-growth-curve-models.html#cb321-11" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb321-12"><a href="latent-growth-curve-models.html#cb321-12" aria-hidden="true" tabindex="-1"></a>fit.pred1 <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.pred1, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb321-13"><a href="latent-growth-curve-models.html#cb321-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>,</span>
<span id="cb321-14"><a href="latent-growth-curve-models.html#cb321-14" aria-hidden="true" tabindex="-1"></a>                    <span class="do">## constrain cigarette-use&#39;s effect to equality over time</span></span>
<span id="cb321-15"><a href="latent-growth-curve-models.html#cb321-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">constraints =</span> <span class="fu">c</span>(<span class="st">&quot;b1 == b2&quot;</span>, <span class="st">&quot;b1 == b3&quot;</span>, <span class="st">&quot;b1 == b4&quot;</span>))</span>
<span id="cb321-16"><a href="latent-growth-curve-models.html#cb321-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.pred1, <span class="at">std =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-11 ended normally after 28 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        13
##   Number of equality constraints                     3
##                                                       
##   Number of observations                           321
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                86.677
##   Degrees of freedom                                20
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status =~                                                        
##     alc1              1.000                               0.679    0.725
##     alc2              1.000                               0.679    0.753
##     alc3              1.000                               0.679    0.764
##     alc4              1.000                               0.679    0.752
##   Rate.Change =~                                                        
##     alc2              1.000                               0.185    0.205
##     alc3              2.000                               0.370    0.416
##     alc4              3.000                               0.555    0.615
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   alc1 ~                                                                
##     cig1      (b1)    0.260    0.023   11.490    0.000    0.260    0.316
##   alc2 ~                                                                
##     cig2      (b2)    0.260    0.023   11.490    0.000    0.260    0.356
##   alc3 ~                                                                
##     cig3      (b3)    0.260    0.023   11.490    0.000    0.260    0.374
##   alc4 ~                                                                
##     cig4      (b4)    0.260    0.023   11.490    0.000    0.260    0.394
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Status ~~                                                        
##     Rate.Change      -0.058    0.020   -2.927    0.003   -0.460   -0.460
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.000                               0.000    0.000
##    .alc2              0.000                               0.000    0.000
##    .alc3              0.000                               0.000    0.000
##    .alc4              0.000                               0.000    0.000
##     Init.Status       1.814    0.062   29.228    0.000    2.671    2.671
##     Rate.Change       0.165    0.018    9.286    0.000    0.893    0.893
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .alc1              0.328    0.049    6.687    0.000    0.328    0.374
##    .alc2              0.330    0.034    9.789    0.000    0.330    0.406
##    .alc3              0.312    0.032    9.800    0.000    0.312    0.396
##    .alc4              0.266    0.044    6.107    0.000    0.266    0.326
##     Init.Status       0.462    0.059    7.769    0.000    1.000    1.000
##     Rate.Change       0.034    0.010    3.462    0.001    1.000    1.000
## 
## Constraints:
##                                                |Slack|
##     b1 - (b2)                                    0.000
##     b1 - (b3)                                    0.000
##     b1 - (b4)                                    0.000</code></pre>
<p>We reject the <span class="math inline">\(H_0\)</span> of perfect model fit, <span class="math inline">\(\chi^2(20)=86.677, p&lt;.001\)</span>, and there are many large standardized residuals (<code>lavResiduals(fit.pred1)</code> output not shown). This is not surprising given how constrained this model is. Cigarette-use is not only constrained to have a constant effect across time, but the effects only occur within an occasion. There are many theoretically motivated reasons to improve the model—for example, one might expect that smoking leads to <em>later</em> alcohol consumption. We could add lagged effects (e.g., <code>alc2 ~ cig1</code>) to improve model fit, which combines features of cross-lagged panel models and LGCMs. In fact, there have also been attempts to merge autoregressive and latent-growth models (e.g., the autoregressive latent-trajectory (ALT) model; Bollen &amp; Curran, 2004).</p>
<p>We will not explore these complexities here, but we will briefly discuss the importance of the equality-constrained slopes on the interpretation of Time’s average effect (i.e., the rate-of-change mean). The script below releases the constraints, which significantly improves model fit.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="latent-growth-curve-models.html#cb323-1" aria-hidden="true" tabindex="-1"></a>fit.tc <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.pred1, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb323-2"><a href="latent-growth-curve-models.html#cb323-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb323-3"><a href="latent-growth-curve-models.html#cb323-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit.pred1, fit.tc)</span></code></pre></div>
<pre><code>## Chi-Squared Difference Test
## 
##           Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)    
## fit.tc    17 2844.7 2893.7 67.036                                  
## fit.pred1 20 2858.3 2896.1 86.677      19.64       3  0.0002015 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The effect of cigarette use now decreases as time goes on, and the decrease is not linear as it is in Eq. <span class="math inline">\(\ref{eq:L1pred}\)</span> because the LGCM can add 3 parameters to account for moderation more flexibly than only <span class="math inline">\(\beta_3\)</span>. Because the effect of cigarette use now depends on Time, the estimated rate-of-change mean is only a simple slope for Time conditional on CigUse = 0 (again, an extrapolation beyond the bounds of this 1–5 scale). Probing the effect of time at different levels of cigarette use is simple enough: simply center the moderator (all 4 <code>cig</code> variables) at the same theoretically interesting value (e.g., 1, 3, and 5), which changes the interpretation of each AlcUse intercept to the expected value at that level of CigUse.</p>
<pre><code>## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   alc1 ~                                                                
##     cig1      (b1)    0.364    0.035   10.281    0.000    0.364    0.434
##   alc2 ~                                                                
##     cig2      (b2)    0.308    0.027   11.415    0.000    0.308    0.415
##   alc3 ~                                                                
##     cig3      (b3)    0.221    0.025    8.738    0.000    0.221    0.326
##   alc4 ~                                                                
##     cig4      (b4)    0.213    0.028    7.687    0.000    0.213    0.327
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     Init.Status       1.626    0.078   20.852    0.000    2.500    2.500
##     Rate.Change       0.276    0.034    8.171    0.000    1.573    1.573</code></pre>
<p>How does one recenter variables without raw data? Well, the first step of calculating a (co)variance is to subtract the mean, so the covariance matrix does not change. And we know exactly how recentering the variables would affect the mean vector: simply subtract the same value from each mean that would have been subtracted from the variable itself. For example, let’s probe the simple effect of Time when CigUse is in the middle of the scale (3).</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="latent-growth-curve-models.html#cb326-1" aria-hidden="true" tabindex="-1"></a>duncM3 <span class="ot">&lt;-</span> duncanM <span class="co"># copy, then center cig1-cig4</span></span>
<span id="cb326-2"><a href="latent-growth-curve-models.html#cb326-2" aria-hidden="true" tabindex="-1"></a>duncM3[<span class="fu">paste0</span>(<span class="st">&quot;cig&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)] <span class="ot">&lt;-</span> duncM3[<span class="fu">paste0</span>(<span class="st">&quot;cig&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)] <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb326-3"><a href="latent-growth-curve-models.html#cb326-3" aria-hidden="true" tabindex="-1"></a>fit.tc3 <span class="ot">&lt;-</span> <span class="fu">update</span>(fit.tc, <span class="at">sample.mean =</span> duncM3) <span class="co"># refit model with centered means</span></span></code></pre></div>
<pre><code>## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   alc1 ~                                                                
##     cig1      (b1)    0.382    0.035   10.911    0.000    0.382    0.453
##   alc2 ~                                                                
##     cig2      (b2)    0.266    0.030    8.766    0.000    0.266    0.367
##   alc3 ~                                                                
##     cig3      (b3)    0.220    0.029    7.660    0.000    0.220    0.324
##   alc4 ~                                                                
##     cig4      (b4)    0.242    0.030    8.133    0.000    0.242    0.368
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     Init.Status       2.693    0.058   46.438    0.000    4.096    4.096
##     Rate.Change       0.118    0.021    5.551    0.000    0.650    0.650</code></pre>
<p>Note that this model is <strong>not statistically equivalent</strong> to the model fitted to uncentered data. The rate-of-change factor loadings constrain the trajectory to be linear, and <code>fit.tc</code> imposes that linearity constraint <em>on different intercepts</em> than <code>fit.tc3</code> does. The average rate of change when CigUse = 3 is <span class="math inline">\(\alpha_1=0.118\)</span>.</p>
</div>
<div id="parallel-growth-curves" class="section level3 hasAnchor" number="13.5.3">
<h3><span class="header-section-number">13.5.3</span> Parallel Growth Curves<a href="latent-growth-curve-models.html#parallel-growth-curves" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In LGCM, time-varying covariates must be measured in parallel with the outcome itself (i.e., at all the same occasions). An alternative to controlling for them is to simultaneously model their own developmental trajectory. In such models, we can explore how the development of different variables relate to each other. The script below specifies linear growth factors for both alcohol and cigarette use.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="latent-growth-curve-models.html#cb328-1" aria-hidden="true" tabindex="-1"></a>mod.par <span class="ot">&lt;-</span> <span class="st">&#39; ## loadings for alcohol use</span></span>
<span id="cb328-2"><a href="latent-growth-curve-models.html#cb328-2" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Alc =~ 1*alc1 + 1*alc2 + 1*alc3 + 1*alc4</span></span>
<span id="cb328-3"><a href="latent-growth-curve-models.html#cb328-3" aria-hidden="true" tabindex="-1"></a><span class="st">    Lin.Alc  =~          1*alc2 + 2*alc3 + 3*alc4</span></span>
<span id="cb328-4"><a href="latent-growth-curve-models.html#cb328-4" aria-hidden="true" tabindex="-1"></a><span class="st">  ## loadings for cigarette use</span></span>
<span id="cb328-5"><a href="latent-growth-curve-models.html#cb328-5" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Cig =~ 1*cig1 + 1*cig2 + 1*cig3 + 1*cig4</span></span>
<span id="cb328-6"><a href="latent-growth-curve-models.html#cb328-6" aria-hidden="true" tabindex="-1"></a><span class="st">    Lin.Cig  =~          1*cig2 + 2*cig3 + 3*cig4</span></span>
<span id="cb328-7"><a href="latent-growth-curve-models.html#cb328-7" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb328-8"><a href="latent-growth-curve-models.html#cb328-8" aria-hidden="true" tabindex="-1"></a>fit.par <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.par, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb328-9"><a href="latent-growth-curve-models.html#cb328-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">int.lv.free =</span> <span class="cn">TRUE</span>, <span class="at">auto.var =</span> <span class="cn">TRUE</span>,</span>
<span id="cb328-10"><a href="latent-growth-curve-models.html#cb328-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">auto.cov.lv.x =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Init.Alc ~~                                                           
##     Lin.Alc          -0.095    0.023   -4.191    0.000   -0.511   -0.511
##     Init.Cig          0.627    0.071    8.850    0.000    0.662    0.662
##     Lin.Cig          -0.026    0.019   -1.375    0.169   -0.106   -0.106
##   Lin.Alc ~~                                                            
##     Init.Cig         -0.096    0.021   -4.508    0.000   -0.394   -0.394
##     Lin.Cig           0.029    0.006    4.477    0.000    0.463    0.463
##   Init.Cig ~~                                                           
##     Lin.Cig          -0.068    0.026   -2.584    0.010   -0.213   -0.213
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     Init.Alc          2.288    0.054   42.560    0.000    2.690    2.690
##     Lin.Alc           0.223    0.018   12.419    0.000    1.021    1.021
##     Init.Cig          1.842    0.064   28.773    0.000    1.651    1.651
##     Lin.Cig           0.210    0.019   10.793    0.000    0.733    0.733</code></pre>
<p>Results indicate increases in average use of both substances during adolescence. Both intercepts are negatively correlated with both slopes, indicating that those who used either illicit substance at the beginning of the study tended to increase the use of either substance at a higher rate (although initial cigarette use was not significantly correlated with increasing alcohol consumption). Latent intercepts were positively correlated, indicating that adolescents who used one substance more frequently at the beginning of the study tended to use the other more frequently as well. Latent slopes were also positively correlated, indicating that adolescents who increasingly used one substance tended to increasingly use the other.</p>
</div>
</div>
<div id="latent-indicators-of-growth-factors" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Latent Indicators of Growth Factors<a href="latent-growth-curve-models.html#latent-indicators-of-growth-factors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All the examples so far have used observed indicators of growth factors. When we want to estimate an LGCM for a latent variable, additional identification constraints are required, depending on the type of latent variable. Recall that latent variables have no intrinsic location (mean) or scale (variance) because they have not been directly measured. We give them arbitrary locations/scales simply to identify the model. Growth-factor means are identified because we fix all the indicator intercepts to zero; thus, indicator means are reproduced as functions of growth-factor means. Growth-factor variances are identified because we fix all the factor loadings; thus, (co)variances among indicators are reproduced as functions of growth-factor (co)variances and loadings.</p>
<p>We will discuss 2 commonly used types of latent growth indicator: a common factor (itself measured with multiple indicators) and a <em>latent response variable</em> (LRV) underlying a discrete (binary, ordinal) observation.</p>
<div id="common-factors" class="section level3 hasAnchor" number="13.6.1">
<h3><span class="header-section-number">13.6.1</span> Common Factors<a href="latent-growth-curve-models.html#common-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that a common factor can be identified by making it <em>z</em> scores—that is, we fix its <span class="math inline">\(\alpha_i=0\)</span> and <span class="math inline">\(\psi_{i,i}=1\)</span>. Other identification methods place constraints on measurement parameters (loadings and intercepts), but we will ignore those methods because they hide the identification issues that we discuss below.</p>
<p>After discussing LGCM with common-factor indicators (where LGCM is the structural model imposed on a CFA), we also briefly discuss another type of model in which the nested components are switched (a CFA to capture common varience in several parallel growth models).</p>
<div id="curve-of-factors" class="section level4 hasAnchor" number="13.6.1.1">
<h4><span class="header-section-number">13.6.1.1</span> Curve of Factors<a href="latent-growth-curve-models.html#curve-of-factors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>At first glance, common factors may seem like poor indicators of growth because all the means are fixed to zero; thus, the identification method makes it appear that no change can occur. However, recall that when a common factor is measured repeatedly with the same indicators, we can use a longitudinal CFA to evaluate equivalence/invariance of the measurement parameters across time. If scalar invariance constraints (equal loadings and intercepts) can be validly applied to at least a subset of repeatedly measured indicators, then the identification constraints (<span class="math inline">\(\alpha_i=0\)</span>, <span class="math inline">\(\psi_{i,i}=1\)</span>) would only be required on the first occasion. On subsequent occasions, latent means (and variances) would be estimable.</p>
<p>Thus, growth factors could be specified to reproduce the mean (and covariance) structure among the common factors. However, because the common-factor mean remains fixed to zero at the first occasion, it follows that the Initial-Status growth factor must have a mean of zero. In a LGCM, all growth-factor indicators have their intercepts fixed to zero, but with common-factor indicators, the first indicator’s latent intercept is already fixed to zero for identification, so there is no exchange of <em>df</em> to estimate the latent mean of Initial Status. Therefore, in a LGCM with common-factor indicators, the mean of Initial Status must be fixed to zero for identification.</p>
<p>The path diagram in Figure 7 illustrates a “curve of factors” model, in which growth factors explain growth among repeated measures of a common factor “substance use”. This common factor represents adolescents’ propensity for engaging in risk substance-use behaviors, indicated by their use of <code>alc</code>ohol, <code>cig</code>arettes, and cannabis (<code>thc</code>). The left panel of Figure 7 illustrates only one occasion’s measurement model, with longitudinal scalar-invariance constraints in place (i.e., the same <span class="math inline">\(\lambda\)</span>s and <span class="math inline">\(\nu\)</span>s are constant across occasions). The left panel also shows that each common-factor intercept is fixed to <span class="math inline">\(\alpha=0\)</span> because those means are structured by the (higher-order) LGCM. The gray arrow directed from the left to right panels indicates that this measurement model applies to each latent indicator of growth. The right panel depicts the (higher-order) LGCM itself. Because only one measurement model for substance use is depicted, Figure 7 is missing the residual covariances that should be estimated for each substance-use indicator across time (i.e., <code>alc1</code>’s residuals are correlated with <code>alc2</code>’s, <code>alc3</code>’s, and <code>alc4</code>’s residuals; same for cigarettes and cannabis).</p>
<p>In practice, measurement invariance should be tested first, as shown in Chapter 25. Although some authors have advocated testing longitudinal invariance with the LGCM in place (), we recommend using a CFA to test invariance because it places no restrictions on the latent mean or covariance structures. Any misfit due to invalid structural constraints (e.g., linear growth when true growth is nonlinear) would inflate Type I error rates for tests of invariance. Note also that if one identifies common factors by fixing a reference (or average) indicator’s loading to 1 and intercept to 0, common-factor means and variances would be freely estimated even without invariance constraints in place. However, the LGCM would not truly model change in a common factor, but rather change in the reference indicator. Measurement invariance is a prerequisite to drawing valid inferences about structural differences/changes in a construct.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-79-1.svg" width="672" /></p>
<p><em>Figure <span class="math inline">\(7\)</span></em>. Curve-of-factors model for substance-use data from Duncan and Duncan (1996).</p>
<p>The script below specifies the curve-of-factors model depicted in Figure 7.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="latent-growth-curve-models.html#cb330-1" aria-hidden="true" tabindex="-1"></a>mod.cof <span class="ot">&lt;-</span> <span class="st">&#39; ##### MEASUREMENT MODEL (3 indicators)</span></span>
<span id="cb330-2"><a href="latent-growth-curve-models.html#cb330-2" aria-hidden="true" tabindex="-1"></a><span class="st">  ## equal loadings across 4 occasions</span></span>
<span id="cb330-3"><a href="latent-growth-curve-models.html#cb330-3" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse1 =~ L1*alc1 + L2*cig1 + L3*thc1</span></span>
<span id="cb330-4"><a href="latent-growth-curve-models.html#cb330-4" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse2 =~ L1*alc2 + L2*cig2 + L3*thc2</span></span>
<span id="cb330-5"><a href="latent-growth-curve-models.html#cb330-5" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse3 =~ L1*alc3 + L2*cig3 + L3*thc3</span></span>
<span id="cb330-6"><a href="latent-growth-curve-models.html#cb330-6" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse4 =~ L1*alc4 + L2*cig4 + L3*thc4</span></span>
<span id="cb330-7"><a href="latent-growth-curve-models.html#cb330-7" aria-hidden="true" tabindex="-1"></a><span class="st">  ## equal intercepts across 4 occasions</span></span>
<span id="cb330-8"><a href="latent-growth-curve-models.html#cb330-8" aria-hidden="true" tabindex="-1"></a><span class="st">    alc1 + alc2 + alc3 + alc4 ~ nu1*1</span></span>
<span id="cb330-9"><a href="latent-growth-curve-models.html#cb330-9" aria-hidden="true" tabindex="-1"></a><span class="st">    cig1 + cig2 + cig3 + cig4 ~ nu2*1</span></span>
<span id="cb330-10"><a href="latent-growth-curve-models.html#cb330-10" aria-hidden="true" tabindex="-1"></a><span class="st">    thc1 + thc2 + thc3 + thc4 ~ nu3*1</span></span>
<span id="cb330-11"><a href="latent-growth-curve-models.html#cb330-11" aria-hidden="true" tabindex="-1"></a><span class="st">  ## residual (co)variances across 4 occasions</span></span>
<span id="cb330-12"><a href="latent-growth-curve-models.html#cb330-12" aria-hidden="true" tabindex="-1"></a><span class="st">    alc1 ~~ alc1 + alc2 + alc3 + alc4</span></span>
<span id="cb330-13"><a href="latent-growth-curve-models.html#cb330-13" aria-hidden="true" tabindex="-1"></a><span class="st">    alc2 ~~ alc2 + alc3 + alc4</span></span>
<span id="cb330-14"><a href="latent-growth-curve-models.html#cb330-14" aria-hidden="true" tabindex="-1"></a><span class="st">    alc3 ~~ alc3 + alc4</span></span>
<span id="cb330-15"><a href="latent-growth-curve-models.html#cb330-15" aria-hidden="true" tabindex="-1"></a><span class="st">    alc4 ~~ alc4</span></span>
<span id="cb330-16"><a href="latent-growth-curve-models.html#cb330-16" aria-hidden="true" tabindex="-1"></a><span class="st">    cig1 ~~ cig1 + cig2 + cig3 + cig4</span></span>
<span id="cb330-17"><a href="latent-growth-curve-models.html#cb330-17" aria-hidden="true" tabindex="-1"></a><span class="st">    cig2 ~~ cig2 + cig3 + cig4</span></span>
<span id="cb330-18"><a href="latent-growth-curve-models.html#cb330-18" aria-hidden="true" tabindex="-1"></a><span class="st">    cig3 ~~ cig3 + cig4</span></span>
<span id="cb330-19"><a href="latent-growth-curve-models.html#cb330-19" aria-hidden="true" tabindex="-1"></a><span class="st">    cig4 ~~ cig4</span></span>
<span id="cb330-20"><a href="latent-growth-curve-models.html#cb330-20" aria-hidden="true" tabindex="-1"></a><span class="st">    thc1 ~~ thc1 + thc2 + thc3 + thc4</span></span>
<span id="cb330-21"><a href="latent-growth-curve-models.html#cb330-21" aria-hidden="true" tabindex="-1"></a><span class="st">    thc2 ~~ thc2 + thc3 + thc4</span></span>
<span id="cb330-22"><a href="latent-growth-curve-models.html#cb330-22" aria-hidden="true" tabindex="-1"></a><span class="st">    thc3 ~~ thc3 + thc4</span></span>
<span id="cb330-23"><a href="latent-growth-curve-models.html#cb330-23" aria-hidden="true" tabindex="-1"></a><span class="st">    thc4 ~~ thc4</span></span>
<span id="cb330-24"><a href="latent-growth-curve-models.html#cb330-24" aria-hidden="true" tabindex="-1"></a><span class="st">## STRUCTURAL MODEL (higher-order LGCM)</span></span>
<span id="cb330-25"><a href="latent-growth-curve-models.html#cb330-25" aria-hidden="true" tabindex="-1"></a><span class="st">  ## loadings for growth factors</span></span>
<span id="cb330-26"><a href="latent-growth-curve-models.html#cb330-26" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status =~ 1*SubUse1 + 1*SubUse2 + 1*SubUse3 + 1*SubUse4</span></span>
<span id="cb330-27"><a href="latent-growth-curve-models.html#cb330-27" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change =~             1*SubUse2 + 2*SubUse3 + 3*SubUse4</span></span>
<span id="cb330-28"><a href="latent-growth-curve-models.html#cb330-28" aria-hidden="true" tabindex="-1"></a><span class="st">  ## growth-factor means and (co)variances</span></span>
<span id="cb330-29"><a href="latent-growth-curve-models.html#cb330-29" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~ 0*1  # fixed to 0 for identification</span></span>
<span id="cb330-30"><a href="latent-growth-curve-models.html#cb330-30" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change ~ 1</span></span>
<span id="cb330-31"><a href="latent-growth-curve-models.html#cb330-31" aria-hidden="true" tabindex="-1"></a><span class="st">  ## growth-factor means and (co)variances</span></span>
<span id="cb330-32"><a href="latent-growth-curve-models.html#cb330-32" aria-hidden="true" tabindex="-1"></a><span class="st">    Init.Status ~~ Init.Status + Rate.Change</span></span>
<span id="cb330-33"><a href="latent-growth-curve-models.html#cb330-33" aria-hidden="true" tabindex="-1"></a><span class="st">    Rate.Change ~~ Rate.Change</span></span>
<span id="cb330-34"><a href="latent-growth-curve-models.html#cb330-34" aria-hidden="true" tabindex="-1"></a><span class="st">  ## residual variances of growth indicators</span></span>
<span id="cb330-35"><a href="latent-growth-curve-models.html#cb330-35" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse1 ~~ psi1*SubUse1</span></span>
<span id="cb330-36"><a href="latent-growth-curve-models.html#cb330-36" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse2 ~~   NA*SubUse2</span></span>
<span id="cb330-37"><a href="latent-growth-curve-models.html#cb330-37" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse3 ~~   NA*SubUse3</span></span>
<span id="cb330-38"><a href="latent-growth-curve-models.html#cb330-38" aria-hidden="true" tabindex="-1"></a><span class="st">    SubUse4 ~~   NA*SubUse4</span></span>
<span id="cb330-39"><a href="latent-growth-curve-models.html#cb330-39" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb330-40"><a href="latent-growth-curve-models.html#cb330-40" aria-hidden="true" tabindex="-1"></a>fit.cof <span class="ot">&lt;-</span> <span class="fu">lavaan</span>(mod.cof, <span class="at">sample.cov =</span> duncanCOV, <span class="at">sample.mean =</span> duncanM,</span>
<span id="cb330-41"><a href="latent-growth-curve-models.html#cb330-41" aria-hidden="true" tabindex="-1"></a>                  <span class="do">## identify the model by constraining the first loading</span></span>
<span id="cb330-42"><a href="latent-growth-curve-models.html#cb330-42" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sample.nobs =</span> N, <span class="at">constraints =</span> <span class="st">&quot;L1 == 1&quot;</span>)</span>
<span id="cb330-43"><a href="latent-growth-curve-models.html#cb330-43" aria-hidden="true" tabindex="-1"></a><span class="do">## Alternatively, use effects-coding:      constraints = &quot;L1 == 3 - L2 - L3&quot;</span></span>
<span id="cb330-44"><a href="latent-growth-curve-models.html#cb330-44" aria-hidden="true" tabindex="-1"></a><span class="do">## or fix first factor&#39;s variance using:   std.lv = TRUE or constraints = &quot;psi1 == 1&quot;</span></span></code></pre></div>
<p>We do not present output because the conclusions are quite similar to the linear model for alcohol consumption in Section 3. The added benefit of this model is that we can see cigarette and cannabis use are stronger indicators (std. factor loadings approximately 0.8) of propensity for substance use than alcohol consumption (std. loadings 0.6–0.7). The benefit of modeling change in an error-free construct is only as valid as the CFA itself. The disadvantage of latent indicators is that each method of identification in the script above provides a different (arbitrary) scale on which to interpret the average rate of change. The standardized solution provides a scale-free estimate, but the units of <span class="math inline">\(SD\)</span> with which to interpret it are between-subject differences in rates of change, which is not necessarily a meaningful quantity to judge the size of the average rate of change.</p>
</div>
<div id="factor-of-curves" class="section level4 hasAnchor" number="13.6.1.2">
<h4><span class="header-section-number">13.6.1.2</span> Factor of Curves<a href="latent-growth-curve-models.html#factor-of-curves" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Although (individual differences in) growth trajectories might differ across substances, an individual’s trajectories might be correlated (e.g., an adolescent whose alcohol-consumption trajectory is higher than average might also increase their cigarette and cannabis use more than average). One might posit a common factor that explains why each substance’s initial statuses are correlated, and another common factor explaining when each substance’s rates of change are correlated. Duncan and Duncan (1996, pp. 335–338) discussing fitting a factor-of-curves model to their substance-use data, which involves several parameter constraints that are less than intuitive and open to criticism. The factor-of-curves model is rarely used in practice, and its plausibility is often tenuous, with limited benefits over interpreting the higher-order growth factors in a curve-of-factors model. Thus, we do not discuss or demonstrate the factor-of-curves model here.</p>
</div>
</div>
<div id="discrete-indicators" class="section level3 hasAnchor" number="13.6.2">
<h3><span class="header-section-number">13.6.2</span> Discrete Indicators<a href="latent-growth-curve-models.html#discrete-indicators" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Latent growth can be modeled for LRVs underlying discrete data, which means that the interpretations of growth factors will apply to the LRV locations and scales. As with common factors, the locations and scales are arbitrary, so regarding interpretation of the size of rate-of-change (for example), LGCMs for discrete data share the same drawbacks as curve-of-factors models. However, hypotheses about the functional form of growth (if any) can still be tested using latent indicators.</p>
<div id="binary-indicators" class="section level4 hasAnchor" number="13.6.2.1">
<h4><span class="header-section-number">13.6.2.1</span> Binary Indicators<a href="latent-growth-curve-models.html#binary-indicators" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As discussed in Chapter 12, binary outcomes have a single threshold (<span class="math inline">\(\tau\)</span>) to discretize a continuous/normal LRV (<span class="math inline">\(y^*\)</span>) into 2 categories:
<span class="math display">\[y = I(y^* &gt; \tau),\]</span>
where the indicator function <span class="math inline">\(I()\)</span> assigns 1 when its argument is <code>TRUE</code> and 0 when it is <code>FALSE</code>. The default behavior in <code>lavaan</code> is to identify the model by fixing each LRV’s intercept and variance to 0 and 1, respectively, enabling all thresholds to be estimated. However, it is statistically equivalent to fix a binary item’s threshold to zero and estimate its intercept. In fact, they will have the same absolute value but opposite sign.</p>
<p>Because indicator means are fixed to zero anyway (so they can be reproduced by growth factors via factor loadings), one could <em>hypothetically</em> fix thresholds for binary indicators to zero in <code>lavaan</code> syntax in order to fit a a LGCM to it (Newsom, 2015, p. 185). For example, if we had raw example data whose substance-use indicators were binary, we could update <em>any</em> of the scripts above by adding something like this to the model syntax:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="latent-growth-curve-models.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39; alc1 + alc2 + alc3 + alc4 | 0*t1&#39;</span></span></code></pre></div>
<p>However, there is no way to <em>link</em> the LRV scales across time because there is only one threshold, whose <em>df</em> is “traded” for the intercept (all of which are in turn traded for growth-factor means). Recall also from Chapter 12 that there are 2 common methods of identifying the LRV scale:</p>
<ul>
<li><code>parameterization = "delta"</code> (default) fixes the marginal/total variance of an LRV to 1</li>
<li><code>parameterization = "theta"</code> fixes an LRV’s residual variance to 1</li>
</ul>
<p>Either parameterization implies equality of variance across occasions, neither of which is likely to hold in practice. So even if the mean LRV remains the same over time, a change in variance will make it appear as though the mean does change because its distance from zero <strong>in units of <span class="math inline">\(SD\)</span></strong> changes. Thus, any true change in the mean is confounded with changes in variance, making it <strong>highly problematic</strong> to fit a LGCM to binary growth indicators.</p>
</div>
<div id="ordinal-indicators" class="section level4 hasAnchor" number="13.6.2.2">
<h4><span class="header-section-number">13.6.2.2</span> Ordinal Indicators<a href="latent-growth-curve-models.html#ordinal-indicators" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With more than 2 categories, we can trade 2 <em>df</em> (e.g., by fixing the first threshold to 0 and second threshold to 1) to estimate both the LRV intercept and variance. Recall from Chapter 12 that any ordinal variable with categories <span class="math inline">\(c=0, \ldots, C\)</span> can be interpreted as a crude discretization of an underlying LRV, whose <span class="math inline">\(C\)</span> thresholds divide the latent distribution into <span class="math inline">\(C+1\)</span> categories.</p>
<p><span class="math display">\[y=c \ \ \ \text{ if } \ \ \ \tau_c &lt; y^* \le \tau_{c+1}\]</span></p>
<p>Because the normal distribution is unbounded, the first category “starts” at <span class="math inline">\(\tau_0 = -\infty\)</span>, and the last category “ends” at <span class="math inline">\(\tau_{C+1} = +\infty\)</span>.</p>
<p>With only 3 categories, there is only enough information to trade the <span class="math inline">\(C=2\)</span> thresholds for the LRV intercept and variance, which is sufficient to link the response scales across occasions. So we can still only assume (not test) the assumption that thresholds do not change over time, but <em>threshold invariance</em> can be tested when items have <span class="math inline">\(\ge3\)</span> thresholds (Mehta et al., 2004). In our example data, substance use was measured with 5 categories, so each indicator would have <span class="math inline">\(C=4\)</span> thresholds, enabling us to test the assumption of threshold invariance (if we had access to the raw data). Chapter 27 will discuss threshold invariance in greater detail in the context of CFA with categorical indicators, but here it is sufficient to say that we can constrain thresholds across occasions in LGCM model syntax by using the same labels (below, <code>a</code>, <code>b</code>, <code>c</code>, and <code>d</code>) for equality-constrained parameters.</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="latent-growth-curve-models.html#cb332-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39; alc1 | a*t1 + b*t2 + c*t3 + d*t4</span></span>
<span id="cb332-2"><a href="latent-growth-curve-models.html#cb332-2" aria-hidden="true" tabindex="-1"></a><span class="st">  alc2 | a*t1 + b*t2 + c*t3 + d*t4</span></span>
<span id="cb332-3"><a href="latent-growth-curve-models.html#cb332-3" aria-hidden="true" tabindex="-1"></a><span class="st">  alc3 | a*t1 + b*t2 + c*t3 + d*t4</span></span>
<span id="cb332-4"><a href="latent-growth-curve-models.html#cb332-4" aria-hidden="true" tabindex="-1"></a><span class="st">  alc4 | a*t1 + b*t2 + c*t3 + d*t4 &#39;</span></span></code></pre></div>
<p>Intercepts remain constrained to zero (the default setting) so that the LRV means can be modeled by the growth-factor means and loadings. However, we must free the variances in the model syntax as well. Similar to invariance with common factors, the first occasion’s variance remains fixed to 1. Using the default <code>parameterization = "delta"</code>, we must free the marginal variances on subsequent occasions, which is controlled by the “latent scale” parameters, whose operator resembles how we specify a (co)variance that includes an asterisk to indicate it refers to the LRV <span class="math inline">\(y^*\)</span>.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="latent-growth-curve-models.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39; alc2 ~*~ NA*alc2</span></span>
<span id="cb333-2"><a href="latent-growth-curve-models.html#cb333-2" aria-hidden="true" tabindex="-1"></a><span class="st">  alc3 ~*~ NA*alc3</span></span>
<span id="cb333-3"><a href="latent-growth-curve-models.html#cb333-3" aria-hidden="true" tabindex="-1"></a><span class="st">  alc4 ~*~ NA*alc4 &#39;</span></span></code></pre></div>
<p>Using <code>parameterization = "theta"</code>, we must instead free the residual variances on subsequent occasions.</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="latent-growth-curve-models.html#cb334-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39; alc2 ~~ NA*alc2</span></span>
<span id="cb334-2"><a href="latent-growth-curve-models.html#cb334-2" aria-hidden="true" tabindex="-1"></a><span class="st">  alc3 ~~ NA*alc3</span></span>
<span id="cb334-3"><a href="latent-growth-curve-models.html#cb334-3" aria-hidden="true" tabindex="-1"></a><span class="st">  alc4 ~~ NA*alc4 &#39;</span></span></code></pre></div>
<p>The estimated growth trajectories will still differ across parameterizations because the latent scales will differ. However, the latent scales are now linked across occasions, so changes in the LRV intercepts are no longer confounded with changes in the LRV scale. So the estimated growth trajectories will be <em>proportionally equivalent</em> across parameterizations (i.e., the standardized solutions will be equivalent).</p>
</div>
</div>
</div>
<div id="multigroup-growth-models" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> Multigroup Growth Models<a href="latent-growth-curve-models.html#multigroup-growth-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Any of the models already discussed can be fitted simultaneously to multiple groups. Differences in parameters across groups represent moderation by the grouping variable. For example, if the latent mean of the Initial-Status factor differs across groups, that is the simple effect of Group at Time 0. Other simple effects of Time can be probed by choosing a different reference occasion, just as discussed with explicit predictors of growth factors in Section 5.1. Likewise, if the latent mean of the Rate-of-Change factor differs across groups, that is the moderation of Time’s effect by Group.</p>
<p>And if there is a predictor of growth factors, then the same principles from Section 5.1 can be extended to the grouping variable. Extending the example from Section 5.1, if the effect of Age on Initial Status (i.e., the simple effect of Age) differs across groups, that is an Age <span class="math inline">\(\times\)</span> Group interaction. And if the effect of Age on Rate of Change (i.e., the Age <span class="math inline">\(\times\)</span> Time interaction) differs across groups, that is an Age <span class="math inline">\(\times\)</span> Time <span class="math inline">\(\times\)</span> Group interaction.</p>
<p>When the growth-factor indicators are latent variables (see Section 6), comparisons across groups are only valid in the presence of invariance constraints. For common factors, scalar invariance must therefore be tested across both groups and occasions. For discrete indicators, thresholds must be invariant across both groups and occasions. For both types of latent indicator, identification constraints for the latent scale only need to be set on one Group–Time combination (typically the “first” group on the first occasion), while latent scales in all other groups/occasions can be freely estimated.</p>
</div>
<div id="references-8" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> References<a href="latent-growth-curve-models.html#references-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bauer, D. J. (2003). Estimating multilevel linear models as structural equation models. <em>Journal of Educational and Behavioral Statistics, 28</em>(2), 135–167. <a href="https://doi.org/10.3102/10769986028002135" class="uri">https://doi.org/10.3102/10769986028002135</a></p>
<p>Bollen, K. A., &amp; Curran, P. J. (2004). Autoregressive latent trajectory (ALT) models: A synthesis of two traditions. <em>Sociological Methods &amp; Research, 32</em>(3), 336–383. <a href="https://doi.org/10.1177/0049124103260222" class="uri">https://doi.org/10.1177/0049124103260222</a></p>
<p>Curran, P. J. (2003). Have multilevel models been structural equation models all along? <em>Multivariate Behavioral Research, 38</em>(4), 529–569. <a href="https://doi.org/10.1207/s15327906mbr3804_5" class="uri">https://doi.org/10.1207/s15327906mbr3804_5</a></p>
<p>Duncan, S. C., &amp; Duncan, T. E. (1996). A multivariate latent growth curve analysis of adolescent substance use. <em>Structural Equation Modeling, 3</em>(4), 323–347. <a href="https://doi.org/10.1080/10705519609540050" class="uri">https://doi.org/10.1080/10705519609540050</a></p>
<p>McNeish, D. (2020). Relaxing the proportionality assumption in latent basis models for nonlinear growth. (Structural Equation Modeling, 27)(5), 817–824. <a href="https://doi.org/10.1080/10705511.2019.1696201" class="uri">https://doi.org/10.1080/10705511.2019.1696201</a></p>
<p>Mehta, P. D., &amp; Neale, M. C. (2005). People are variables too: Multilevel structural equations modeling. <em>Psychological Methods, 10</em>(3), 259–284. <a href="https://doi.org/10.1037/1082-989X.10.3.259" class="uri">https://doi.org/10.1037/1082-989X.10.3.259</a></p>
<p>Mehta, P. D., Neale, M. C., &amp; Flay, B. R. (2004). Squeezing interval change from ordinal panel data: Latent growth curves with ordinal outcomes. <em>Psychological Methods, 9</em>(3), 301–333. <a href="https://doi.org/10.1037/1082-989X.9.3.301" class="uri">https://doi.org/10.1037/1082-989X.9.3.301</a></p>
<p>Newsom, J. T. (2015). <em>Longitudinal structural equation modeling: A comprehensive introduction</em>. Routledge.</p>
<p>Singer, J. D., &amp; Willett, J. B. (2003). <em>Applied longitudinal data analysis: Modeling change and event occurrence</em>. Oxford University Press. <a href="https://doi.org/10.1093/acprof:oso/9780195152968.001.0001" class="uri">https://doi.org/10.1093/acprof:oso/9780195152968.001.0001</a></p>
<p>Skrondal, A., &amp; Rabe-Hesketh, S. (2004). <em>Generalized latent variable modeling: Multilevel, longitudinal, and structural equation models</em>. Chapman and Hall/CRC. <a href="https://doi.org/10.1201/9780203489437" class="uri">https://doi.org/10.1201/9780203489437</a></p>
<p>Voelkle, M. C., &amp; McKnight, P. E. (2012). One size fits all? A Monte-Carlo simulation on the relationship between repeated measures (M)ANOVA and latent curve modeling. <em>Methodology, 8</em>(1), 23––38. <a href="https://doi.org/10.1027/1614-2241/a000044" class="uri">https://doi.org/10.1027/1614-2241/a000044</a></p>
<p>Wainer, H. (2000). The centercept: An estimable and meaningful
regression parameter. <em>Psychological Science, 11</em>(5), 434–436. <a href="https://doi.org/10.1111/1467-9280.00284" class="uri">https://doi.org/10.1111/1467-9280.00284</a></p>
<p>Widaman, K. F., &amp; Thompson, J. S. (2003). On specifying the null model for incremental fit indices in structural equation modeling. <em>Psychological Methods, 8</em>(1), 16–37. <a href="https://doi.org/10.1037/1082-989X.8.1.16" class="uri">https://doi.org/10.1037/1082-989X.8.1.16</a></p>
<p>Wu, W., &amp; Lang, K. M. (2016). Proportionality assumption in latent basis curve models: A cautionary note. <em>Structural Equation Modeling, 23</em>(1), 140–154. <a href="https://doi.org/10.1080/10705511.2014.938578" class="uri">https://doi.org/10.1080/10705511.2014.938578</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fitting-path-models-with-multilevel-data.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
