<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Path Models | Compendium Structural Equation Modeling in Educational Research</title>
  <meta name="description" content="3 Path Models | Compendium Structural Equation Modeling in Educational Research" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Path Models | Compendium Structural Equation Modeling in Educational Research" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="LJGroot/SEM-Compendium" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Path Models | Compendium Structural Equation Modeling in Educational Research" />
  
  
  

<meta name="author" content="Suzanne Jak and Terrence D. Jorgensen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="using-lavaan-to-run-regression-and-anova-as-a-sem.html"/>
<link rel="next" href="standard-errors-and-confidence-intervals.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html"><i class="fa fa-check"></i><b>1</b> Regression as Mean- and Covariance-Structure Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#installing-lavaan"><i class="fa fa-check"></i><b>1.1</b> Installing <code>lavaan</code></a></li>
<li class="chapter" data-level="1.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#types-of-data-used-in-sem"><i class="fa fa-check"></i><b>1.2</b> Types of Data Used in SEM</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#raw-data"><i class="fa fa-check"></i><b>1.2.1</b> Raw Data</a></li>
<li class="chapter" data-level="1.2.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#summary-statistics-from-raw-data"><i class="fa fa-check"></i><b>1.2.2</b> Summary Statistics from Raw Data</a></li>
<li class="chapter" data-level="1.2.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#importing-summary-data"><i class="fa fa-check"></i><b>1.2.3</b> Importing Summary Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#regression-review"><i class="fa fa-check"></i><b>1.3</b> Regression Review</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#linear-regression-models"><i class="fa fa-check"></i><b>1.3.1</b> Linear Regression Models</a></li>
<li class="chapter" data-level="1.3.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#matrix-notation"><i class="fa fa-check"></i><b>1.3.2</b> Matrix Notation</a></li>
<li class="chapter" data-level="1.3.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#interpreting-and-estimating-coefficients"><i class="fa fa-check"></i><b>1.3.3</b> Interpreting and Estimating Coefficients</a></li>
<li class="chapter" data-level="1.3.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#syntax-examples-with-raw-data"><i class="fa fa-check"></i><b>1.3.4</b> Syntax Examples with Raw Data</a></li>
<li class="chapter" data-level="1.3.5" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#categorical-predictors"><i class="fa fa-check"></i><b>1.3.5</b> Categorical Predictors</a></li>
<li class="chapter" data-level="1.3.6" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#constant-vs.-varying-slopes"><i class="fa fa-check"></i><b>1.3.6</b> Constant vs. Varying Slopes</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#summary-statistics"><i class="fa fa-check"></i><b>1.4</b> Summary Statistics</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#reimport-data"><i class="fa fa-check"></i><b>1.4.1</b> Reimport Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#raw-data-vs.-summary-statistics"><i class="fa fa-check"></i><b>1.4.2</b> Raw Data vs. Summary Statistics</a></li>
<li class="chapter" data-level="1.4.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#what-is-covariance"><i class="fa fa-check"></i><b>1.4.3</b> What Is Covariance?</a></li>
<li class="chapter" data-level="1.4.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#interpreting-covariance"><i class="fa fa-check"></i><b>1.4.4</b> Interpreting Covariance</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#covariance-matrix"><i class="fa fa-check"></i><b>1.5</b> Covariance Matrix</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#ols-with-summary-statistics-beta-mathbfx-mathbfx-1-mathbfx-mathbfy"><i class="fa fa-check"></i><b>1.5.1</b> OLS with Summary Statistics: <span class="math inline">\(\beta = (\mathbf{X}^{&#39;} \mathbf{X})^{-1} \mathbf{X}^{&#39;} \mathbf{y}\)</span></a></li>
<li class="chapter" data-level="1.5.2" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#intercepts-and-means"><i class="fa fa-check"></i><b>1.5.2</b> Intercepts and Means</a></li>
<li class="chapter" data-level="1.5.3" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#intercepts-and-means-1"><i class="fa fa-check"></i><b>1.5.3</b> Intercepts and Means</a></li>
<li class="chapter" data-level="1.5.4" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#what-are-mean-and-covariance-structures"><i class="fa fa-check"></i><b>1.5.4</b> What Are Mean and Covariance <em>Structures</em>?</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="regression-as-mean--and-covariance-structure-analysis.html"><a href="regression-as-mean--and-covariance-structure-analysis.html#references"><i class="fa fa-check"></i><b>1.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><i class="fa fa-check"></i><b>2</b> Using <code>lavaan</code> to Run Regression and ANOVA as a SEM</a>
<ul>
<li class="chapter" data-level="2.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#prepare-data-and-workspace"><i class="fa fa-check"></i><b>2.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#import-example-data"><i class="fa fa-check"></i><b>2.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="2.1.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#load-lavaan-into-workspace"><i class="fa fa-check"></i><b>2.1.2</b> Load <code>lavaan</code> into Workspace</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multiple-regression-in-sem"><i class="fa fa-check"></i><b>2.2</b> Multiple Regression in SEM</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#lavaan-syntax"><i class="fa fa-check"></i><b>2.2.1</b> <code>lavaan</code> Syntax</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#caveats-with-sem"><i class="fa fa-check"></i><b>2.3</b> Caveats with SEM</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#model-comparison-with-ols"><i class="fa fa-check"></i><b>2.3.1</b> Model Comparison with OLS</a></li>
<li class="chapter" data-level="2.3.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#model-comparison-with-lavaan"><i class="fa fa-check"></i><b>2.3.2</b> Model Comparison with <code>lavaan</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#moderation-caveats"><i class="fa fa-check"></i><b>2.3.3</b> Moderation Caveats</a></li>
<li class="chapter" data-level="2.3.4" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#summary-of-caveats"><i class="fa fa-check"></i><b>2.3.4</b> Summary of Caveats</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multigroup-sem"><i class="fa fa-check"></i><b>2.4</b> Multigroup SEM</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#group-specific-intercepts-in-ols"><i class="fa fa-check"></i><b>2.4.1</b> Group-Specific Intercepts in OLS</a></li>
<li class="chapter" data-level="2.4.2" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#group-specific-intercepts-in-sem"><i class="fa fa-check"></i><b>2.4.2</b> Group-Specific Intercepts in SEM?</a></li>
<li class="chapter" data-level="2.4.3" data-path="using-lavaan-to-run-regression-and-anova-as-a-sem.html"><a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html#multiple-groups-in-sem"><i class="fa fa-check"></i><b>2.4.3</b> Multiple Groups in SEM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="path-models.html"><a href="path-models.html"><i class="fa fa-check"></i><b>3</b> Path Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="path-models.html"><a href="path-models.html#illustrative-example"><i class="fa fa-check"></i><b>3.1</b> Illustrative example</a></li>
<li class="chapter" data-level="3.2" data-path="path-models.html"><a href="path-models.html#conceptual-explanation"><i class="fa fa-check"></i><b>3.2</b> Conceptual explanation</a></li>
<li class="chapter" data-level="3.3" data-path="path-models.html"><a href="path-models.html#matrix-explanation"><i class="fa fa-check"></i><b>3.3</b> Matrix explanation</a></li>
<li class="chapter" data-level="3.4" data-path="path-models.html"><a href="path-models.html#path-analysis-using-lavaan"><i class="fa fa-check"></i><b>3.4</b> Path analysis using lavaan</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="path-models.html"><a href="path-models.html#installing-lavaan-1"><i class="fa fa-check"></i><b>3.4.1</b> Installing lavaan</a></li>
<li class="chapter" data-level="3.4.2" data-path="path-models.html"><a href="path-models.html#fitting-a-path-model"><i class="fa fa-check"></i><b>3.4.2</b> Fitting a path model</a></li>
<li class="chapter" data-level="3.4.3" data-path="path-models.html"><a href="path-models.html#syntax-shortcuts"><i class="fa fa-check"></i><b>3.4.3</b> Syntax shortcuts</a></li>
<li class="chapter" data-level="3.4.4" data-path="path-models.html"><a href="path-models.html#extracting-results-from-lavaan-output-in-matrix-form"><i class="fa fa-check"></i><b>3.4.4</b> Extracting results from lavaan output in matrix form</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="path-models.html"><a href="path-models.html#references-1"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
<li class="chapter" data-level="3.6" data-path="path-models.html"><a href="path-models.html#appendix-3"><i class="fa fa-check"></i><b>3.6</b> Appendix I. Derivations of equation 3.08 and 3.09</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html"><i class="fa fa-check"></i><b>4</b> Standard Errors and Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#standard-errors"><i class="fa fa-check"></i><b>4.1</b> Standard Errors</a></li>
<li class="chapter" data-level="4.2" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#likelihood-based-confidence-intervals"><i class="fa fa-check"></i><b>4.2.1</b> Likelihood-based confidence intervals</a></li>
<li class="chapter" data-level="4.2.2" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#bootstrapped-confidence-intervals"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrapped confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#obtaining-standard-errors-and-confidence-intervals-in-lavaan"><i class="fa fa-check"></i><b>4.3</b> Obtaining standard errors and confidence intervals in <code>lavaan</code></a></li>
<li class="chapter" data-level="4.4" data-path="standard-errors-and-confidence-intervals.html"><a href="standard-errors-and-confidence-intervals.html#references-2"><i class="fa fa-check"></i><b>4.4</b> <strong>References</strong></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html"><i class="fa fa-check"></i><b>5</b> Direct, Indirect, and Total Effects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#testing-significance-of-indirect-effects"><i class="fa fa-check"></i><b>5.1</b> Testing significance of indirect effects</a></li>
<li class="chapter" data-level="5.2" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#higher-order-indirect-effects"><i class="fa fa-check"></i><b>5.2</b> Higher order indirect effects</a></li>
<li class="chapter" data-level="5.3" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#using-matrix-algebra-to-calculate-total-total-indirect-and-specific-indirect-effects"><i class="fa fa-check"></i><b>5.3</b> Using matrix algebra to calculate total, total indirect and specific indirect effects</a></li>
<li class="chapter" data-level="5.4" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#calculating-total-total-indirect-and-specific-indirect-effects-using-lavaan-output"><i class="fa fa-check"></i><b>5.4</b> Calculating total, total indirect and specific indirect effects using lavaan output</a></li>
<li class="chapter" data-level="5.5" data-path="direct-indirect-and-total-effects.html"><a href="direct-indirect-and-total-effects.html#calculating-specific-indirect-effects-in-lavaan"><i class="fa fa-check"></i><b>5.5</b> Calculating specific indirect effects in lavaan</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html"><i class="fa fa-check"></i><b>6</b> Calculating Standardized Parameter Estimates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardized-regression-coefficients"><i class="fa fa-check"></i><b>6.1</b> Standardized regression coefficients</a></li>
<li class="chapter" data-level="6.2" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardized-residual-factor-variances-and-covariances"><i class="fa fa-check"></i><b>6.2</b> Standardized residual factor variances and covariances</a></li>
<li class="chapter" data-level="6.3" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#calculating-standardized-coefficients-in-r-using-lavaan-results"><i class="fa fa-check"></i><b>6.3</b> Calculating standardized coefficients in R using lavaan results</a></li>
<li class="chapter" data-level="6.4" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#request-standardized-output-with-lavaan"><i class="fa fa-check"></i><b>6.4</b> Request standardized output with lavaan</a></li>
<li class="chapter" data-level="6.5" data-path="calculating-standardized-parameter-estimates.html"><a href="calculating-standardized-parameter-estimates.html#standardizing-indirect-and-total-effects"><i class="fa fa-check"></i><b>6.5</b> Standardizing indirect and total effects</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="identification.html"><a href="identification.html"><i class="fa fa-check"></i><b>7</b> Identification</a>
<ul>
<li class="chapter" data-level="7.1" data-path="identification.html"><a href="identification.html#assessment-of-identification-using-the-elements-of-mathbfsigma_textpopulation-and-mathbfsigma_textmodel"><i class="fa fa-check"></i><b>7.1</b> Assessment of identification using the elements of <span class="math inline">\(\mathbf\Sigma_{\text{population}}\)</span> and <span class="math inline">\(\mathbf\Sigma_{\text{model}}\)</span></a></li>
<li class="chapter" data-level="7.2" data-path="identification.html"><a href="identification.html#assessing-identification-through-heuristics-rules-of-thumb"><i class="fa fa-check"></i><b>7.2</b> Assessing identification through heuristics (rules of thumb)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="identification.html"><a href="identification.html#the-recursive-rule"><i class="fa fa-check"></i><b>7.2.1</b> The recursive rule</a></li>
<li class="chapter" data-level="7.2.2" data-path="identification.html"><a href="identification.html#the-order-condition"><i class="fa fa-check"></i><b>7.2.2</b> The order condition</a></li>
<li class="chapter" data-level="7.2.3" data-path="identification.html"><a href="identification.html#the-rank-condition"><i class="fa fa-check"></i><b>7.2.3</b> The rank condition</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="identification.html"><a href="identification.html#assessment-of-empirical-model-identification-using-lavaan"><i class="fa fa-check"></i><b>7.3</b> Assessment of empirical model identification using <code>lavaan</code></a></li>
<li class="chapter" data-level="7.4" data-path="identification.html"><a href="identification.html#appendix-7"><i class="fa fa-check"></i><b>7.4</b> Appendix I</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="identification.html"><a href="identification.html#algebraic-assessment-of-identification-using-elements-of-mathbfsigma_textpopulation-and-mathbfsigma_textmodel"><i class="fa fa-check"></i><b>7.4.1</b> Algebraic assessment of identification using elements of <span class="math inline">\(\mathbf\Sigma_{\text{population}}\)</span> and <span class="math inline">\(\mathbf\Sigma_{\text{model}}\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="autoregression.html"><a href="autoregression.html"><i class="fa fa-check"></i><b>8</b> Autoregression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="autoregression.html"><a href="autoregression.html#autoregression-models-with-predictors"><i class="fa fa-check"></i><b>8.1</b> Autoregression models with predictors</a></li>
<li class="chapter" data-level="8.2" data-path="autoregression.html"><a href="autoregression.html#cross-lagged-panel-models"><i class="fa fa-check"></i><b>8.2</b> Cross-lagged panel models</a></li>
<li class="chapter" data-level="8.3" data-path="autoregression.html"><a href="autoregression.html#references-3"><i class="fa fa-check"></i><b>8.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9.html"><a href="ch9.html"><i class="fa fa-check"></i><b>9</b> Model Specification and Model Identification</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch9.html"><a href="ch9.html#from-theory-to-model"><i class="fa fa-check"></i><b>9.1</b> From theory to model</a></li>
<li class="chapter" data-level="9.2" data-path="ch9.html"><a href="ch9.html#model-parsimony"><i class="fa fa-check"></i><b>9.2</b> Model parsimony</a></li>
<li class="chapter" data-level="9.3" data-path="ch9.html"><a href="ch9.html#a-priori-model-specification"><i class="fa fa-check"></i><b>9.3</b> A priori model specification</a></li>
<li class="chapter" data-level="9.4" data-path="ch9.html"><a href="ch9.html#post-hoc-model-modification"><i class="fa fa-check"></i><b>9.4</b> Post hoc model modification</a></li>
<li class="chapter" data-level="9.5" data-path="ch9.html"><a href="ch9.html#backward-and-forward-specification-searches"><i class="fa fa-check"></i><b>9.5</b> Backward and forward specification searches</a></li>
<li class="chapter" data-level="9.6" data-path="ch9.html"><a href="ch9.html#correlation-residuals"><i class="fa fa-check"></i><b>9.6</b> Correlation residuals</a></li>
<li class="chapter" data-level="9.7" data-path="ch9.html"><a href="ch9.html#modification-indices"><i class="fa fa-check"></i><b>9.7</b> Modification indices</a></li>
<li class="chapter" data-level="9.8" data-path="ch9.html"><a href="ch9.html#cross-validation"><i class="fa fa-check"></i><b>9.8</b> Cross-validation</a></li>
<li class="chapter" data-level="9.9" data-path="ch9.html"><a href="ch9.html#calculating-correlation-residuals-in-lavaan"><i class="fa fa-check"></i><b>9.9</b> Calculating correlation residuals in <code>lavaan</code></a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="ch9.html"><a href="ch9.html#requesting-mis-and-sepcs-in-lavaan"><i class="fa fa-check"></i><b>9.9.1</b> Requesting MIs and (S)EPCs in <code>lavaan</code></a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="ch9.html"><a href="ch9.html#references-4"><i class="fa fa-check"></i><b>9.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>10</b> Estimation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estimation.html"><a href="estimation.html#improper-solutions"><i class="fa fa-check"></i><b>10.1</b> Improper Solutions</a></li>
<li class="chapter" data-level="10.2" data-path="estimation.html"><a href="estimation.html#specifying-starting-values-in-lavaan"><i class="fa fa-check"></i><b>10.2</b> Specifying starting values in lavaan</a></li>
<li class="chapter" data-level="10.3" data-path="estimation.html"><a href="estimation.html#alternative-estimators"><i class="fa fa-check"></i><b>10.3</b> Alternative estimators</a></li>
<li class="chapter" data-level="10.4" data-path="estimation.html"><a href="estimation.html#robust-estimators"><i class="fa fa-check"></i><b>10.4</b> Robust estimators</a></li>
<li class="chapter" data-level="10.5" data-path="estimation.html"><a href="estimation.html#requesting-alternative-and-robust-estimators-in-lavaan"><i class="fa fa-check"></i><b>10.5</b> Requesting alternative and robust estimators in lavaan</a></li>
<li class="chapter" data-level="10.6" data-path="estimation.html"><a href="estimation.html#alternative-calculation-of-the-ml-discrepancy-function-when-analysing-raw-data"><i class="fa fa-check"></i><b>10.6</b> Alternative calculation of the ML discrepancy function when analysing raw data</a></li>
<li class="chapter" data-level="10.7" data-path="estimation.html"><a href="estimation.html#using-fiml-to-analyse-raw-data-with-missing-values-in-lavaan"><i class="fa fa-check"></i><b>10.7</b> Using FIML to analyse raw data with missing values in lavaan</a></li>
<li class="chapter" data-level="10.8" data-path="estimation.html"><a href="estimation.html#references-5"><i class="fa fa-check"></i><b>10.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="measures-of-model-fit.html"><a href="measures-of-model-fit.html"><i class="fa fa-check"></i><b>11</b> Measures of Model Fit</a>
<ul>
<li class="chapter" data-level="11.1" data-path="measures-of-model-fit.html"><a href="measures-of-model-fit.html#the-chi-squared-test-of-exact-fit"><i class="fa fa-check"></i><b>11.1</b> The chi-squared test of exact fit</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="measures-of-model-fit.html"><a href="measures-of-model-fit.html#alternative-basis-for-calculating-the-test-statistic-when-analysing-raw-data"><i class="fa fa-check"></i><b>11.1.1</b> Alternative basis for calculating the test statistic when analysing raw data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html"><i class="fa fa-check"></i><b>12</b> Path Analysis with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="12.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#prepare-data-and-workspace-1"><i class="fa fa-check"></i><b>12.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#import-example-data-1"><i class="fa fa-check"></i><b>12.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="12.1.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#summarize-data"><i class="fa fa-check"></i><b>12.1.2</b> Summarize Data</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#regression-models-for-binary-variables"><i class="fa fa-check"></i><b>12.2</b> Regression Models for Binary Variables</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#fit-a-logistic-regression-model"><i class="fa fa-check"></i><b>12.2.1</b> Fit a Logistic Regression Model</a></li>
<li class="chapter" data-level="12.2.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#fit-a-probit-regression-model"><i class="fa fa-check"></i><b>12.2.2</b> Fit a Probit Regression Model</a></li>
<li class="chapter" data-level="12.2.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#compare-models"><i class="fa fa-check"></i><b>12.2.3</b> Compare Models</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#latent-response-variable"><i class="fa fa-check"></i><b>12.3</b> Latent Response Variable</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#ordinal-outcomes"><i class="fa fa-check"></i><b>12.3.1</b> Ordinal Outcomes</a></li>
<li class="chapter" data-level="12.3.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-thresholds"><i class="fa fa-check"></i><b>12.3.2</b> Estimating Thresholds</a></li>
<li class="chapter" data-level="12.3.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-polychoric-correlations"><i class="fa fa-check"></i><b>12.3.3</b> Estimating Polychoric Correlations</a></li>
<li class="chapter" data-level="12.3.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimating-an-sem-with-estimated-input"><i class="fa fa-check"></i><b>12.3.4</b> Estimating an SEM with Estimated Input</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#mediation-model-with-categorical-outcomes"><i class="fa fa-check"></i><b>12.4</b> Mediation Model with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#estimate-mediation-models"><i class="fa fa-check"></i><b>12.4.1</b> Estimate Mediation Models</a></li>
<li class="chapter" data-level="12.4.2" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#interpreting-coefficients"><i class="fa fa-check"></i><b>12.4.2</b> Interpreting Coefficients</a></li>
<li class="chapter" data-level="12.4.3" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#delta-vs.-theta-parameterizations"><i class="fa fa-check"></i><b>12.4.3</b> Delta vs. Theta Parameterizations</a></li>
<li class="chapter" data-level="12.4.4" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#decomposing-total-effects"><i class="fa fa-check"></i><b>12.4.4</b> Decomposing Total Effects</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="path-analysis-with-categorical-outcomes.html"><a href="path-analysis-with-categorical-outcomes.html#references-6"><i class="fa fa-check"></i><b>12.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html"><i class="fa fa-check"></i><b>13</b> Fitting path models with multilevel data</a>
<ul>
<li class="chapter" data-level="13.1" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#intraclass-correlation"><i class="fa fa-check"></i><b>13.1</b> Intraclass correlation</a></li>
<li class="chapter" data-level="13.2" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#multilevel-structure-as-a-nuisance-correcting-for-the-dependency"><i class="fa fa-check"></i><b>13.2</b> Multilevel structure as a nuisance: Correcting for the dependency</a></li>
<li class="chapter" data-level="13.3" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#two-level-path-models"><i class="fa fa-check"></i><b>13.3</b> Two-level path models</a></li>
<li class="chapter" data-level="13.4" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#obtaining-iccs-and-estimates-of-sigma_textw-and-sigma_textb"><i class="fa fa-check"></i><b>13.4</b> Obtaining ICCs, and estimates of <span class="math inline">\(\Sigma_\text{W}\)</span> and <span class="math inline">\(\Sigma_\text{B}\)</span></a></li>
<li class="chapter" data-level="13.5" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#fitting-a-two-level-path-model"><i class="fa fa-check"></i><b>13.5</b> Fitting a two-level path model</a></li>
<li class="chapter" data-level="13.6" data-path="fitting-path-models-with-multilevel-data.html"><a href="fitting-path-models-with-multilevel-data.html#references-7"><i class="fa fa-check"></i><b>13.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html"><i class="fa fa-check"></i><b>14</b> Latent Growth Curve Models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#prepare-data-and-workspace-2"><i class="fa fa-check"></i><b>14.1</b> Prepare Data and Workspace</a></li>
<li class="chapter" data-level="14.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#random-intercept-model"><i class="fa fa-check"></i><b>14.2</b> Random Intercept Model</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#specification-and-estimation"><i class="fa fa-check"></i><b>14.2.1</b> Specification and Estimation</a></li>
<li class="chapter" data-level="14.2.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#interpret-results"><i class="fa fa-check"></i><b>14.2.2</b> Interpret Results</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#linear-growth-model"><i class="fa fa-check"></i><b>14.3</b> Linear Growth Model</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#model-fit-and-comparison"><i class="fa fa-check"></i><b>14.3.1</b> Model Fit and Comparison</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#unrestricted-growth-models"><i class="fa fa-check"></i><b>14.4</b> Unrestricted Growth Models</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#latent-basis-curve"><i class="fa fa-check"></i><b>14.4.1</b> Latent Basis Curve</a></li>
<li class="chapter" data-level="14.4.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#saturated-growth-model"><i class="fa fa-check"></i><b>14.4.2</b> Saturated Growth Model</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#explaining-growth-factors"><i class="fa fa-check"></i><b>14.5</b> Explaining Growth Factors</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#time-invariant-level-2-predictors"><i class="fa fa-check"></i><b>14.5.1</b> Time-Invariant (Level-2) Predictors</a></li>
<li class="chapter" data-level="14.5.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#time-varying-level-1-predictors"><i class="fa fa-check"></i><b>14.5.2</b> Time-Varying (Level-1) Predictors</a></li>
<li class="chapter" data-level="14.5.3" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#parallel-growth-curves"><i class="fa fa-check"></i><b>14.5.3</b> Parallel Growth Curves</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#latent-indicators-of-growth-factors"><i class="fa fa-check"></i><b>14.6</b> Latent Indicators of Growth Factors</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#common-factors"><i class="fa fa-check"></i><b>14.6.1</b> Common Factors</a></li>
<li class="chapter" data-level="14.6.2" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#discrete-indicators"><i class="fa fa-check"></i><b>14.6.2</b> Discrete Indicators</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#multigroup-growth-models"><i class="fa fa-check"></i><b>14.7</b> Multigroup Growth Models</a></li>
<li class="chapter" data-level="14.8" data-path="latent-growth-curve-models.html"><a href="latent-growth-curve-models.html#references-8"><i class="fa fa-check"></i><b>14.8</b> References</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Compendium Structural Equation Modeling in Educational Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="path-models" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Path Models<a href="path-models.html#path-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Path analysis is one of the families of statistical analyses within the structural equation modeling (SEM) framework. Path analysis is used to describe the dependencies between a set of observed variables, where a structural model defines the directional relations between the variables. Path analysis builds on regression analysis principles, but can be used for more complex models that include multiple dependent variables or (multiple) mediator variables. We will first introduce the illustrative example that is used throughout this and subsequent chapters on path models. Then, we will explain the path model both conceptually and technically. Finally, we will illustrate how to fit a path model with an empirical data example using the <code>lavaan</code> program.</p>
<div id="illustrative-example" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Illustrative example<a href="path-models.html#illustrative-example" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To illustrate path analysis we will use data from a study by Affrunti and Woodruff-Borden (2014) who investigated the development of child anxiety. They hypothesized that perfectionistic parents will engage in behaviors characterized by overcontrol, which then will increase child anxiety. In addition, parent anxiety was thought to influence child anxiety. In order to test their hypothesized model the variables parent perfectionism, parental overcontrol, parent anxiety and child anxiety were measured in 77 families (see Affrunti &amp; Woodruff-Borden, 2014 for more information on data collection and operationalization of the variables). In this chapter we will use a slightly adapted version of the model on the development of child anxiety.</p>
</div>
<div id="conceptual-explanation" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Conceptual explanation<a href="path-models.html#conceptual-explanation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Figure 3.1 is a graphical display of the path diagram of the structural model for the development of child anxiety that serves our illustrative purposes. A path diagram is a graphical representation of the path model in which the directional relationships between observed variables are defined. The four squares represent the observed variables parental anxiety (PA), parental perfectionism (PP), parental overcontrol (PO) and child anxiety (CA). The effects between the observed variables are represented by one sided arrows (→).</p>
<p>In our example, the model consists of direct effects from parent anxiety and parent perfectionism on parental overcontrol, and a direct effect of parental overcontrol on child anxiety. Parent anxiety and parent perfectionism are so-called “exogenous” variables. The states or values of exogenous variables are not influenced by other variables in the model. They are sometimes also referred to as independent variables or predictor variables. Parental overcontrol and child anxiety are so-called “endogenous” variables, as they are assumed to be influenced by the states of the other variables in the model. An endogenous variable is sometimes referred to as a dependent variable. However, an endogenous variable can also have an effect on another endogenous variable in the model. In our example, parental overcontrol is influenced by parent anxiety and parent perfectionism (i.e., parental overcontrol is an endogenous variable). Parental overcontrol, in turn, also has a direct effect on child anxiety. This path model therefore represents a mediation model, where the effects of parent anxiety and parent perfectionism on child anxiety are fully mediated through parental overcontrol.</p>
<p><img src="images/Fig1.Week2.Ch3.jpg" width="80%" style="display: block; margin: auto;" /></p>
<p><em>Figure 3.1.</em> A simple path diagram of the development of child anxiety</p>
<p>Figure 3.1 not only gives a graphical representation of the set of directional relations between the observed variables, but also includes the circles <span class="math inline">\({\zeta}_{PA}\)</span>, <span class="math inline">\({\zeta}_{PF}\)</span>, <span class="math inline">\({\zeta}_{PO}\)</span>, and <span class="math inline">\({\zeta}_{CA}\)</span> that represent the so-called residual factors. Residual factors are unobserved, latent variables that represent all factors that fall outside the model but may influence the states of the corresponding observed variables. The directional effects from the residual factors to the corresponding observed variables are accompanied by the numeral ‘1’. This indicates that these effects are fixed to ‘1’, which is a so-called scaling constant (which will be explained in more detail in Chapter 12). Because these scaling constants for residual factors apply to almost all models, they are often not displayed in path diagrams.</p>
<p>For endogenous variables, the residual factor can be viewed as a kind of ‘container’ variable, that contains all variables that also affect the specific endogenous variable, but that were not included in the model. The residual factors therefore symbolize the probabilistic causality of path analysis, as they indicate that endogenous variables are not only influenced by other variables in the model but also by (unobserved) variables that are outside the model (i.e., unmeasured causes). For example, in the model for the development of child anxiety, it would be unrealistic to assume that the anxiety of a child is only determined by parents’ behavior of overcontrol. It might be that there are also other factors, e.g. past experiences, contact with peers, or genetic predisposition, that have an effect on the anxiety of a child. To enable a model where child anxiety is only partially influenced by parental overcontrol, the unmeasured causes of child anxiety are incorporated in the model through the residual factor. The residual factors of endogenous variables are therefore sometimes also referred to as disturbance factors.</p>
<p>The residual factors of exogenous variables can also be viewed as a container variable that contains all (unobserved) variables that are outside the model (i.e., unmeasured causes) that influence the corresponding exogenous variable. However, because exogenous variables are not influenced by other variables in the model, the residual factor of an exogenous variable represents the total variances of the corresponding variable. In addition, the residual factors of different exogenous variables covary. For example, in the path diagram of Figure 1 there is a covariance between the two residual factors of parent anxiety and parent perfectionism, as reflected by the double headed arrow (&lt;–&gt;). This reflects the assumption that the unmeasured causes of the corresponding exogenous variables may covary, although the model does not provide an explanation for this association (i.e., they are outside the model). For example, parental neuroticism may be a common cause of parental anxiety and parental perfectionism, leading to a covariance between the two variables. Because the common causes are not modelled, and we may not even know all possible sources of shared variance between exogenous variables, it is very unrealistic to assume that the exogenous variables would not be correlated.</p>
<p>For both exogenous and endogenous variables, the residual factor also reflects measurement error. The variance of a residual factor therefore partly consists of variance of the corresponding variable due to random error fluctuations. Thus, one cannot distinguish residual variance due to measurement error (i.e., unsystematic variance) and residual variance due to unmeasured causes (i.e., systematic variance). When the measure of the observed variable is unreliable this will inflate the variance of the corresponding residual factor and can be confounded with variance due to unmeasured causes of the variable.</p>
</div>
<div id="matrix-explanation" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Matrix explanation<a href="path-models.html#matrix-explanation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In general, the aim of path analysis is to describe the dependencies between a set of observed variables, based on some theory. In order to do this, we try to define a theoretically sensible path model that can accurately describe the variances and covariances of the observed variables in the population and formulate the following hypothesis:</p>
<p><span class="math inline">\(\mathbf{\Sigma}_{\text{population}} = \mathbf{\Sigma}_{\text{model}}\)</span>,</p>
<p>where <span class="math inline">\(\mathbf{\Sigma}_{\text{population}}\)</span> is the matrix of population variances and covariances of the observed variables, and <span class="math inline">\(\mathbf{\Sigma}_{model}\)</span> is the matrix of variances and covariances of the observed variables as implied by the path model. The population variances and covariances are unknown, as data are usually only collected in a sample that was drawn from the population. Therefore, we estimate the population variances and covariances based on the sample variances and covariances:</p>
<p><span class="math inline">\(\mathbf{\Sigma}_{\text{population}} \approx \mathbf{\hat\Sigma}_{\text{population}}\)</span> , where <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{population}} = \mathbf{\Sigma}_{\text{sample}}\)</span>.</p>
<p>As a covariance matrix is a symmetric matrix, usually the upper triangle of the matrix is not provided:</p>
<p><span class="math display">\[
\mathbf{\Sigma}_{\text{population}} =
\begin{bmatrix}
\sigma_{11}  &amp; &amp; \\
\sigma_{21} &amp; \sigma_{22} &amp; \\
\sigma_{31} &amp; \sigma_{32} &amp; \sigma_{33} \\
\sigma_{41} &amp; \sigma_{42} &amp; \sigma_{43} &amp; \sigma_{44}
\end{bmatrix}
\approx
\begin{bmatrix}
\hat\sigma_{11}  &amp; &amp; \\
\hat\sigma_{21} &amp; \hat\sigma_{22} &amp; \\
\hat\sigma_{31} &amp; \hat\sigma_{32} &amp; \hat\sigma_{33} \\
\hat\sigma_{41} &amp; \hat\sigma_{42} &amp; \hat\sigma_{43} &amp; \hat\sigma_{44}
\end{bmatrix}.
\]</span></p>
<p>The variances of the variables are given on the diagonal of the matrix (<span class="math inline">\(\sigma_{11}\)</span> to <span class="math inline">\(\sigma_{44}\)</span>) and the covariances are given on the lower triangle of the matrix (e.g., <span class="math inline">\(\sigma_{21}\)</span> represents the covariance between variable <span class="math inline">\(\mathrm{y}_2\)</span> and variable <span class="math inline">\(\mathrm{y}_1\)</span>). The values of the upper triangular are equal to the lower triangular (e.g., <span class="math inline">\(\sigma_{21}\)</span> is equal to <span class="math inline">\(\sigma_{12}\)</span>). The population variances and covariances are estimated using the sample variances and covariances, where:</p>
<p><span class="math display">\[
\mathbf{\Sigma}_{\text{sample}} =
\begin{bmatrix}
s_{11}  &amp; &amp; \\
s_{21} &amp; s_{22} &amp; \\
s_{31} &amp; s_{32} &amp; s_{33} \\
s_{41} &amp; s_{42} &amp; s_{43} &amp; s_{44}
\end{bmatrix}.
\]</span></p>
<p>Here, the elements of <span class="math inline">\(\mathbf{\Sigma}_{\text{sample}}\)</span> are denoted with ‘s’. As an example, the observed sample variance of the first variable, <span class="math inline">\(s_{11}\)</span>, serves as an estimate of the population variance of the first variable, <span class="math inline">\(\hat\sigma_{11}\)</span>. The sample covariance matrix of our illustrative example of child anxiety is given by:</p>
<p><span class="math display">\[
\mathbf{\Sigma}_{\text{sample}} =
\begin{bmatrix}
91.58  &amp; &amp; \\
53.36 &amp; 194.32 &amp; \\
28.39 &amp; 50.90 &amp; 130.19 \\
9.21 &amp; 4.98 &amp; 9.41 &amp; 7.56
\end{bmatrix}.
\]</span></p>
<p>Thus, the variance of the variable parent anxiety is 91.58, and the covariance between the variables parent anxiety and parent perfectionism is 53.36.</p>
<p>Similarly, we do not know the ‘true’ variances and covariances of the observed variables in the population as implied by the ‘true’ model parameters in the path model. Instead, we derive an estimated variance-covariance matrix as implied by the model:</p>
<p><span class="math inline">\(\mathbf{\Sigma}_{\text{model}} \approx \mathbf{\hat\Sigma}_{\text{model}}\)</span>,</p>
<p>where <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{model}}\)</span> is a function of sample estimates of the unknown model parameters. Thus, to enable calculation of <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{model}}\)</span> we first need to derive estimates of all model parameters that feature in the path model. Below, we will describe the relationships between the observed variables in terms of model parameters, and explain how they can be used to find expressions for the variances and covariances.</p>
<p>Figure 3.2 shows the Greek symbols that represent the variables and parameters that feature in the path model. The observed variables parental anxiety, parental perfectionism, parental overcontrol and child anxiety are represented by the squares <span class="math inline">\(\mathrm{y}_1\)</span>, <span class="math inline">\(\mathrm{y}_2\)</span>, <span class="math inline">\(\mathrm{y}_3\)</span>, and <span class="math inline">\(\mathrm{y}_4\)</span> respectively. The direct effects between the observed variables are denoted <span class="math inline">\(\beta_{31}\)</span>, <span class="math inline">\(\beta_{32}\)</span>, and <span class="math inline">\(\beta_{43}\)</span>. These direct effects are also called path coefficients and can be interpreted as regression coefficients. In general, <span class="math inline">\(\beta_{ij}\)</span> is the regression of variable <span class="math inline">\(\mathrm{y}_{i}\)</span> on <span class="math inline">\(\mathrm{y}_{j}\)</span>, or, equivalently, the effect of <span class="math inline">\(\mathrm{y}_{j}\)</span> on <span class="math inline">\(\mathrm{y}_{i}\)</span>. In addition, the circles are residual factors <span class="math inline">\(\zeta_{1}\)</span>, <span class="math inline">\(\zeta_{2}\)</span>, <span class="math inline">\(\zeta_{3}\)</span>, and <span class="math inline">\(\zeta_{4}\)</span> that represent all factors that fall outside the model, i.e., unmeasured causes.</p>
<p><img src="images/Fig2.Week2.Ch3.jpg" width="80%" style="display: block; margin: auto;" /></p>
<p><em>Figure 3.2.</em> Path diagram of the development of child anxiety including all path coefficients</p>
<p>Using the symbols described above, the relations between the variables can be represented by the following equations:</p>
<p><span class="math display" id="eq:3-01">\[\begin{equation}
\mathrm{y}_1 = \zeta_1
\tag{3.1}
\end{equation}\]</span>
<span class="math display" id="eq:3-02">\[\begin{equation}
\mathrm{y}_2 = \zeta_2
\tag{3.2}
\end{equation}\]</span>
<span class="math display" id="eq:3-03">\[\begin{equation}
\mathrm{y}_3=\beta_{31}\mathrm{y}_1+\beta_{32}\mathrm{y}_2 + \zeta_3
\tag{3.3}
\end{equation}\]</span>
<span class="math display" id="eq:3-04">\[\begin{equation}
\mathrm{y}_4 = \beta_{43} \mathrm{y}_3 + \zeta_4
\tag{3.4}
\end{equation}\]</span></p>
<p>Here, we can see that exogenous variables <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span> are only affected by factors that fall outside the model (<span class="math inline">\(\zeta_1\)</span> and <span class="math inline">\(\zeta_2\)</span>), whereas endogenous variable <span class="math inline">\(\mathrm{y}_3\)</span> and <span class="math inline">\(\mathrm{y}_4\)</span> are affected also by the other variables in the model. Note that the effects of the residual factors are left out of these Equations because they are constrained to ‘1’ (i.e., we could write <span class="math inline">\(\mathrm{y}_1\)</span> = (direct effect)<span class="math inline">\(\zeta_1\)</span>, where (direct effect) = 1, which thus simplifies to <span class="math inline">\(\mathrm{y}_1\)</span> = <span class="math inline">\(\zeta_1\)</span>).</p>
<p>Instead of writing down the equation for each observed variable, the equations for the observed variables <span class="math inline">\(\mathrm{y}_1\)</span>, <span class="math inline">\(\mathrm{y}_2\)</span>, <span class="math inline">\(\mathrm{y}_3\)</span>, and <span class="math inline">\(\mathrm{y}_4\)</span> can also be written in matrix form:</p>
<p><span class="math display" id="eq:3-05">\[\begin{equation}
\mathbf{y} = \mathbf{B} \mathbf{y} + \boldsymbol{\zeta}
\tag{3.5}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\mathbf{y}\)</span> is a vector of all observed variables, <span class="math inline">\(\boldsymbol{\zeta}\)</span> is a vector of all residual factors, and <span class="math inline">\(\mathbf{B}\)</span> is a matrix of regression coefficients:</p>
<p><span class="math display">\[
\mathbf{y} =
\begin{bmatrix}
\mathrm{y}_1 \\
\mathrm{y}_2 \\
\mathrm{y}_3 \\
\mathrm{y}_4
\end{bmatrix}
, \boldsymbol{\zeta} =
\begin{bmatrix}
\zeta_1 \\
\zeta_2 \\
\zeta_3 \\
\zeta_4
\end{bmatrix}, \mathrm{and} \hspace{1mm} \mathbf{B} =
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 \\
\beta_{31} &amp;  \beta_{32} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \beta_{43} &amp; 0
\end{bmatrix}.
\]</span></p>
<p>Matrix <span class="math inline">\(\mathbf{B}\)</span> contains three non-zero elements: <span class="math inline">\(\beta_{31}\)</span>, <span class="math inline">\(\beta_{32}\)</span>, <span class="math inline">\(\beta_{43}\)</span>. The regression coefficient <span class="math inline">\(\beta_{31}\)</span> represent the effect ofvariable <span class="math inline">\(\mathrm{y}_1\)</span> on variable <span class="math inline">\(\mathrm{y}_3\)</span>, the regression coefficient <span class="math inline">\(\beta_{32}\)</span> represent the effect of variable <span class="math inline">\(\mathrm{y}_2\)</span> on variable <span class="math inline">\(\mathrm{y}_3\)</span>, and the regression coefficient <span class="math inline">\(\beta_{43}\)</span> represent the effect of variable <span class="math inline">\(\mathrm{y}_3\)</span> on variable <span class="math inline">\(\mathrm{y}_4\)</span>.</p>
<p>Substituting these matrices into Equation <a href="path-models.html#eq:3-05">(3.5)</a> gives:</p>
<p><span class="math display" id="eq:3-06">\[\begin{equation}
\begin{bmatrix}
\mathrm{y}_1 \\
\mathrm{y}_2 \\
\mathrm{y}_3 \\
\mathrm{y}_4
\end{bmatrix}
=  
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 \\
\beta_{31} &amp;  \beta_{32} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \beta_{43} &amp; 0
\end{bmatrix}
\times
\begin{bmatrix}
\mathrm{y}_1 \\
\mathrm{y}_2 \\
\mathrm{y}_3 \\
\mathrm{y}_4
\end{bmatrix}
+
\begin{bmatrix}
\zeta_1 \\
\zeta_2 \\
\zeta_3 \\
\zeta_4
\end{bmatrix},
\tag{3.6}
\end{equation}\]</span></p>
<p>which yields:</p>
<p><span class="math display" id="eq:3-07">\[\begin{equation}
\begin{bmatrix}
\mathrm{y}_1 \\
\mathrm{y}_2 \\
\mathrm{y}_3 \\
\mathrm{y}_4
\end{bmatrix}
=  
\begin{bmatrix}
&amp; &amp;  \zeta_1  &amp; &amp; \\
&amp; &amp; \zeta_2  &amp; &amp; \\
\beta_{31} \mathrm{y}_1 &amp; + &amp; \beta_{32} \mathrm{y}_2 &amp; + &amp; \zeta_3 \\
&amp; &amp; \beta_{43} \mathrm{y}_3 + \zeta_4 &amp;
\end{bmatrix}.
\tag{3.7}
\end{equation}\]</span></p>
<p>Here, we can see that the equations for variables <span class="math inline">\(\mathrm{y}_1\)</span>, <span class="math inline">\(\mathrm{y}_2\)</span>, <span class="math inline">\(\mathrm{y}_3\)</span>, and <span class="math inline">\(\mathrm{y}_4\)</span> are the same as separate Equations <a href="path-models.html#eq:3-01">(3.1)</a> through <a href="path-models.html#eq:3-04">(3.4)</a>.</p>
<p>The path model as described by Equation 3.07 is used to describe the relationships between the observed variables. In order to find the model for the variances and covariances of the observed variables, we have to re-write Equation <a href="path-models.html#eq:3-05">(3.5)</a> as a function of model parameters:</p>
<p><span class="math display">\[\mathrm{y} = \mathbf{B} \mathrm{y} + \zeta \Leftrightarrow\]</span>
<span class="math display" id="eq:3-08">\[\begin{equation}
\mathrm{y} = (\mathbf{I} - \mathbf{B})^{-1} \zeta
\tag{3.8}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\mathbf{I}\)</span> is an identity matrix that needs to be introduced to come to the end result, and <span class="math inline">\((\mathbf{I} - \mathbf{B})^{-1}\)</span> denotes the inverse of the matrix <span class="math inline">\((\mathbf{I} - \mathbf{B})\)</span>. Derivations of Equation <a href="path-models.html#eq:3-08">(3.8)</a> are given in <a href="path-models.html#appendix-3">Appendix 1</a>.</p>
<p>We now have an expression for the scores on the variables. However, in standard SEM, we do not model the observed scores directly, but the variances and covariance of the observed scores. Therefore, we need to find an expression for the model implied covariance matrix. Using Equation 3.08 and some covariance algebra, we obtain the expression for the variances and covariances of <span class="math inline">\(\mathrm{y}\)</span>, called <span class="math inline">\(\mathbf{\Sigma}_{\text{model}}\)</span> = COV<span class="math inline">\((\mathbf{y},\mathbf{y})\)</span>:</p>
<p><span class="math display" id="eq:3-09">\[\begin{equation}
\mathbf{\Sigma}_{\text{model}} = (\mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\Psi} (\mathbf{I} - \mathbf{B})^{-1\mathrm{T}}
\tag{3.9}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\boldsymbol{\Psi}\)</span> is written for COV(<span class="math inline">\(\boldsymbol\zeta\)</span>,<span class="math inline">\(\boldsymbol\zeta\)</span>), and <span class="math inline">\((\mathbf{I} - \mathbf{B})^{-1\mathrm{T}}\)</span> denotes the transpose of the matrix <span class="math inline">\((\mathbf{I} - \mathbf{B})^{-1}\)</span>. Derivations of Equation <a href="path-models.html#eq:3-09">(3.9)</a> are given in <a href="path-models.html#appendix-3">Appendix 1</a>.</p>
<p>The symmetric matrix <span class="math inline">\(\boldsymbol{\Psi}\)</span> contains the variances and the covariances of the residual factors <span class="math inline">\(\boldsymbol\zeta\)</span>. For the model given in Equation <a href="path-models.html#eq:3-07">(3.7)</a>, matrix <span class="math inline">\(\boldsymbol{\Psi}\)</span> is</p>
<p><span class="math display">\[
\boldsymbol{\Psi} =
\begin{bmatrix}
\psi_{11} &amp; \psi_{12} &amp; 0 &amp; 0 \\
\psi_{21} &amp; \psi_{22} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \psi_{33} &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; \psi_{44}
\end{bmatrix}
\]</span></p>
<p>where <span class="math inline">\(\psi_{11}\)</span> and <span class="math inline">\(\psi_{22}\)</span> represent the variances of <span class="math inline">\(\zeta_1\)</span> and <span class="math inline">\(\zeta_2\)</span> and are thus equivalent with the variances of the exogenous variables <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span>. The covariance of <span class="math inline">\(\zeta_{1}\)</span> and <span class="math inline">\(\zeta_{2}\)</span> is represented by <span class="math inline">\(\psi_{12}\)</span> and is thus equivalent with the covariance of <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span>. Because a covariance matrix is a symmetric matrix, <span class="math inline">\(\psi_{12}\)</span> is equal to <span class="math inline">\(\psi_{21}\)</span>. Parameters <span class="math inline">\(\psi_{33}\)</span> and <span class="math inline">\(\psi_{44}\)</span> are the variances of <span class="math inline">\(\zeta_3\)</span> and <span class="math inline">\(\zeta_4\)</span>, equivalent with the residual variances (or disturbance variances) of <span class="math inline">\(\mathrm{y}_3\)</span> and <span class="math inline">\(\mathrm{y}_4\)</span>, that is, that part of the variances of <span class="math inline">\(\mathrm{y}_3\)</span> and <span class="math inline">\(\mathrm{y}_4\)</span> that are not explained by the model.Note that the <span class="math inline">\(\zeta\)</span> variances associated with endogenous variables <span class="math inline">\(\mathrm{y}_3\)</span> and <span class="math inline">\(\mathrm{y}_4\)</span> have the same interpretation as the <span class="math inline">\(\zeta\)</span> variances associated with exogenous variables <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span>, but whereas all variance of <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span> is unexplained by the model (and thus <span class="math inline">\(\psi_{11}\)</span> and <span class="math inline">\(\psi_{22}\)</span> are equivalent with the variances of <span class="math inline">\(\mathrm{y}_1\)</span> and <span class="math inline">\(\mathrm{y}_2\)</span>), only part of the variances of <span class="math inline">\(\mathrm{y}_3\)</span> and <span class="math inline">\(\mathrm{y}_4\)</span> is unexplained by the model.</p>
<p>Now that we have found the general expression for the variances and covariances as a function of model parameters, we can evaluate Equation 3.09 of our example. Substituting <span class="math inline">\(\mathbf{B}\)</span> and <span class="math inline">\(\boldsymbol{\Psi}\)</span> of our example we obtain:</p>
<p><span class="math inline">\(\mathbf{\Sigma}_{\text{model}} = (\mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\Psi} (\mathbf{I} - \mathbf{B})^{-1\mathrm{T}}\)</span>, where:</p>
<p><span class="math display">\[
(\mathbf{I} - \mathbf{B})^{-1} =
\Bigg(
\begin{bmatrix}
1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 1 \\
\end{bmatrix}
-
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0  \\
0 &amp; 0 &amp; 0 &amp; 0 \\
\beta_{31} &amp; \beta_{32} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \beta_{43} &amp; 0
\end{bmatrix}
\Bigg)
^{-1}
=
\begin{bmatrix}
1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 &amp; 0 \\
\beta_{31} &amp; \beta_{32} &amp; 1 &amp; 0 \\
\beta_{31}\beta_{43} &amp; \beta_{32}\beta_{43} &amp; \beta_{43} &amp; 1
\end{bmatrix},
\]</span>
<span class="math display">\[
\boldsymbol{\Psi} =
\begin{bmatrix}
\psi_{11} &amp; \psi_{21} &amp; 0 &amp; 0 \\
\psi_{21} &amp; \psi_{22} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \psi_{33} &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; \psi_{44}
\end{bmatrix}, \mathrm{and}
\]</span></p>
<p><span class="math display">\[
(\mathbf{I} - \mathbf{B})^{-1\mathrm{T}} =
\Bigg(
\begin{bmatrix}
1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 1 &amp; 1 \\
0 &amp; 0 &amp; 0 &amp; 1
\end{bmatrix}
-
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 \\
\beta_{31} &amp; \beta_{32} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \beta_{43} &amp; 0
\end{bmatrix}
\Bigg)^{-1\mathrm{T}}
=
\begin{bmatrix}
1 &amp; 0 &amp; \beta_{31} &amp; \beta_{31}\beta_{43} \\
0 &amp; 1 &amp; \beta_{32} &amp; \beta_{32}\beta_{43} \\
0 &amp; 0 &amp; 1 &amp; \beta_{43} \\
0 &amp; 0 &amp; 0 &amp; 1
\end{bmatrix}.
\]</span></p>
<p>Which yields:</p>
<p><img src="images/Equation.Week2.Ch3.jpg" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
<p><span class="math display" id="eq:3-10">\[\begin{equation}
\Sigma_{\text{model}} =
\begin{bmatrix}
\\
\psi_{11} &amp; &amp; &amp; \\

\\
\psi_{21} &amp; \psi_{22} &amp; &amp; \\

\\
\beta_{31} \psi_{11} +  &amp; \beta_{31} \psi_{21} +  &amp; (\beta_{31}\psi_{11}+\beta_{32}\psi_{31}) \beta_{31} +  &amp; \\
\beta_{32} \psi_{21}&amp;\beta_{32} \psi_{22}&amp;(\beta_{31}\psi_{21}+\beta_{32}\psi_{22}) \beta_{32}\psi_{33}&amp;
\\
\\

\beta_{31}\beta_{43}\psi_{11} +  &amp; \beta_{31}\beta_{43}\psi_{21} +  &amp; (\beta_{31}\beta_{43}\psi_{11} + \beta_{32}\beta_{43}\psi_{21}) \beta_{31} + &amp; (\beta_{31}\beta_{43}\psi_{11} + \beta_{32}\beta_{43}\psi_{21})\beta_{31}\beta_{43} +  \\

\beta_{32}\beta_{43}\psi_{21} &amp; \beta_{32}\beta_{43}\psi_{22} &amp; (\beta_{31}\beta_{43}\psi_{21} + \beta_{32}\beta_{43}\psi_{22}) \beta_{32} + &amp; (\beta_{31}\beta_{43}\psi_{21} + \beta_{32}\beta_{43} \psi_{22})\beta_{32}\beta_{43} + \\
&amp;&amp;\beta_{43}\psi_{33} &amp; {\beta_{32}}^2 \psi_{33} + \psi_{44} \\
&amp;&amp;&amp;\\
\end{bmatrix}
\tag{3.10}
\end{equation}\]</span></p>
<p>Now that we have found the expression of <span class="math inline">\(\mathbf{\Sigma}_{\text{model}}\)</span> as a function of model parameters, this enables the estimation of the model parameters, by choosing the values for each model parameter in such a way, that the resulting model implied variances and covariances of <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{model}}\)</span> are as close as possible to the sample variances and covariances, <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{population}}\)</span>. A discrepancy function can be used to obtain parameter estimates, where an iterative procedure yields model parameters that keep the discrepancy between <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{population}}\)</span> and <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{model}}\)</span> to a minimum. In general, smaller values of discrepancy functions indicate better fit of the model to the data, and a value of zero indicates the fit is perfect, i.e., if the parameter estimates can perfectly reproduce the sample covariance matrix. Several discrepancy functions exist, but maximum likelihood estimation is most commonly applied. The resulting discrepancy value can be used for the assessment of overall goodness-of-fit using the so-called chi-square test of exact fit, where a significant chi-square value indicates a significant deviation between model and data (i.e., implying that <span class="math inline">\(\mathbf{\hat\Sigma}_{\text{population}} \ne \mathbf{\Sigma}_{\text{model}}\)</span>). See also Chapters 10 and 11, where the topics of Estimation and Evaluation of Model Fit are explained in more detail.</p>
<p>In our illustrative example of child anxiety, maximum likelihood estimation leads to the following model parameter estimates:</p>
<p><span class="math display">\[
\hat{\mathbf{B}}
=
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 \\
\hat\beta_{31} &amp; \hat\beta_{32} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \hat\beta_{43} &amp; 0
\end{bmatrix}
=
\begin{bmatrix}
0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 \\
0.19 &amp; 0.21 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0.07 &amp; 0
\end{bmatrix},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\hat{\boldsymbol{\Psi}} =
\begin{bmatrix}
\hat\psi_{11} &amp; \hat\psi_{21} &amp; 0 &amp; 0 \\
\hat\psi_{21} &amp; \hat\psi_{22} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \hat\psi_{33} &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; \hat\psi_{44}
\end{bmatrix}
=
\begin{bmatrix}
92.58 &amp; 53.36 &amp; 0 &amp; 0 \\
53.36 &amp; 194.32 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 114.16 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 6.88
\end{bmatrix}.
\]</span></p>
<p>Matrix <span class="math inline">\(\hat{\mathbf{B}}\)</span> contains the estimated regression coefficients <span class="math inline">\(\hat\beta_{31}\)</span>, <span class="math inline">\(\hat\beta_{32}\)</span> and <span class="math inline">\(\hat\beta_{43}\)</span>. The estimated regression of parental overcontrol on parent anxiety (<span class="math inline">\(\hat\beta_{31}\)</span>) is 0.19. As the parameter estimate is unstandardized, this indicates that with 1 point increase in parent anxiety there will be 0.19 point increase in parental overcontrol, holding constant all other variables in the model. The estimated effect of parent perfectionism on parental overcontrol (<span class="math inline">\(\hat\beta_{32}\)</span>) is 0.21, indicating that controlled for all other variables in the model, 1 point increase in parent perfectionism will lead to 0.21 point increase in parental overcontrol. Lastly, the estimated effect of parental overcontrol on child anxiety is 0.07, where 1 point increase in parental overcontrol will result in a 0.07 increase in child anxiety (controlled for all other variables in the model). All estimated effects between the variables are positive, and they support the hypothesis that parent anxiety and perfectionism increase parental overcontrol, which then increases child anxiety. However, the unstandardized parameter estimates do not give a direct interpretation of the size of the effects, and additional information is needed to judge the significance of the effects (see also Chapters 5 and 6).</p>
<p>Matrix <span class="math inline">\(\hat{\boldsymbol{\Psi}}\)</span> contains the estimated variances and covariance of the residual factors. Here, we can see that the variance of the residual factor of parent anxiety (<span class="math inline">\(\psi_{11}\)</span>) is 91.58 and the variance of the residual factor of parent perfectionism (<span class="math inline">\(\psi_{22}\)</span>) is 194.32. Remember that the variances of exogenous variables are not explained by any observed variables, and thus all variance in parent anxiety and parent perfectionism is represented by the variances of their corresponding residual factors. In addition, the covariance between parent anxiety and parent perfectionism is equal to the covariance between their corresponding residual factors (<span class="math inline">\(\psi_{21}\)</span>). The variance of the residual factor of overcontrol (<span class="math inline">\(\psi_{33}\)</span>) can be interpreted as the variance of overcontrol that is unexplained by the model. The same is true for the estimated variance of the residual factor of child anxiety (<span class="math inline">\(\psi_{44}\)</span>).</p>
<p>As the estimated model parameters of the psi-matrix provide information about the amount of variance that is unexplained by the model, we can also calculate the amount of variance that is explained by the model. The variance explained by the model is a result that is often reported in ordinary regression analysis as an indication of how well the model fits the data. Therefore, just as in regression analysis, it is informative to calculate the proportion of explained variance by using the estimated residual factor variance (i.e., the unexplained variance). In our example, the unexplained variance of the observed variable child anxiety is 6.88. We can calculate the proportion of explained variance of child anxiety using the following formula:</p>
<p><span class="math inline">\(R^2 = \frac{\text{unexplained, residual variance}}{\text{total variance}}\)</span>.</p>
<p>In our example the proportion of explained variance of child anxiety is 0.09, indicating that only 9<span class="math inline">\(\%\)</span> of the variance of child anxiety is explained by the path model that was specified (see also Chapter 5 on standardized parameters).</p>
</div>
<div id="path-analysis-using-lavaan" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Path analysis using lavaan<a href="path-models.html#path-analysis-using-lavaan" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="installing-lavaan-1" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Installing lavaan<a href="path-models.html#installing-lavaan-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The software that we will use to run our structural equation modeling analyses is lavaan (Rosseel, 2012), which is free open-source software that is available as a package in R. To install the lavaan package you can type the following command in the R console:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="path-models.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lavaan&quot;</span>, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>This will open a window where you have to select a CRAN mirror (select “[your country], [closest city]”) and will install the package lavaan, including all the packages that it is dependent upon. You only need to install the package once (on a specific computer), to add the package to the R library. Once the package is installed, you can activate all the functionalities that are available in the package by using the command:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="path-models.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code></pre></div>
<p>Every time you start R you need to use this command to activate the lavaan package into the current R workspace. Therefore, it is advisable to start every script with this command.</p>
</div>
<div id="fitting-a-path-model" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Fitting a path model<a href="path-models.html#fitting-a-path-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Script 3.1 fits the path model of Figure 3.2 to the covariance matrix that is given in Affrunti and Woodruff-Borden (2014). All commands will be explained below.</p>
<p><strong><em>Script 3.1</em></strong></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="path-models.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># names observed variables</span></span>
<span id="cb147-2"><a href="path-models.html#cb147-2" aria-hidden="true" tabindex="-1"></a>obsnames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;parent_anx&quot;</span>, <span class="st">&quot;perfect&quot;</span>, <span class="st">&quot;overcontrol&quot;</span>, <span class="st">&quot;child_anx&quot;</span>) </span>
<span id="cb147-3"><a href="path-models.html#cb147-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-4"><a href="path-models.html#cb147-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-5"><a href="path-models.html#cb147-5" aria-hidden="true" tabindex="-1"></a><span class="co"># covariance matrix as given by Affrunti and Woodruff-Borden (2014)</span></span>
<span id="cb147-6"><a href="path-models.html#cb147-6" aria-hidden="true" tabindex="-1"></a>AWcov <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">data =</span> <span class="fu">c</span>(<span class="fl">91.58</span>,  <span class="fl">53.36</span>,  <span class="fl">28.39</span>, <span class="fl">9.21</span>,</span>
<span id="cb147-7"><a href="path-models.html#cb147-7" aria-hidden="true" tabindex="-1"></a>                         <span class="fl">53.36</span>, <span class="fl">194.32</span>,  <span class="fl">50.90</span>, <span class="fl">4.98</span>,</span>
<span id="cb147-8"><a href="path-models.html#cb147-8" aria-hidden="true" tabindex="-1"></a>                         <span class="fl">28.39</span>,  <span class="fl">50.90</span>, <span class="fl">130.19</span>, <span class="fl">9.41</span>,</span>
<span id="cb147-9"><a href="path-models.html#cb147-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">9.21</span>,   <span class="fl">4.98</span>,   <span class="fl">9.41</span>, <span class="fl">7.56</span>),</span>
<span id="cb147-10"><a href="path-models.html#cb147-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">nrow =</span> <span class="dv">4</span>,</span>
<span id="cb147-11"><a href="path-models.html#cb147-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ncol =</span> <span class="dv">4</span>,</span>
<span id="cb147-12"><a href="path-models.html#cb147-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">dimnames =</span> <span class="fu">list</span>(obsnames,obsnames))</span>
<span id="cb147-13"><a href="path-models.html#cb147-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-14"><a href="path-models.html#cb147-14" aria-hidden="true" tabindex="-1"></a><span class="co"># specify the path model</span></span>
<span id="cb147-15"><a href="path-models.html#cb147-15" aria-hidden="true" tabindex="-1"></a>AWmodel <span class="ot">&lt;-</span> <span class="st">&#39;# regression equations</span></span>
<span id="cb147-16"><a href="path-models.html#cb147-16" aria-hidden="true" tabindex="-1"></a><span class="st">            overcontrol ~ b31*parent_anx + b32*perfect</span></span>
<span id="cb147-17"><a href="path-models.html#cb147-17" aria-hidden="true" tabindex="-1"></a><span class="st">            child_anx ~ b43*overcontrol</span></span>
<span id="cb147-18"><a href="path-models.html#cb147-18" aria-hidden="true" tabindex="-1"></a><span class="st">            # (residual) variance</span></span>
<span id="cb147-19"><a href="path-models.html#cb147-19" aria-hidden="true" tabindex="-1"></a><span class="st">            parent_anx ~~ p11*parent_anx</span></span>
<span id="cb147-20"><a href="path-models.html#cb147-20" aria-hidden="true" tabindex="-1"></a><span class="st">            perfect ~~ p22*perfect</span></span>
<span id="cb147-21"><a href="path-models.html#cb147-21" aria-hidden="true" tabindex="-1"></a><span class="st">            overcontrol ~~ p33*overcontrol</span></span>
<span id="cb147-22"><a href="path-models.html#cb147-22" aria-hidden="true" tabindex="-1"></a><span class="st">            child_anx ~~ p44*child_anx</span></span>
<span id="cb147-23"><a href="path-models.html#cb147-23" aria-hidden="true" tabindex="-1"></a><span class="st">            # covariance exogenous variables</span></span>
<span id="cb147-24"><a href="path-models.html#cb147-24" aria-hidden="true" tabindex="-1"></a><span class="st">            parent_anx ~~ p21*perfect</span></span>
<span id="cb147-25"><a href="path-models.html#cb147-25" aria-hidden="true" tabindex="-1"></a><span class="st">            &#39;</span></span>
<span id="cb147-26"><a href="path-models.html#cb147-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-27"><a href="path-models.html#cb147-27" aria-hidden="true" tabindex="-1"></a><span class="co"># build the model</span></span>
<span id="cb147-28"><a href="path-models.html#cb147-28" aria-hidden="true" tabindex="-1"></a>AWmodelOut <span class="ot">&lt;-</span> <span class="fu">lavaan</span>( <span class="at">model =</span> AWmodel, </span>
<span id="cb147-29"><a href="path-models.html#cb147-29" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sample.cov =</span> AWcov, <span class="at">sample.nobs =</span> <span class="dv">77</span>, </span>
<span id="cb147-30"><a href="path-models.html#cb147-30" aria-hidden="true" tabindex="-1"></a>                       <span class="at">likelihood =</span> <span class="st">&quot;wishart&quot;</span>, <span class="at">fixed.x =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>We start by defining the observed covariance matrix and the names of the associated observed variables. It is required to provide these names with the input matrix. First we created the object <code>obsnames</code> that contains the names of the variables. Note that the order of the variables corresponds to the labels <span class="math inline">\(\mathrm{y}_1\)</span> to <span class="math inline">\(\mathrm{y}_4\)</span> in Figure 3.2.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="path-models.html#cb148-1" aria-hidden="true" tabindex="-1"></a>obsnames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;parent_anx&quot;</span>, <span class="st">&quot;perfect&quot;</span>, <span class="st">&quot;overcontrol&quot;</span>, <span class="st">&quot;child_anx&quot;</span>) </span></code></pre></div>
<p>The names are given as a list with two elements, one vector of row names and one vector of column names. As a covariance matrix is a symmetric matrix, row and column names are the same, and we can use the command <code>list(obsnames, obsnames)</code> to provide the labels for the observed covariance matrix.</p>
<p>The observed covariance matrix is stored in the object <code>AWcov</code>, by creating a matrix with the values of the elements, number of rows, number of columns, and the name vectors of the two dimensions.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="path-models.html#cb149-1" aria-hidden="true" tabindex="-1"></a>AWcov <span class="ot">=</span> <span class="fu">matrix</span>(...)</span></code></pre></div>
<p>To check whether you successfully specified the observed covariance matrix, check the results by typing <code>AWcov</code> in the R console. And check, for example, whether the matrix is indeed symmetrical by typing <code>AWcov == t(AWcov)</code> or <code>isSymmetric(AWcov)</code>.</p>
<p>The next step is to specify the model that has to be fitted to the observed data. We create the object <code>AWmodel</code> where the model specifications are given, encapsulated by single quotes. We need to specify all free parameters that need to be estimated: regression coefficients and (residual) variances and covariances. The structural part of the model is specified using regression equations:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="path-models.html#cb150-1" aria-hidden="true" tabindex="-1"></a>AWmodel <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb150-2"><a href="path-models.html#cb150-2" aria-hidden="true" tabindex="-1"></a><span class="st">            # regression equations</span></span>
<span id="cb150-3"><a href="path-models.html#cb150-3" aria-hidden="true" tabindex="-1"></a><span class="st">            overcontrol ~ b31*parent_anx + b32*perfect</span></span>
<span id="cb150-4"><a href="path-models.html#cb150-4" aria-hidden="true" tabindex="-1"></a><span class="st">            child_anx ~ b43*overcontrol </span></span></code></pre></div>
<p>The tilde sign, “~”, is the regression operator. On the left hand of this operator we have the dependent variable, and on the right hand side of this operator we have the independent variables, separated by the “+” operator. The regression coefficients are named after their position in the <span class="math inline">\(\mathbf{B}\)</span> matrix. For example, the regression of overcontrol on parent anxiety is labeled with “<code>b31</code>”, which corresponds to the position of the estimate of the regression coefficient (<span class="math inline">\(\beta_{31}\)</span>) in the <span class="math inline">\(\mathbf{B}\)</span> matrix. As such, the names “<code>b31</code>”, “<code>b32</code>”, “<code>b43</code>” are chosen to represent <span class="math inline">\(\beta_{31}\)</span>, <span class="math inline">\(\beta_{32}\)</span>, and<span class="math inline">\(\beta_{43}\)</span>.</p>
<p>The residual terms are not explicitly included in the formulas. These formulas therefore only specify the structural part of the model.</p>
<p>The (residual) variances are specified using double tilde’s (“<span class="math inline">\(\sim \sim\)</span>”), where the same variable name is given both left and right of this operator. Covariances are specified similarly. The estimates of the (co)variances can be named by providing a label before the variable name that is to the right from the “<span class="math inline">\(\sim \sim\)</span>” operator. Here, we used the names “<code>p11</code>” to “<code>p44</code>” and “<code>p21</code>” to refer to the position of the parameter estimates in the <span class="math inline">\(\boldsymbol{\Psi}\)</span> matrix.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="path-models.html#cb151-1" aria-hidden="true" tabindex="-1"></a>            <span class="co"># (residual) variance</span></span>
<span id="cb151-2"><a href="path-models.html#cb151-2" aria-hidden="true" tabindex="-1"></a>            parent_anx <span class="sc">~</span><span class="er">~</span> p11<span class="sc">*</span>parent_anx</span>
<span id="cb151-3"><a href="path-models.html#cb151-3" aria-hidden="true" tabindex="-1"></a>            perfect <span class="sc">~</span><span class="er">~</span> p22<span class="sc">*</span>perfect</span>
<span id="cb151-4"><a href="path-models.html#cb151-4" aria-hidden="true" tabindex="-1"></a>            overcontrol <span class="sc">~</span><span class="er">~</span> p33<span class="sc">*</span>overcontrol</span>
<span id="cb151-5"><a href="path-models.html#cb151-5" aria-hidden="true" tabindex="-1"></a>            child_anx <span class="sc">~</span><span class="er">~</span> p44<span class="sc">*</span>child_anx</span>
<span id="cb151-6"><a href="path-models.html#cb151-6" aria-hidden="true" tabindex="-1"></a>            <span class="co"># covariance exogenous variables</span></span>
<span id="cb151-7"><a href="path-models.html#cb151-7" aria-hidden="true" tabindex="-1"></a>            parent_anx <span class="sc">~</span><span class="er">~</span> p21<span class="sc">*</span>perfect</span>
<span id="cb151-8"><a href="path-models.html#cb151-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">&#39;</span></span></code></pre></div>
<p>When all separate elements of the model are created, we can fit (“run”) the model using the <code>lavaan()</code> function and storing the output in <code>AWmodelOut</code>:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="path-models.html#cb152-1" aria-hidden="true" tabindex="-1"></a>AWmodelOut <span class="ot">&lt;-</span> <span class="fu">lavaan</span>( <span class="at">model =</span> AWmodel, </span>
<span id="cb152-2"><a href="path-models.html#cb152-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sample.cov =</span> AWcov, <span class="at">sample.nobs =</span> <span class="dv">77</span>, </span>
<span id="cb152-3"><a href="path-models.html#cb152-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">likelihood =</span> <span class="st">&quot;wishart&quot;</span>, <span class="at">fixed.x =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>The <code>lavaan()</code> function takes as arguments the specified model (<code>model = AWmodel</code>), the specified covariance matrix (<code>sample.cov = AWcov</code>), and the total number of observations (<code>sample.nobs = 77</code>). The final two arguments are used to turn off two default settings of lavaan. That is, we use Wishart likelihood (<code>likelihood = "wishart"</code>) because we are only analyzing covariance structure (when we add mean structure later in the semester, we will use “<code>normal</code>” likelihood). We also specify that we want to freely estimate (<code>fixed.x = FALSE</code>) rather than fix the (co)variances of the exogenous variables to their sample values.</p>
<p>The output is stored in <code>AWmodelOut</code>, and we can inspect the result using the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="path-models.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(AWmodelOut)</span></code></pre></div>
<p>This will show you some fit results of the model and give you the parameter estimates and their associated standard errors. The model has 2 degrees of freedom, and the chi-square value is 7.333. The summary of the output is given below:</p>
<pre><code>## lavaan 0.6-12 ended normally after 28 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         8
## 
##   Number of observations                            77
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 7.333
##   Degrees of freedom                                 2
##   P-value (Chi-square)                           0.026
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   overcontrol ~                                       
##     parnt_nx (b31)    0.187    0.140    1.341    0.180
##     perfect  (b32)    0.210    0.096    2.194    0.028
##   child_anx ~                                         
##     ovrcntrl (b43)    0.072    0.026    2.741    0.006
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   parent_anx ~~                                       
##     perfect  (p21)   53.360   16.481    3.238    0.001
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     parnt_nx (p11)   91.580   14.856    6.164    0.000
##     perfect  (p22)  194.320   31.523    6.164    0.000
##    .ovrcntrl (p33)  114.157   18.519    6.164    0.000
##    .child_nx (p44)    6.880    1.116    6.164    0.000</code></pre>
<p>Here we see the result for the regression coefficients <span class="math inline">\(\beta_{31}\)</span>, <span class="math inline">\(\beta_{32}\)</span>, and <span class="math inline">\(\beta_{43}\)</span>. lavaan also provides the associated standard error of the estimate (0.140, for <span class="math inline">\(\beta_{31}\)</span>). This gives an indication of the precision of the parameter estimate and can be used to judge whether the parameter estimate differs significantly from zero (see also [Chapter 5][05-IndirectEffects]).</p>
<p>Especially when parameters are labeled, lavaan will have to shorten some of the longer variable names (only in the printed output, not internally!), so that the output conforms to a certain format. You may also notice that some variances are preceded by a period (.). This indicates that it is a residual variance for an endogenous variable, rather than a variance for an exogenous variable. If you run models with residual correlations between endogenous variables, those residual covariances will also use the (.) prefix.</p>
<p>You can also request to see <span class="math inline">\(R^2\)</span> for each endogenous variable:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="path-models.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(AWmodelOut, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-12 ended normally after 28 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         8
## 
##   Number of observations                            77
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 7.333
##   Degrees of freedom                                 2
##   P-value (Chi-square)                           0.026
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   overcontrol ~                                       
##     parnt_nx (b31)    0.187    0.140    1.341    0.180
##     perfect  (b32)    0.210    0.096    2.194    0.028
##   child_anx ~                                         
##     ovrcntrl (b43)    0.072    0.026    2.741    0.006
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   parent_anx ~~                                       
##     perfect  (p21)   53.360   16.481    3.238    0.001
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     parnt_nx (p11)   91.580   14.856    6.164    0.000
##     perfect  (p22)  194.320   31.523    6.164    0.000
##    .ovrcntrl (p33)  114.157   18.519    6.164    0.000
##    .child_nx (p44)    6.880    1.116    6.164    0.000
## 
## R-Square:
##                    Estimate
##     overcontrol       0.123
##     child_anx         0.090</code></pre>
</div>
<div id="syntax-shortcuts" class="section level3 hasAnchor" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Syntax shortcuts<a href="path-models.html#syntax-shortcuts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Script 3.1 specifies every single nonzero parameter depicted in the path model of Figure 3.2. In larger models, this can become quite cumbersome, increase the chance of making an error, and make the model syntax more difficult to read (e.g., to find mistakes). Some parameters can be specified automatically in the <code>lavaan()</code> call. For example, setting the option <code>auto.var = TRUE</code> will tell lavaan to freely estimate all (residual) variances of variables included in the model syntax, and the option <code>fixed.x = FALSE</code> already tells lavaan to freely estimate covariances among exogenous variables. Thus, adding these options to the <code>lavaan()</code> call means that the model syntax requires only the specification of regression parameters, which is quite easy to read:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="path-models.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="do">## shorter model specification</span></span>
<span id="cb157-2"><a href="path-models.html#cb157-2" aria-hidden="true" tabindex="-1"></a>AWmodel <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb157-3"><a href="path-models.html#cb157-3" aria-hidden="true" tabindex="-1"></a><span class="st">            # regression equations</span></span>
<span id="cb157-4"><a href="path-models.html#cb157-4" aria-hidden="true" tabindex="-1"></a><span class="st">            overcontrol ~ b31*parent_anx + b32*perfect</span></span>
<span id="cb157-5"><a href="path-models.html#cb157-5" aria-hidden="true" tabindex="-1"></a><span class="st">            child_anx ~ b43*overcontrol</span></span>
<span id="cb157-6"><a href="path-models.html#cb157-6" aria-hidden="true" tabindex="-1"></a><span class="st">            &#39;</span></span>
<span id="cb157-7"><a href="path-models.html#cb157-7" aria-hidden="true" tabindex="-1"></a><span class="do">## free all (residual) variances using auto.var = TRUE</span></span>
<span id="cb157-8"><a href="path-models.html#cb157-8" aria-hidden="true" tabindex="-1"></a>AWmodelOut <span class="ot">&lt;-</span> <span class="fu">lavaan</span>( <span class="at">model =</span> AWmodel, <span class="at">auto.var =</span> <span class="cn">TRUE</span>,</span>
<span id="cb157-9"><a href="path-models.html#cb157-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sample.cov =</span> AWcov, <span class="at">sample.nobs =</span> <span class="dv">77</span>, </span>
<span id="cb157-10"><a href="path-models.html#cb157-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">likelihood =</span> <span class="st">&quot;wishart&quot;</span>, <span class="at">fixed.x =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>In fact, the <code>auto.var = TRUE</code> option is set by default in lavaan’s shortcut function, <code>sem()</code>, which sets several other default options that are typically desired in a path analysis (or structural regression among latent variables, which you will learn about later).</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="path-models.html#cb158-1" aria-hidden="true" tabindex="-1"></a>AWmodelOut <span class="ot">&lt;-</span> <span class="fu">sem</span>( <span class="at">model =</span> AWmodel,</span>
<span id="cb158-2"><a href="path-models.html#cb158-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sample.cov =</span> AWcov, <span class="at">sample.nobs =</span> <span class="dv">77</span>, </span>
<span id="cb158-3"><a href="path-models.html#cb158-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">likelihood =</span> <span class="st">&quot;wishart&quot;</span>, <span class="at">fixed.x =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<div id="extracting-results-from-lavaan-output-in-matrix-form" class="section level3 hasAnchor" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> Extracting results from lavaan output in matrix form<a href="path-models.html#extracting-results-from-lavaan-output-in-matrix-form" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To be able to inspect the parameter estimates of a path model in matrix form (namely the <span class="math inline">\(\mathbf{B}\)</span> and <span class="math inline">\(\boldsymbol{\Psi}\)</span> matrices), you can use the <code>lavInspect()</code> function, which can be used to extract many kinds of information about the fitted lavaan model (see a complete list on the help page: <code>?lavInspect</code>).</p>
<p>The <code>lavInspect()</code> function takes two arguments: (1) the lavaan “object” (in this case, <code>AWmodelOut</code>) and (2) a character string naming what specific information you want to inspect (in this case, the estimated coefficients: “<code>coef</code>”). SEM involves more than just the <span class="math inline">\(\mathbf{B}\)</span> and <span class="math inline">\(\boldsymbol{\Psi}\)</span> matrices, and the output will always include them even if they are empty (e.g., full of zeros, or an identity matrix). The following code can be used to store the <span class="math inline">\(\mathbf{B}\)</span> and <span class="math inline">\(\boldsymbol{\Psi}\)</span> matrices in the objects “<code>BETA</code>” and “<code>PSI</code>” to control what is displayed.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="path-models.html#cb159-1" aria-hidden="true" tabindex="-1"></a>Estimates <span class="ot">&lt;-</span> <span class="fu">lavInspect</span>(AWmodelOut, <span class="st">&quot;est&quot;</span>)</span>
<span id="cb159-2"><a href="path-models.html#cb159-2" aria-hidden="true" tabindex="-1"></a>BETA <span class="ot">&lt;-</span> Estimates<span class="sc">$</span>beta[obsnames, obsnames] </span>
<span id="cb159-3"><a href="path-models.html#cb159-3" aria-hidden="true" tabindex="-1"></a>PSI <span class="ot">&lt;-</span> Estimates<span class="sc">$</span>psi[obsnames, obsnames] </span></code></pre></div>
<p>The resulting <code>BETA</code> and <code>PSI</code> matrices are shown below. Because lavaan ignores the order of the variables in the input covariance matrix, its matrices correspond to variables in the order that they appeared in the model syntax. The order is arbitrary, but to make them easier to read (e.g., to compare this output to the matrices described in the previous sections of this chapter), the above syntax used the square-bracket operators to specify that the order of [rows, columns] should be the same order as our input matrix.</p>
<pre><code>## [1] &quot;BETA&quot;</code></pre>
<pre><code>##             parent_anx  perfect overcontrol child_anx
## parent_anx   0.0000000 0.000000  0.00000000         0
## perfect      0.0000000 0.000000  0.00000000         0
## overcontrol  0.1873575 0.210491  0.00000000         0
## child_anx    0.0000000 0.000000  0.07227898         0</code></pre>
<pre><code>## [1] &quot;PSI&quot;</code></pre>
<pre><code>##             parent_anx perfect overcontrol child_anx
## parent_anx       91.58   53.36      0.0000  0.000000
## perfect          53.36  194.32      0.0000  0.000000
## overcontrol       0.00    0.00    114.1569  0.000000
## child_anx         0.00    0.00      0.0000  6.879855</code></pre>
<p>Here, we can see that the variance of the residual factor of parent anxiety (<span class="math inline">\(\psi_{11}\)</span>) is 91.580 and the variance of the residual factor of parent perfectionism (<span class="math inline">\(\psi_{22}\)</span>) is 194.320.</p>
</div>
</div>
<div id="references-1" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> References<a href="path-models.html#references-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Rosseel, Y. (2012). lavaan: An R package for structural equation modeling. <em>Journal of Statistical Software, 48</em>(2), 1-36.</p>
</div>
<div id="appendix-3" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Appendix I. Derivations of equation 3.08 and 3.09<a href="path-models.html#appendix-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Derivation of Equation 3.08</strong></p>
<p><span class="math inline">\(\mathbf{y} = \mathbf{B} \mathbf{y} + \boldsymbol{\zeta} \Leftrightarrow\)</span></p>
<p><span class="math inline">\(\mathbf{y} - \mathbf{B} \mathbf{y} = \boldsymbol{\zeta} \Leftrightarrow\)</span></p>
<p><span class="math inline">\(\mathbf{I} \mathbf{y} - \mathbf{B} \mathbf{y} = \boldsymbol{\zeta} \Leftrightarrow\)</span></p>
<p><span class="math inline">\((\mathbf{I} - \mathbf{B}) \mathbf{y} = \boldsymbol{\zeta} \Leftrightarrow\)</span></p>
<p>(premultiply both sides by <span class="math inline">\((\mathbf{I} - \mathbf{B})^{-1}\)</span></p>
<p><span class="math inline">\((\mathbf{I} - \mathbf{B})^{-1} (\mathbf{I} - \mathbf{B}) \mathbf{y} = (\mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\zeta} \Leftrightarrow\)</span></p>
<p><span class="math inline">\(\mathbf{y} = (\mathbf{I} - \mathbf{B})^{-1} \zeta\)</span></p>
<p><strong>Derivation of Equation 3.09</strong></p>
<p><span class="math inline">\(\mathbf{\Sigma} = \mathrm{COV}(\mathbf{y},\mathbf{y}) \Leftrightarrow\)</span></p>
<p>(substitute Equation 3.08)</p>
<p><span class="math inline">\(\mathbf{\Sigma} = \mathrm{COV}( ( \mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\zeta}, (\mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\zeta}) \Leftrightarrow\)</span></p>
<p><span class="math inline">\(\mathbf{\Sigma} = ( \mathbf{I} - \mathbf{B})^{-1} \mathrm{COV}(\boldsymbol{\zeta}, \boldsymbol{\zeta}) ( \mathbf{I} - \mathbf{B}) ^{-1\mathrm{T}} \Leftrightarrow\)</span></p>
<p>(variances and covariances of <span class="math inline">\(\boldsymbol{\zeta}\)</span> are denoted <span class="math inline">\(\boldsymbol{\Psi}\)</span>)</p>
<p><span class="math inline">\(\mathbf{\Sigma} = ( \mathbf{I} - \mathbf{B})^{-1} \boldsymbol{\Psi} ( \mathbf{I} - \mathbf{B})^{-1\mathrm{T}}\)</span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="using-lavaan-to-run-regression-and-anova-as-a-sem.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="standard-errors-and-confidence-intervals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
