<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Using lavaan to Run Regression and ANOVA as a SEM | A lavaan Compendium for Structural Equation Modeling in Educational Research</title>
  <meta name="description" content="2 Using lavaan to Run Regression and ANOVA as a SEM | A lavaan Compendium for Structural Equation Modeling in Educational Research" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Using lavaan to Run Regression and ANOVA as a SEM | A lavaan Compendium for Structural Equation Modeling in Educational Research" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="TDJorgensen/SEM-in-Ed-compendium" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Using lavaan to Run Regression and ANOVA as a SEM | A lavaan Compendium for Structural Equation Modeling in Educational Research" />
  
  
  

<meta name="author" content="Suzanne Jak and Terrence D. Jorgensen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch1.html"/>
<link rel="next" href="ch3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Regression as Mean- and Covariance-Structure Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch1.html"><a href="ch1.html#what-are-mean-and-covariance-structures"><i class="fa fa-check"></i><b>1.1</b> What Are Mean and Covariance <em>Structures</em>?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ch1.html"><a href="ch1.html#ch1-1-1"><i class="fa fa-check"></i><b>1.1.1</b> Types of Data Used in SEM</a></li>
<li class="chapter" data-level="1.1.2" data-path="ch1.html"><a href="ch1.html#interpreting-covariance"><i class="fa fa-check"></i><b>1.1.2</b> Interpreting Covariance</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch1.html"><a href="ch1.html#importing-data-for-sem"><i class="fa fa-check"></i><b>1.2</b> Importing Data for SEM</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ch1.html"><a href="ch1.html#installing-lavaan"><i class="fa fa-check"></i><b>1.2.1</b> Installing <code>lavaan</code></a></li>
<li class="chapter" data-level="1.2.2" data-path="ch1.html"><a href="ch1.html#importing-raw-data"><i class="fa fa-check"></i><b>1.2.2</b> Importing Raw Data</a></li>
<li class="chapter" data-level="1.2.3" data-path="ch1.html"><a href="ch1.html#calculate-summary-statistics-from-raw-data"><i class="fa fa-check"></i><b>1.2.3</b> Calculate Summary Statistics from Raw Data</a></li>
<li class="chapter" data-level="1.2.4" data-path="ch1.html"><a href="ch1.html#importing-summary-data"><i class="fa fa-check"></i><b>1.2.4</b> Importing Summary Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="ch1.html"><a href="ch1.html#regression-using-matrix-algebra"><i class="fa fa-check"></i><b>1.3</b> Regression Using Matrix Algebra</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ch1.html"><a href="ch1.html#ch1-3-1"><i class="fa fa-check"></i><b>1.3.1</b> Linear Regression Models</a></li>
<li class="chapter" data-level="1.3.2" data-path="ch1.html"><a href="ch1.html#intercepts-and-means"><i class="fa fa-check"></i><b>1.3.2</b> Intercepts and Means</a></li>
<li class="chapter" data-level="1.3.3" data-path="ch1.html"><a href="ch1.html#categorical-predictors"><i class="fa fa-check"></i><b>1.3.3</b> Categorical Predictors</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="ch1.html"><a href="ch1.html#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>2</b> Using <code>lavaan</code> to Run Regression and ANOVA as a SEM</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch2.html"><a href="ch2.html#prepare-data-and-workspace"><i class="fa fa-check"></i><b>2.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch2.html"><a href="ch2.html#import-example-data"><i class="fa fa-check"></i><b>2.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch2.html"><a href="ch2.html#ch2-1-2"><i class="fa fa-check"></i><b>2.1.2</b> <code>lavaan</code> Syntax</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ch2.html"><a href="ch2.html#comparing-2-group-means-in-glm-and-sem"><i class="fa fa-check"></i><b>2.2</b> Comparing 2 Group Means in GLM and SEM</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ch2.html"><a href="ch2.html#the-glm-approach"><i class="fa fa-check"></i><b>2.2.1</b> The GLM Approach</a></li>
<li class="chapter" data-level="2.2.2" data-path="ch2.html"><a href="ch2.html#the-sem-approach-single-group-sem"><i class="fa fa-check"></i><b>2.2.2</b> The SEM Approach (single-group SEM)</a></li>
<li class="chapter" data-level="2.2.3" data-path="ch2.html"><a href="ch2.html#multigroup-sem-approach"><i class="fa fa-check"></i><b>2.2.3</b> Multigroup SEM Approach</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch2.html"><a href="ch2.html#fit-an-sem-to-summary-statistics"><i class="fa fa-check"></i><b>2.3</b> Fit an SEM to Summary Statistics</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="ch2.html"><a href="ch2.html#advantages-of-analyzing-summary-statistics"><i class="fa fa-check"></i><b>2.3.1</b> Advantages of Analyzing Summary Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ch2.html"><a href="ch2.html#moderation-in-sem"><i class="fa fa-check"></i><b>2.4</b> Moderation in SEM</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="ch2.html"><a href="ch2.html#moderation-by-groups-using-mg-sem"><i class="fa fa-check"></i><b>2.4.1</b> Moderation by Groups Using MG-SEM</a></li>
<li class="chapter" data-level="2.4.2" data-path="ch2.html"><a href="ch2.html#the-emmeans-package"><i class="fa fa-check"></i><b>2.4.2</b> The <code>emmeans</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="ch2.html"><a href="ch2.html#summary-1"><i class="fa fa-check"></i><b>2.5</b> Summary</a></li>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#references-1"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>3</b> Path Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch3.html"><a href="ch3.html#illustrative-example"><i class="fa fa-check"></i><b>3.1</b> Illustrative example</a></li>
<li class="chapter" data-level="3.2" data-path="ch3.html"><a href="ch3.html#conceptual-explanation"><i class="fa fa-check"></i><b>3.2</b> Conceptual explanation</a></li>
<li class="chapter" data-level="3.3" data-path="ch3.html"><a href="ch3.html#matrix-explanation"><i class="fa fa-check"></i><b>3.3</b> Matrix explanation</a></li>
<li class="chapter" data-level="3.4" data-path="ch3.html"><a href="ch3.html#path-analysis-using-lavaan"><i class="fa fa-check"></i><b>3.4</b> Path analysis using lavaan</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="ch3.html"><a href="ch3.html#installing-lavaan-1"><i class="fa fa-check"></i><b>3.4.1</b> Installing lavaan</a></li>
<li class="chapter" data-level="3.4.2" data-path="ch3.html"><a href="ch3.html#fitting-a-path-model"><i class="fa fa-check"></i><b>3.4.2</b> Fitting a path model</a></li>
<li class="chapter" data-level="3.4.3" data-path="ch3.html"><a href="ch3.html#syntax-shortcuts"><i class="fa fa-check"></i><b>3.4.3</b> Syntax shortcuts</a></li>
<li class="chapter" data-level="3.4.4" data-path="ch3.html"><a href="ch3.html#extracting-results-from-lavaan-output-in-matrix-form"><i class="fa fa-check"></i><b>3.4.4</b> Extracting results from lavaan output in matrix form</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#references-2"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#appendix"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#derivations-of-equation-refeq3-08"><i class="fa fa-check"></i>Derivations of Equation @ref(eq:3-08)</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#derivations-of-equation-refeq3-09"><i class="fa fa-check"></i>Derivations of Equation @ref(eq:3-09)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4.html"><a href="ch4.html"><i class="fa fa-check"></i><b>4</b> Standard Errors and Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch4.html"><a href="ch4.html#standard-errors"><i class="fa fa-check"></i><b>4.1</b> Standard Errors</a></li>
<li class="chapter" data-level="4.2" data-path="ch4.html"><a href="ch4.html#confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="ch4.html"><a href="ch4.html#likelihood-based-confidence-intervals"><i class="fa fa-check"></i><b>4.2.1</b> Likelihood-based confidence intervals</a></li>
<li class="chapter" data-level="4.2.2" data-path="ch4.html"><a href="ch4.html#bootstrapped-confidence-intervals"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrapped confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ch4.html"><a href="ch4.html#obtaining-standard-errors-and-confidence-intervals-in-lavaan"><i class="fa fa-check"></i><b>4.3</b> Obtaining standard errors and confidence intervals in <code>lavaan</code></a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#references-3"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5.html"><a href="ch5.html"><i class="fa fa-check"></i><b>5</b> Direct, Indirect, and Total Effects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch5.html"><a href="ch5.html#testing-significance-of-indirect-effects"><i class="fa fa-check"></i><b>5.1</b> Testing significance of indirect effects</a></li>
<li class="chapter" data-level="5.2" data-path="ch5.html"><a href="ch5.html#higher-order-indirect-effects"><i class="fa fa-check"></i><b>5.2</b> Higher order indirect effects</a></li>
<li class="chapter" data-level="5.3" data-path="ch5.html"><a href="ch5.html#using-matrix-algebra-to-calculate-total-total-indirect-and-specific-indirect-effects"><i class="fa fa-check"></i><b>5.3</b> Using matrix algebra to calculate total, total indirect and specific indirect effects</a></li>
<li class="chapter" data-level="5.4" data-path="ch5.html"><a href="ch5.html#calculating-total-total-indirect-and-specific-indirect-effects-using-lavaan-output"><i class="fa fa-check"></i><b>5.4</b> Calculating total, total indirect and specific indirect effects using lavaan output</a></li>
<li class="chapter" data-level="5.5" data-path="ch5.html"><a href="ch5.html#calculating-specific-indirect-effects-in-lavaan"><i class="fa fa-check"></i><b>5.5</b> Calculating specific indirect effects in lavaan</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6.html"><a href="ch6.html"><i class="fa fa-check"></i><b>6</b> Calculating Standardized Parameter Estimates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch6.html"><a href="ch6.html#standardized-regression-coefficients"><i class="fa fa-check"></i><b>6.1</b> Standardized regression coefficients</a></li>
<li class="chapter" data-level="6.2" data-path="ch6.html"><a href="ch6.html#standardized-residual-factor-variances-and-covariances"><i class="fa fa-check"></i><b>6.2</b> Standardized residual factor variances and covariances</a></li>
<li class="chapter" data-level="6.3" data-path="ch6.html"><a href="ch6.html#calculating-standardized-coefficients-in-r-using-lavaan-results"><i class="fa fa-check"></i><b>6.3</b> Calculating standardized coefficients in R using lavaan results</a>
<ul>
<li class="chapter" data-level="" data-path="ch6.html"><a href="ch6.html#script-6.1"><i class="fa fa-check"></i>Script 6.1</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ch6.html"><a href="ch6.html#request-standardized-output-with-lavaan"><i class="fa fa-check"></i><b>6.4</b> Request standardized output with lavaan</a></li>
<li class="chapter" data-level="6.5" data-path="ch6.html"><a href="ch6.html#standardizing-indirect-and-total-effects"><i class="fa fa-check"></i><b>6.5</b> Standardizing indirect and total effects</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch7.html"><a href="ch7.html"><i class="fa fa-check"></i><b>7</b> Identification</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch7.html"><a href="ch7.html#assessment-of-identification-using-the-elements-of-mathbfsigma_textpopulation-and-mathbfsigma_textmodel"><i class="fa fa-check"></i><b>7.1</b> Assessment of identification using the elements of <span class="math inline">\(\mathbf\Sigma_{\text{population}}\)</span> and <span class="math inline">\(\mathbf\Sigma_{\text{model}}\)</span></a></li>
<li class="chapter" data-level="7.2" data-path="ch7.html"><a href="ch7.html#assessing-identification-through-heuristics"><i class="fa fa-check"></i><b>7.2</b> Assessing identification through heuristics</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ch7.html"><a href="ch7.html#the-recursive-rule"><i class="fa fa-check"></i><b>7.2.1</b> The recursive rule</a></li>
<li class="chapter" data-level="7.2.2" data-path="ch7.html"><a href="ch7.html#the-order-condition"><i class="fa fa-check"></i><b>7.2.2</b> The order condition</a></li>
<li class="chapter" data-level="7.2.3" data-path="ch7.html"><a href="ch7.html#the-rank-condition"><i class="fa fa-check"></i><b>7.2.3</b> The rank condition</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ch7.html"><a href="ch7.html#assessment-of-empirical-model-identification-using-lavaan"><i class="fa fa-check"></i><b>7.3</b> Assessment of empirical model identification using <code>lavaan</code></a>
<ul>
<li class="chapter" data-level="" data-path="ch7.html"><a href="ch7.html#script-7.1"><i class="fa fa-check"></i>Script 7.1</a></li>
<li class="chapter" data-level="" data-path="ch7.html"><a href="ch7.html#script-7.2"><i class="fa fa-check"></i>Script 7.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch7.html"><a href="ch7.html#appendix-1"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="ch7.html"><a href="ch7.html#algebraic-assessment-of-identification-using-elements-of-mathbfsigma_textpopulation-and-mathbfsigma_textmodel"><i class="fa fa-check"></i>Algebraic assessment of identification using elements of <span class="math inline">\(\mathbf\Sigma_{\text{population}}\)</span> and <span class="math inline">\(\mathbf\Sigma_{\text{model}}\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch8.html"><a href="ch8.html"><i class="fa fa-check"></i><b>8</b> Autoregression</a>
<ul>
<li class="chapter" data-level="" data-path="ch8.html"><a href="ch8.html#script-8.1"><i class="fa fa-check"></i>Script 8.1</a></li>
<li class="chapter" data-level="8.1" data-path="ch8.html"><a href="ch8.html#autoregression-models-with-predictors"><i class="fa fa-check"></i><b>8.1</b> Autoregression models with predictors</a>
<ul>
<li class="chapter" data-level="" data-path="ch8.html"><a href="ch8.html#script-8.2"><i class="fa fa-check"></i>Script 8.2</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="ch8.html"><a href="ch8.html#cross-lagged-panel-models"><i class="fa fa-check"></i><b>8.2</b> Cross-lagged panel models</a></li>
<li class="chapter" data-level="" data-path="ch8.html"><a href="ch8.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9.html"><a href="ch9.html"><i class="fa fa-check"></i><b>9</b> Model Specification and Model Identification</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch9.html"><a href="ch9.html#from-theory-to-model"><i class="fa fa-check"></i><b>9.1</b> From theory to model</a></li>
<li class="chapter" data-level="9.2" data-path="ch9.html"><a href="ch9.html#model-parsimony"><i class="fa fa-check"></i><b>9.2</b> Model parsimony</a></li>
<li class="chapter" data-level="9.3" data-path="ch9.html"><a href="ch9.html#a-priori-model-specification"><i class="fa fa-check"></i><b>9.3</b> A priori model specification</a></li>
<li class="chapter" data-level="9.4" data-path="ch9.html"><a href="ch9.html#post-hoc-model-modification"><i class="fa fa-check"></i><b>9.4</b> Post hoc model modification</a></li>
<li class="chapter" data-level="9.5" data-path="ch9.html"><a href="ch9.html#backward-and-forward-specification-searches"><i class="fa fa-check"></i><b>9.5</b> Backward and forward specification searches</a></li>
<li class="chapter" data-level="9.6" data-path="ch9.html"><a href="ch9.html#correlation-residuals"><i class="fa fa-check"></i><b>9.6</b> Correlation residuals</a></li>
<li class="chapter" data-level="9.7" data-path="ch9.html"><a href="ch9.html#modification-indices"><i class="fa fa-check"></i><b>9.7</b> Modification indices</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="ch9.html"><a href="ch9.html#script-9.0"><i class="fa fa-check"></i><b>9.7.1</b> Script 9.0</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="ch9.html"><a href="ch9.html#cross-validation"><i class="fa fa-check"></i><b>9.8</b> Cross-validation</a></li>
<li class="chapter" data-level="9.9" data-path="ch9.html"><a href="ch9.html#calculating-correlation-residuals-in-lavaan"><i class="fa fa-check"></i><b>9.9</b> Calculating correlation residuals in <code>lavaan</code></a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="ch9.html"><a href="ch9.html#requesting-mis-and-sepcs-in-lavaan"><i class="fa fa-check"></i><b>9.9.1</b> Requesting MIs and (S)EPCs in <code>lavaan</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch9.html"><a href="ch9.html#references-5"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch10.html"><a href="ch10.html"><i class="fa fa-check"></i><b>10</b> Estimation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch10.html"><a href="ch10.html#improper-solutions"><i class="fa fa-check"></i><b>10.1</b> Improper Solutions</a></li>
<li class="chapter" data-level="10.2" data-path="ch10.html"><a href="ch10.html#specifying-starting-values-in-lavaan"><i class="fa fa-check"></i><b>10.2</b> Specifying starting values in <code>lavaan</code></a></li>
<li class="chapter" data-level="10.3" data-path="ch10.html"><a href="ch10.html#alternative-estimators"><i class="fa fa-check"></i><b>10.3</b> Alternative estimators</a></li>
<li class="chapter" data-level="10.4" data-path="ch10.html"><a href="ch10.html#robust-estimators"><i class="fa fa-check"></i><b>10.4</b> Robust estimators</a></li>
<li class="chapter" data-level="10.5" data-path="ch10.html"><a href="ch10.html#requesting-alternative-and-robust-estimators-in-lavaan"><i class="fa fa-check"></i><b>10.5</b> Requesting alternative and robust estimators in lavaan</a></li>
<li class="chapter" data-level="10.6" data-path="ch10.html"><a href="ch10.html#ch10-6"><i class="fa fa-check"></i><b>10.6</b> Alternative calculation of the ML discrepancy function when analysing raw data</a></li>
<li class="chapter" data-level="10.7" data-path="ch10.html"><a href="ch10.html#ch10-7"><i class="fa fa-check"></i><b>10.7</b> Using FIML to analyse raw data with missing values in lavaan</a></li>
<li class="chapter" data-level="" data-path="ch10.html"><a href="ch10.html#references-6"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch11.html"><a href="ch11.html"><i class="fa fa-check"></i><b>11</b> Measures of Model Fit</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch11.html"><a href="ch11.html#the-chi-squared-test-of-exact-fit"><i class="fa fa-check"></i><b>11.1</b> The chi-squared test of exact fit</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="ch11.html"><a href="ch11.html#alternative-basis-for-calculating-the-test-statistic-when-analysing-raw-data"><i class="fa fa-check"></i><b>11.1.1</b> Alternative basis for calculating the test statistic when analysing raw data</a></li>
<li class="chapter" data-level="11.1.2" data-path="ch11.html"><a href="ch11.html#testing-exact-fit-vs.-describing-the-degree-of-approximate-fit"><i class="fa fa-check"></i><b>11.1.2</b> Testing exact fit vs. describing the degree of approximate fit</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="ch11.html"><a href="ch11.html#root-mean-square-error-of-approximation-rmsea"><i class="fa fa-check"></i><b>11.2</b> Root Mean Square Error of Approximation (RMSEA)</a></li>
<li class="chapter" data-level="11.3" data-path="ch11.html"><a href="ch11.html#other-descriptive-fit-indices"><i class="fa fa-check"></i><b>11.3</b> Other descriptive fit indices</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="ch11.html"><a href="ch11.html#the-tuckerlewis-index-tli-and-the-comparative-fit-index-cfi"><i class="fa fa-check"></i><b>11.3.1</b> The Tucker–Lewis Index (TLI) and the Comparative Fit Index (CFI)</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch11.html"><a href="ch11.html#the-root-mean-square-residual-rmr-and-standardized-rmr-srmr"><i class="fa fa-check"></i><b>11.3.2</b> The Root Mean Square Residual (RMR) and Standardized RMR (SRMR)</a></li>
<li class="chapter" data-level="11.3.3" data-path="ch11.html"><a href="ch11.html#information-criteria"><i class="fa fa-check"></i><b>11.3.3</b> Information Criteria</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch11.html"><a href="ch11.html#a-note-on-using-available-fit-indices"><i class="fa fa-check"></i><b>11.4</b> A note on using available fit indices</a></li>
<li class="chapter" data-level="11.5" data-path="ch11.html"><a href="ch11.html#difference-in-model-fit"><i class="fa fa-check"></i><b>11.5</b> Difference in model fit</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="ch11.html"><a href="ch11.html#deltachi2-as-a-likelihood-ratio-test"><i class="fa fa-check"></i><b>11.5.1</b> <span class="math inline">\(\Delta\chi^2\)</span> as a likelihood ratio test</a></li>
<li class="chapter" data-level="11.5.2" data-path="ch11.html"><a href="ch11.html#describing-differences-in-fit"><i class="fa fa-check"></i><b>11.5.2</b> Describing differences in fit</a></li>
<li class="chapter" data-level="11.5.3" data-path="ch11.html"><a href="ch11.html#testing-differences-in-fit-between-non-nested-models"><i class="fa fa-check"></i><b>11.5.3</b> Testing differences in fit between non-nested models</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="ch11.html"><a href="ch11.html#request-fit-measures-in-lavaan"><i class="fa fa-check"></i><b>11.6</b> Request fit measures in <code>lavaan</code></a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="ch11.html"><a href="ch11.html#compare-fit-of-lavaan-models"><i class="fa fa-check"></i><b>11.6.1</b> Compare fit of lavaan models</a></li>
<li class="chapter" data-level="11.6.2" data-path="ch11.html"><a href="ch11.html#fit-measures-in-lavaan-when-adjusting-for-non-normal-data"><i class="fa fa-check"></i><b>11.6.2</b> Fit measures in <code>lavaan</code> when adjusting for non-normal data</a></li>
<li class="chapter" data-level="11.6.3" data-path="ch11.html"><a href="ch11.html#test-statistic-adjusted-for-small-sample-size"><i class="fa fa-check"></i><b>11.6.3</b> Test statistic adjusted for small sample size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch11.html"><a href="ch11.html#references-7"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch12.html"><a href="ch12.html"><i class="fa fa-check"></i><b>12</b> Path Analysis with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch12.html"><a href="ch12.html#prepare-data-and-workspace-1"><i class="fa fa-check"></i><b>12.1</b> Prepare Data and Workspace</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ch12.html"><a href="ch12.html#import-example-data-1"><i class="fa fa-check"></i><b>12.1.1</b> Import Example Data</a></li>
<li class="chapter" data-level="12.1.2" data-path="ch12.html"><a href="ch12.html#summarize-data"><i class="fa fa-check"></i><b>12.1.2</b> Summarize Data</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ch12.html"><a href="ch12.html#regression-models-for-binary-variables"><i class="fa fa-check"></i><b>12.2</b> Regression Models for Binary Variables</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ch12.html"><a href="ch12.html#fit-a-logistic-regression-model"><i class="fa fa-check"></i><b>12.2.1</b> Fit a Logistic Regression Model</a></li>
<li class="chapter" data-level="12.2.2" data-path="ch12.html"><a href="ch12.html#fit-a-probit-regression-model"><i class="fa fa-check"></i><b>12.2.2</b> Fit a Probit Regression Model</a></li>
<li class="chapter" data-level="12.2.3" data-path="ch12.html"><a href="ch12.html#compare-models"><i class="fa fa-check"></i><b>12.2.3</b> Compare Models</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ch12.html"><a href="ch12.html#latent-response-variable"><i class="fa fa-check"></i><b>12.3</b> Latent Response Variable</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ch12.html"><a href="ch12.html#ordinal-outcomes"><i class="fa fa-check"></i><b>12.3.1</b> Ordinal Outcomes</a></li>
<li class="chapter" data-level="12.3.2" data-path="ch12.html"><a href="ch12.html#estimating-thresholds"><i class="fa fa-check"></i><b>12.3.2</b> Estimating Thresholds</a></li>
<li class="chapter" data-level="12.3.3" data-path="ch12.html"><a href="ch12.html#estimating-polychoric-correlations"><i class="fa fa-check"></i><b>12.3.3</b> Estimating Polychoric Correlations</a></li>
<li class="chapter" data-level="12.3.4" data-path="ch12.html"><a href="ch12.html#estimating-an-sem-with-estimated-input"><i class="fa fa-check"></i><b>12.3.4</b> Estimating an SEM with Estimated Input</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ch12.html"><a href="ch12.html#mediation-model-with-categorical-outcomes"><i class="fa fa-check"></i><b>12.4</b> Mediation Model with Categorical Outcomes</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ch12.html"><a href="ch12.html#estimate-mediation-models"><i class="fa fa-check"></i><b>12.4.1</b> Estimate Mediation Models</a></li>
<li class="chapter" data-level="12.4.2" data-path="ch12.html"><a href="ch12.html#interpreting-coefficients"><i class="fa fa-check"></i><b>12.4.2</b> Interpreting Coefficients</a></li>
<li class="chapter" data-level="12.4.3" data-path="ch12.html"><a href="ch12.html#delta-vs.-theta-parameterizations"><i class="fa fa-check"></i><b>12.4.3</b> Delta vs. Theta Parameterizations</a></li>
<li class="chapter" data-level="12.4.4" data-path="ch12.html"><a href="ch12.html#decomposing-total-effects"><i class="fa fa-check"></i><b>12.4.4</b> Decomposing Total Effects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch12.html"><a href="ch12.html#references-8"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ch13.html"><a href="ch13.html"><i class="fa fa-check"></i><b>13</b> Fitting Path Models with Multilevel Data</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch13.html"><a href="ch13.html#intraclass-correlation"><i class="fa fa-check"></i><b>13.1</b> Intraclass correlation</a></li>
<li class="chapter" data-level="13.2" data-path="ch13.html"><a href="ch13.html#multilevel-structure-as-a-nuisance-correcting-for-the-dependency"><i class="fa fa-check"></i><b>13.2</b> Multilevel structure as a nuisance: Correcting for the dependency</a></li>
<li class="chapter" data-level="13.3" data-path="ch13.html"><a href="ch13.html#two-level-path-models"><i class="fa fa-check"></i><b>13.3</b> Two-level path models</a></li>
<li class="chapter" data-level="13.4" data-path="ch13.html"><a href="ch13.html#obtaining-iccs-and-estimates-of-sigma_textw-and-sigma_textb"><i class="fa fa-check"></i><b>13.4</b> Obtaining ICCs, and estimates of <span class="math inline">\(\Sigma_\text{W}\)</span> and <span class="math inline">\(\Sigma_\text{B}\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ch13.html"><a href="ch13.html#script-13.1"><i class="fa fa-check"></i>Script 13.1</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="ch13.html"><a href="ch13.html#fitting-a-two-level-path-model"><i class="fa fa-check"></i><b>13.5</b> Fitting a two-level path model</a>
<ul>
<li class="chapter" data-level="" data-path="ch13.html"><a href="ch13.html#script-13.2"><i class="fa fa-check"></i>Script 13.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch13.html"><a href="ch13.html#references-9"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch14.html"><a href="ch14.html"><i class="fa fa-check"></i><b>14</b> Factor Models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch14.html"><a href="ch14.html#empirical-example-of-a-factor-model"><i class="fa fa-check"></i><b>14.1</b> Empirical example of a factor model</a></li>
<li class="chapter" data-level="14.2" data-path="ch14.html"><a href="ch14.html#conceptual-explanation-of-a-factor-model"><i class="fa fa-check"></i><b>14.2</b> Conceptual explanation of a factor model</a></li>
<li class="chapter" data-level="14.3" data-path="ch14.html"><a href="ch14.html#symbolic-explanation-of-a-factor-model"><i class="fa fa-check"></i><b>14.3</b> Symbolic explanation of a factor model</a></li>
<li class="chapter" data-level="14.4" data-path="ch14.html"><a href="ch14.html#identification-of-model-parameters-in-a-factor-model"><i class="fa fa-check"></i><b>14.4</b> Identification of model parameters in a factor model</a></li>
<li class="chapter" data-level="14.5" data-path="ch14.html"><a href="ch14.html#fitting-a-factor-model-using-lavaan"><i class="fa fa-check"></i><b>14.5</b> Fitting a factor model using lavaan</a>
<ul>
<li class="chapter" data-level="" data-path="ch14.html"><a href="ch14.html#script-14.1"><i class="fa fa-check"></i>Script 14.1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch14.html"><a href="ch14.html#references-10"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="ch14.html"><a href="ch14.html#appendix-2"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="ch14.html"><a href="ch14.html#derivations-of-equation-14.13"><i class="fa fa-check"></i>Derivations of Equation 14.13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch15.html"><a href="ch15.html"><i class="fa fa-check"></i><b>15</b> Standardized Parameter Estimates for the Factor Model</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ch15.html"><a href="ch15.html#standardized-factor-loadings"><i class="fa fa-check"></i><b>15.1</b> Standardized factor loadings</a></li>
<li class="chapter" data-level="15.2" data-path="ch15.html"><a href="ch15.html#standardized-common-factor-variances-and-covariances"><i class="fa fa-check"></i><b>15.2</b> Standardized common-factor variances and covariances</a></li>
<li class="chapter" data-level="15.3" data-path="ch15.html"><a href="ch15.html#standardized-unique-factor-variances-and-covariances"><i class="fa fa-check"></i><b>15.3</b> Standardized unique-factor variances and covariances</a></li>
<li class="chapter" data-level="15.4" data-path="ch15.html"><a href="ch15.html#structure-coefficients"><i class="fa fa-check"></i><b>15.4</b> Structure coefficients</a></li>
<li class="chapter" data-level="15.5" data-path="ch15.html"><a href="ch15.html#ch15-5"><i class="fa fa-check"></i><b>15.5</b> Calculating standardized coefficients in lavaan</a>
<ul>
<li class="chapter" data-level="" data-path="ch15.html"><a href="ch15.html#script-15.1"><i class="fa fa-check"></i>Script 15.1</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="ch15.html"><a href="ch15.html#request-standardized-output-with-lavaan-1"><i class="fa fa-check"></i><b>15.6</b> Request standardized output with lavaan</a></li>
<li class="chapter" data-level="" data-path="ch15.html"><a href="ch15.html#references-11"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ch16.html"><a href="ch16.html"><i class="fa fa-check"></i><b>16</b> The Empirical Check for Identification</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ch16.html"><a href="ch16.html#empirical-check-of-model-a"><i class="fa fa-check"></i><b>16.1</b> Empirical check of Model A</a>
<ul>
<li class="chapter" data-level="" data-path="ch16.html"><a href="ch16.html#script-16.1"><i class="fa fa-check"></i>Script 16.1</a></li>
<li class="chapter" data-level="" data-path="ch16.html"><a href="ch16.html#script-16.2"><i class="fa fa-check"></i>Script 16.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch16.html"><a href="ch16.html#references-12"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ch17.html"><a href="ch17.html"><i class="fa fa-check"></i><b>17</b> Second Order Factor Models</a>
<ul>
<li class="chapter" data-level="" data-path="ch17.html"><a href="ch17.html#script-17.1"><i class="fa fa-check"></i>Script 17.1</a></li>
<li class="chapter" data-level="" data-path="ch17.html"><a href="ch17.html#getting-the-parameter-estimates-in-matrix-form"><i class="fa fa-check"></i>Getting the parameter estimates in matrix form</a>
<ul>
<li class="chapter" data-level="" data-path="ch17.html"><a href="ch17.html#script-17.2"><i class="fa fa-check"></i>Script 17.2</a></li>
</ul></li>
<li class="chapter" data-level="17.1" data-path="ch17.html"><a href="ch17.html#standardized-parameter-estimates-for-the-higher-order-part-of-the-model"><i class="fa fa-check"></i><b>17.1</b> Standardized parameter estimates for the higher-order part of the model</a>
<ul>
<li class="chapter" data-level="" data-path="ch17.html"><a href="ch17.html#script-17.3"><i class="fa fa-check"></i>Script 17.3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ch18.html"><a href="ch18.html"><i class="fa fa-check"></i><b>18</b> Structural Regression Models</a>
<ul>
<li class="chapter" data-level="" data-path="ch18.html"><a href="ch18.html#script-18.1"><i class="fa fa-check"></i>Script 18.1</a></li>
<li class="chapter" data-level="" data-path="ch18.html"><a href="ch18.html#script-18.2"><i class="fa fa-check"></i>Script 18.2</a></li>
<li class="chapter" data-level="18.1" data-path="ch18.html"><a href="ch18.html#standardized-parameter-estimates-for-the-structural-part-of-the-model"><i class="fa fa-check"></i><b>18.1</b> Standardized parameter estimates for the structural part of the model</a>
<ul>
<li class="chapter" data-level="" data-path="ch18.html"><a href="ch18.html#script-18.3"><i class="fa fa-check"></i>Script 18.3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="ch19.html"><a href="ch19.html"><i class="fa fa-check"></i><b>19</b> Second-order Correlation Residuals</a></li>
<li class="chapter" data-level="20" data-path="ch20.html"><a href="ch20.html"><i class="fa fa-check"></i><b>20</b> Factors with single indicators</a>
<ul>
<li class="chapter" data-level="" data-path="ch20.html"><a href="ch20.html#script-20.1"><i class="fa fa-check"></i>Script 20.1</a></li>
<li class="chapter" data-level="" data-path="ch20.html"><a href="ch20.html#script-20.2"><i class="fa fa-check"></i>Script 20.2</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="ch21.html"><a href="ch21.html"><i class="fa fa-check"></i><b>21</b> Mean structures</a>
<ul>
<li class="chapter" data-level="21.1" data-path="ch21.html"><a href="ch21.html#mean-structure-of-a-factor-model"><i class="fa fa-check"></i><b>21.1</b> Mean structure of a factor model</a></li>
<li class="chapter" data-level="21.2" data-path="ch21.html"><a href="ch21.html#mean-structure-of-a-path-model"><i class="fa fa-check"></i><b>21.2</b> Mean structure of a path model</a></li>
<li class="chapter" data-level="21.3" data-path="ch21.html"><a href="ch21.html#mean-structure-of-a-factor-model-in-lavaan"><i class="fa fa-check"></i><b>21.3</b> Mean structure of a factor model in <code>lavaan</code></a>
<ul>
<li class="chapter" data-level="" data-path="ch21.html"><a href="ch21.html#script-21.1"><i class="fa fa-check"></i>Script 21.1</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="ch21.html"><a href="ch21.html#mean-structure-of-a-path-model-1"><i class="fa fa-check"></i><b>21.4</b> Mean structure of a path model</a></li>
<li class="chapter" data-level="" data-path="ch21.html"><a href="ch21.html#appendix-3"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="ch21.html"><a href="ch21.html#derivation-of-equation-21.20"><i class="fa fa-check"></i>Derivation of Equation 21.20</a></li>
<li class="chapter" data-level="" data-path="ch21.html"><a href="ch21.html#derivation-of-equation-21.27"><i class="fa fa-check"></i>Derivation of Equation 21.27</a></li>
<li class="chapter" data-level="" data-path="ch21.html"><a href="ch21.html#derivation-of-equation-21.28"><i class="fa fa-check"></i>Derivation of Equation 21.28</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="ch22.html"><a href="ch22.html"><i class="fa fa-check"></i><b>22</b> Multigroup Models</a>
<ul>
<li class="chapter" data-level="22.1" data-path="ch22.html"><a href="ch22.html#measurement-invariance"><i class="fa fa-check"></i><b>22.1</b> Measurement invariance</a>
<ul>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.1"><i class="fa fa-check"></i>Script 22.1</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="ch22.html"><a href="ch22.html#across-group-equality-constraints"><i class="fa fa-check"></i><b>22.2</b> Across group equality constraints</a>
<ul>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.2"><i class="fa fa-check"></i>Script 22.2</a></li>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.3"><i class="fa fa-check"></i>Script 22.3</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="ch22.html"><a href="ch22.html#standardized-estimates-for-a-multigroup-model"><i class="fa fa-check"></i><b>22.3</b> Standardized estimates for a multigroup model</a></li>
<li class="chapter" data-level="22.4" data-path="ch22.html"><a href="ch22.html#lavaan-shortcuts"><i class="fa fa-check"></i><b>22.4</b> <code>lavaan</code> shortcuts</a>
<ul>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.4"><i class="fa fa-check"></i>Script 22.4</a></li>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.5"><i class="fa fa-check"></i>Script 22.5</a></li>
<li class="chapter" data-level="" data-path="ch22.html"><a href="ch22.html#script-22.6"><i class="fa fa-check"></i>Script 22.6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="ch23.html"><a href="ch23.html"><i class="fa fa-check"></i><b>23</b> Calculating Mean Residuals</a>
<ul>
<li class="chapter" data-level="" data-path="ch23.html"><a href="ch23.html#script-23.1"><i class="fa fa-check"></i>Script 23.1</a></li>
<li class="chapter" data-level="" data-path="ch23.html"><a href="ch23.html#script-22.2-1"><i class="fa fa-check"></i>Script 22.2</a></li>
<li class="chapter" data-level="" data-path="ch23.html"><a href="ch23.html#script-23.3"><i class="fa fa-check"></i>Script 23.3</a></li>
<li class="chapter" data-level="" data-path="ch23.html"><a href="ch23.html#references-13"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="ch24.html"><a href="ch24.html"><i class="fa fa-check"></i><b>24</b> Modification Indices and EPC’s for Equality Constraints</a>
<ul>
<li class="chapter" data-level="24.1" data-path="ch24.html"><a href="ch24.html#modification-index-for-simultaneously-freeing-a-set-of-parameters"><i class="fa fa-check"></i><b>24.1</b> Modification index for simultaneously freeing a set of parameters</a>
<ul>
<li class="chapter" data-level="" data-path="ch24.html"><a href="ch24.html#script-24.1"><i class="fa fa-check"></i>Script 24.1</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="ch24.html"><a href="ch24.html#modification-indices-for-releasing-equality-constraints"><i class="fa fa-check"></i><b>24.2</b> Modification indices for releasing equality constraints</a>
<ul>
<li class="chapter" data-level="" data-path="ch24.html"><a href="ch24.html#script-24.3"><i class="fa fa-check"></i>Script 24.3</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="ch24.html"><a href="ch24.html#epc-interest"><i class="fa fa-check"></i><b>24.3</b> EPC-interest</a></li>
<li class="chapter" data-level="" data-path="ch24.html"><a href="ch24.html#references-14"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="ch25.html"><a href="ch25.html"><i class="fa fa-check"></i><b>25</b> MIMIC (and RFA) models</a>
<ul>
<li class="chapter" data-level="25.1" data-path="ch25.html"><a href="ch25.html#illustration-testing-uniform-bias-in-a-mimic-model"><i class="fa fa-check"></i><b>25.1</b> Illustration testing uniform bias in a MIMIC model</a></li>
<li class="chapter" data-level="25.2" data-path="ch25.html"><a href="ch25.html#evaluating-non-uniform-measurement-bias"><i class="fa fa-check"></i><b>25.2</b> Evaluating non-uniform measurement bias</a></li>
<li class="chapter" data-level="25.3" data-path="ch25.html"><a href="ch25.html#connection-with-measurement-invariance-testing-in-multigroup-models"><i class="fa fa-check"></i><b>25.3</b> Connection with measurement invariance testing in multigroup models</a></li>
<li class="chapter" data-level="25.4" data-path="ch25.html"><a href="ch25.html#rfa-models"><i class="fa fa-check"></i><b>25.4</b> RFA-models</a></li>
<li class="chapter" data-level="" data-path="ch25.html"><a href="ch25.html#references-15"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="ch26.html"><a href="ch26.html"><i class="fa fa-check"></i><b>26</b> Longitudinal Factor Analysis</a>
<ul>
<li class="chapter" data-level="26.1" data-path="ch26.html"><a href="ch26.html#step-1-a-longitudinal-factor-model-with-configural-invariance"><i class="fa fa-check"></i><b>26.1</b> Step 1: A longitudinal factor model with configural invariance</a>
<ul>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#script-26.1"><i class="fa fa-check"></i>Script 26.1</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="ch26.html"><a href="ch26.html#step-2-a-longitudinal-model-with-weak-factorial-invariance."><i class="fa fa-check"></i><b>26.2</b> Step 2: A longitudinal model with weak factorial invariance.</a>
<ul>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#script-26.2"><i class="fa fa-check"></i>Script 26.2</a></li>
</ul></li>
<li class="chapter" data-level="26.3" data-path="ch26.html"><a href="ch26.html#step-3-longitudinal-model-with-strong-factorial-invariance"><i class="fa fa-check"></i><b>26.3</b> Step 3: Longitudinal model with strong factorial invariance</a>
<ul>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#script-26.3"><i class="fa fa-check"></i>Script 26.3</a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="ch26.html"><a href="ch26.html#step-4-a-model-with-strict-factorial-invariance"><i class="fa fa-check"></i><b>26.4</b> Step 4: A model with strict factorial invariance</a>
<ul>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#script-26.4"><i class="fa fa-check"></i>Script 26.4</a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="ch26.html"><a href="ch26.html#standardized-estimates-for-a-longitudinal-factor-model-with-means"><i class="fa fa-check"></i><b>26.5</b> Standardized estimates for a (longitudinal) factor model with means</a>
<ul>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#script-26.5"><i class="fa fa-check"></i>Script 26.5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch26.html"><a href="ch26.html#references-16"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="ch27.html"><a href="ch27.html"><i class="fa fa-check"></i><b>27</b> Latent Growth Curve Models</a>
<ul>
<li class="chapter" data-level="27.1" data-path="ch27.html"><a href="ch27.html#prepare-data-and-workspace-2"><i class="fa fa-check"></i><b>27.1</b> Prepare Data and Workspace</a></li>
<li class="chapter" data-level="27.2" data-path="ch27.html"><a href="ch27.html#random-intercept-model"><i class="fa fa-check"></i><b>27.2</b> Random Intercept Model</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="ch27.html"><a href="ch27.html#specification-and-estimation"><i class="fa fa-check"></i><b>27.2.1</b> Specification and Estimation</a></li>
<li class="chapter" data-level="27.2.2" data-path="ch27.html"><a href="ch27.html#interpret-results"><i class="fa fa-check"></i><b>27.2.2</b> Interpret Results</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="ch27.html"><a href="ch27.html#linear-growth-model"><i class="fa fa-check"></i><b>27.3</b> Linear Growth Model</a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="ch27.html"><a href="ch27.html#model-fit-and-comparison"><i class="fa fa-check"></i><b>27.3.1</b> Model Fit and Comparison</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="ch27.html"><a href="ch27.html#unrestricted-growth-models"><i class="fa fa-check"></i><b>27.4</b> Unrestricted Growth Models</a>
<ul>
<li class="chapter" data-level="27.4.1" data-path="ch27.html"><a href="ch27.html#latent-basis-curve"><i class="fa fa-check"></i><b>27.4.1</b> Latent Basis Curve</a></li>
<li class="chapter" data-level="27.4.2" data-path="ch27.html"><a href="ch27.html#saturated-growth-model"><i class="fa fa-check"></i><b>27.4.2</b> Saturated Growth Model</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="ch27.html"><a href="ch27.html#explaining-growth-factors"><i class="fa fa-check"></i><b>27.5</b> Explaining Growth Factors</a>
<ul>
<li class="chapter" data-level="27.5.1" data-path="ch27.html"><a href="ch27.html#time-invariant-level-2-predictors"><i class="fa fa-check"></i><b>27.5.1</b> Time-Invariant (Level-2) Predictors</a></li>
<li class="chapter" data-level="27.5.2" data-path="ch27.html"><a href="ch27.html#time-varying-level-1-predictors"><i class="fa fa-check"></i><b>27.5.2</b> Time-Varying (Level-1) Predictors</a></li>
<li class="chapter" data-level="27.5.3" data-path="ch27.html"><a href="ch27.html#parallel-growth-curves"><i class="fa fa-check"></i><b>27.5.3</b> Parallel Growth Curves</a></li>
</ul></li>
<li class="chapter" data-level="27.6" data-path="ch27.html"><a href="ch27.html#latent-indicators-of-growth-factors"><i class="fa fa-check"></i><b>27.6</b> Latent Indicators of Growth Factors</a>
<ul>
<li class="chapter" data-level="27.6.1" data-path="ch27.html"><a href="ch27.html#common-factors"><i class="fa fa-check"></i><b>27.6.1</b> Common Factors</a></li>
<li class="chapter" data-level="27.6.2" data-path="ch27.html"><a href="ch27.html#discrete-indicators"><i class="fa fa-check"></i><b>27.6.2</b> Discrete Indicators</a></li>
</ul></li>
<li class="chapter" data-level="27.7" data-path="ch27.html"><a href="ch27.html#multigroup-growth-models"><i class="fa fa-check"></i><b>27.7</b> Multigroup Growth Models</a></li>
<li class="chapter" data-level="" data-path="ch27.html"><a href="ch27.html#references-17"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="ch28.html"><a href="ch28.html"><i class="fa fa-check"></i><b>28</b> Analysis of categorical outcomes</a>
<ul>
<li class="chapter" data-level="28.1" data-path="ch28.html"><a href="ch28.html#factor-analysis-using-categorical-indicators"><i class="fa fa-check"></i><b>28.1</b> Factor analysis using categorical indicators</a>
<ul>
<li class="chapter" data-level="" data-path="ch28.html"><a href="ch28.html#script-28.1"><i class="fa fa-check"></i>Script 28.1</a></li>
<li class="chapter" data-level="" data-path="ch28.html"><a href="ch28.html#script-28.2"><i class="fa fa-check"></i>Script 28.2</a></li>
<li class="chapter" data-level="" data-path="ch28.html"><a href="ch28.html#script-28.3"><i class="fa fa-check"></i>Script 28.3</a></li>
<li class="chapter" data-level="" data-path="ch28.html"><a href="ch28.html#script-28.4"><i class="fa fa-check"></i>Script 28.4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch28.html"><a href="ch28.html#references-and-further-reading"><i class="fa fa-check"></i>References and further reading</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="ch29.html"><a href="ch29.html"><i class="fa fa-check"></i><b>29</b> Fitting CFA models with multilevel data</a>
<ul>
<li class="chapter" data-level="29.1" data-path="ch29.html"><a href="ch29.html#intraclass-correlations-of-observed-variables"><i class="fa fa-check"></i><b>29.1</b> Intraclass correlations of observed variables</a>
<ul>
<li class="chapter" data-level="" data-path="ch29.html"><a href="ch29.html#script-29.1"><i class="fa fa-check"></i>Script 29.1</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="ch29.html"><a href="ch29.html#multilevel-structure-as-a-nuisance-correcting-for-the-dependency-1"><i class="fa fa-check"></i><b>29.2</b> Multilevel structure as a nuisance: Correcting for the dependency</a></li>
<li class="chapter" data-level="29.3" data-path="ch29.html"><a href="ch29.html#two-level-factor-models"><i class="fa fa-check"></i><b>29.3</b> Two-level factor models</a>
<ul>
<li class="chapter" data-level="" data-path="ch29.html"><a href="ch29.html#script-29.2"><i class="fa fa-check"></i>Script 29.2</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="ch29.html"><a href="ch29.html#intraclass-correlations-of-common-factors"><i class="fa fa-check"></i><b>29.4</b> Intraclass correlations of common factors</a></li>
<li class="chapter" data-level="29.5" data-path="ch29.html"><a href="ch29.html#climate-and-contextual-between-level-latent-variables"><i class="fa fa-check"></i><b>29.5</b> Climate and contextual between-level latent variables</a></li>
<li class="chapter" data-level="29.6" data-path="ch29.html"><a href="ch29.html#full-sem-with-multilevel-data"><i class="fa fa-check"></i><b>29.6</b> Full SEM with multilevel data</a></li>
<li class="chapter" data-level="" data-path="ch29.html"><a href="ch29.html#references-18"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A <code>lavaan</code> Compendium for Structural Equation Modeling in Educational Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch2" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Using <code>lavaan</code> to Run Regression and ANOVA as a SEM<a href="ch2.html#ch2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter prepares the reader to learn about structural equation modeling (SEM) by reviewing the fundamentals of ordinary least-squares (OLS) regression in the general(ized) linear modeling (GLM) framework. Some key take-home messages will reinforce what was discussed about <em>covariance structure analysis</em> in the previous chapter:</p>
<ul>
<li>Analyzing different data formats (raw vs. summary data) yields equivalent results (under conditions of normality and complete data).
<ul>
<li><strong>Recall</strong> from the previous chapter that maximum-likelihood estimation (MLE) in SEM chooses parameters that minimize discrepancies between observed and expected <em>summary statistics</em> rather than casewise observations.</li>
</ul></li>
<li>Grouping variables can be represented as dummy, effects, or contrast codes, but there are some advantages of stratifying results by group. This will be demonstrated using multigroup SEM and comparing results to the single-group approach.<br />
</li>
<li>Point estimates from SEM will match GLM because OLS estimates are ML estimates when the distributional assumptions are met.
<ul>
<li>independent, identically distributed (normal with homogeneous variance)</li>
</ul></li>
<li>However, the <em>SE</em>s are typically smaller under ML with SEM than under OLS with GLM.<br />
</li>
<li>Furthermore, different (but analogous) test statistics will be compared between GLM (<em>t</em> and <em>F</em> statistics) and SEM (<em>z</em> and <span class="math inline">\(\chi^2\)</span> statistics).</li>
<li>Model comparisons require fitting nested models to the same data, which in SEM means fitting them to the same summary statistics.</li>
</ul>
<!-- TODO: 
Frame the need to talk about MG-SEM because it allows for thinking more about CSA v. reproducing raw data 
-->
<div id="prepare-data-and-workspace" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Prepare Data and Workspace<a href="ch2.html#prepare-data-and-workspace" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="import-example-data" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Import Example Data<a href="ch2.html#import-example-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will use data from a tutorial published on the <a href="http://www.socialchangelab.net/uploads/9/8/7/7/98771854/moderated_mediation_example_write-up.pdf">Social Change Lab’s web site</a>.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="ch2.html#cb87-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> foreign<span class="sc">::</span><span class="fu">read.spss</span>(<span class="st">&quot;demoData/MODMED.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span>)[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>)]</span>
<span id="cb87-2"><a href="ch2.html#cb87-2" tabindex="-1"></a><span class="do">## print first and last 3 rows</span></span>
<span id="cb87-3"><a href="ch2.html#cb87-3" tabindex="-1"></a>dat[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">98</span><span class="sc">:</span><span class="dv">100</span>), ]</span></code></pre></div>
<pre><code>##     MOOD      NFC     POS      ATT
## 1     -1  3.07579  6.2500  18.5455
## 2     -1  2.59489 -5.0671 -16.9684
## 3     -1 -1.00952  0.9346  -5.9578
## 98     1  0.14496 -6.6079  -0.6811
## 99     1  0.28151 15.1838  30.5421
## 100    1 -0.06157 -6.0116  11.7879</code></pre>
<p>Recall from <a href="ch1.html#ch1">Chapter 1</a> that SEM can equivalently be fitted to summary statistics rather than raw data. This chapter will demonstrate this both approaches.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="ch2.html#cb89-1" tabindex="-1"></a><span class="do">## Save summary statistics</span></span>
<span id="cb89-2"><a href="ch2.html#cb89-2" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(dat)</span>
<span id="cb89-3"><a href="ch2.html#cb89-3" tabindex="-1"></a>S <span class="ot">&lt;-</span> <span class="fu">cov</span>(dat)</span>
<span id="cb89-4"><a href="ch2.html#cb89-4" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat)</span></code></pre></div>
<p>Also recall that it is possible to fit a “multigroup SEM” to obtain parameter estimates separately per group. This chapter will also demonstrate how to fit a multigroup SEM to raw data as well as to summary statistics. For the latter, we require group-specific summary statistics, which <a href="ch1.html#ch1">Chapter 1</a> discussed how to obtain. Here, we use slightly more efficient syntax to obtain lists of group-specific summary statistics, although the more sophisticated <code>sapply()</code> function makes the syntax less immediately intuitive to read.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="ch2.html#cb90-1" tabindex="-1"></a><span class="do">## Create factor from effects-coded conditions</span></span>
<span id="cb90-2"><a href="ch2.html#cb90-2" tabindex="-1"></a>dat<span class="sc">$</span>mood.f <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>MOOD, <span class="at">levels =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb90-3"><a href="ch2.html#cb90-3" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;neutral&quot;</span>,<span class="st">&quot;positive&quot;</span>))</span>
<span id="cb90-4"><a href="ch2.html#cb90-4" tabindex="-1"></a><span class="do">## Save lists of group-specific summary statistics</span></span>
<span id="cb90-5"><a href="ch2.html#cb90-5" tabindex="-1"></a>CC <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ATT&quot;</span>,<span class="st">&quot;NFC&quot;</span>,<span class="st">&quot;POS&quot;</span>)   <span class="co"># when group = &quot;mood.f&quot;</span></span>
<span id="cb90-6"><a href="ch2.html#cb90-6" tabindex="-1"></a>gM <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">&quot;neutral&quot;</span>,<span class="st">&quot;positive&quot;</span>), <span class="at">simplify =</span> <span class="cn">FALSE</span>, </span>
<span id="cb90-7"><a href="ch2.html#cb90-7" tabindex="-1"></a>             <span class="at">FUN =</span> <span class="cf">function</span>(g) <span class="fu">colMeans</span>(dat[dat<span class="sc">$</span>mood.f <span class="sc">==</span> g, CC]) )</span>
<span id="cb90-8"><a href="ch2.html#cb90-8" tabindex="-1"></a>gS <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">&quot;neutral&quot;</span>,<span class="st">&quot;positive&quot;</span>), <span class="at">simplify =</span> <span class="cn">FALSE</span>,</span>
<span id="cb90-9"><a href="ch2.html#cb90-9" tabindex="-1"></a>             <span class="at">FUN =</span> <span class="cf">function</span>(g) <span class="fu">cov</span>(     dat[dat<span class="sc">$</span>mood.f <span class="sc">==</span> g, CC]) )</span>
<span id="cb90-10"><a href="ch2.html#cb90-10" tabindex="-1"></a>gN <span class="ot">&lt;-</span> <span class="fu">table</span>(dat<span class="sc">$</span>mood.f)</span></code></pre></div>
</div>
<div id="ch2-1-2" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> <code>lavaan</code> Syntax<a href="ch2.html#ch2-1-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Notice from the section-header that <code>lavaan</code> should always be lower-case. It is a portmanteau of tent riable alysis, similar to alysis f riance (ANOVA).</p>
<p>Load <code>lavaan</code> into your workspace.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="ch2.html#cb91-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code></pre></div>
<p>The standard syntax for regression in R is a <code>formula</code> object. To regress <code>ATT</code>itude on <code>MOOD</code> condition, <code>N</code>eed <code>F</code>or <code>C</code>ognition (<code>NFC</code>), and <code>POS</code>itive thoughts:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="ch2.html#cb92-1" tabindex="-1"></a>ATT <span class="sc">~</span> MOOD <span class="sc">+</span> NFC <span class="sc">+</span> POS</span></code></pre></div>
<p>SEM is a multivariate modeling framework, so a <code>formula</code> object does not allow for sufficient complexity.</p>
<ul>
<li>There can be many outcome variables, each with its own formula (i.e., different predictors)
<ul>
<li>Multivariate GLMs (e.g., MANOVA) require the same predictors for all outcomes</li>
<li>e.g., <code>cbind(ATT, POS) ~ MOOD + NFC</code></li>
</ul></li>
<li>Outcomes can even predict other outcomes, which GLM does not allow
<ul>
<li>Another name for an SEM is a <em>simultaneous equations model</em>.</li>
</ul></li>
</ul>
<p>Later chapters will introduce additional complexity that <code>formula</code> objects do not allow for:</p>
<ul>
<li>Residual variances can be specified explicitly using a “double tilde” operator (<code>~~</code>), which allows specifying equality constraints on variance estimates.</li>
<li>There can be unobserved (latent) variables, which require a special operator (<code>=~</code>) to define in <code>lavaan</code> syntax.</li>
<li>Details about these and other operators can be found in the <strong>Details</strong> section of the <code>?model.syntax</code> help page, and the website also has a <a href="https://lavaan.ugent.be/tutorial/index.html">syntax tutorial</a> for various short topics. Details about syntax features we will use in this chapter are summarized in the table below.</li>
</ul>
<table>
<colgroup>
<col width="9%" />
<col width="41%" />
<col width="48%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><strong>Operator</strong></th>
<th align="left"><strong>Purpose</strong></th>
<th align="left"><strong>Example</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>~</code></td>
<td align="left">Estimate regression slope(s)</td>
<td align="left"><code>'outcome ~ predictor'</code></td>
</tr>
<tr class="even">
<td align="left"><code>~1</code></td>
<td align="left">Estimate intercept(s)</td>
<td align="left"><code>'outcome ~ 1'</code></td>
</tr>
<tr class="odd">
<td align="left"><code>value*</code></td>
<td align="left">Fix (number) or free (missing value) parameters</td>
<td align="left"><code>'posttest ~ 1*pretest + NA*x1'</code></td>
</tr>
<tr class="even">
<td align="left"><code>string*</code></td>
<td align="left">Label parameters</td>
<td align="left"><code>'y ~ myLabel*x'</code></td>
</tr>
<tr class="odd">
<td align="left"><code>+</code></td>
<td align="left">Additional parameters or operators</td>
<td align="left"><code>'y ~ NA*x1 + beta2*x2'</code></td>
</tr>
<tr class="even">
<td align="left"><code>c()</code></td>
<td align="left">Operators for multiple groups</td>
<td align="left"><code>'y ~ c(NA, 1)*x1 + c(beta1, beta2)*x2'</code></td>
</tr>
<tr class="odd">
<td align="left"><code>:=</code></td>
<td align="left">Define a function of parameters</td>
<td align="left"><code>'slopeRatio := beta1 / beta2'</code></td>
</tr>
</tbody>
</table>
<p><code>lavaan</code> requires collecting all of these model parameters in a <code>character</code> vector, even when there is only one outcome.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="ch2.html#cb93-1" tabindex="-1"></a><span class="st">&#39; ATT ~ MOOD + NFC + POS &#39;</span></span></code></pre></div>
<p>Note how the syntax above looks exactly like the <code>formula</code> we would pass to <code>lm()</code>, except that it is within quotation marks. <code>lavaan</code>’s model syntax is flexible enough that we can equivalently specify each parameter on a different line, which can be useful in larger models or to make <code>#comments</code> in syntax.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="ch2.html#cb94-1" tabindex="-1"></a><span class="st">&#39; ATT ~ 1     # intercept</span></span>
<span id="cb94-2"><a href="ch2.html#cb94-2" tabindex="-1"></a><span class="st">  ATT ~ MOOD  # slopes</span></span>
<span id="cb94-3"><a href="ch2.html#cb94-3" tabindex="-1"></a><span class="st">  ATT ~ NFC</span></span>
<span id="cb94-4"><a href="ch2.html#cb94-4" tabindex="-1"></a><span class="st">  ATT ~ POS &#39;</span></span></code></pre></div>
<p>Once we specify a model (typically saving the character string to an object), we can fit that model to the (raw or summary) data.
There are multiple model-fitting functions in the <code>lavaan</code> package:</p>
<ul>
<li><code>lavaan()</code> is the main “engine”, but expects that models are fully specified in complete detail</li>
<li><code>sem()</code> is a “wrapper” that calls <code>lavaan()</code> with some sensible defaults that apply to most SEMs (e.g., automatically estimating residual variances, automatically estimating covariances among predictors)</li>
<li><code>cfa()</code> is meant for fitting confirmatory factor analysis (CFA) models, discussed in a later chapter. <code>cfa()</code> and <code>sem()</code> actually behave identically (i.e., they call <code>lavaan()</code> with the same defaults)</li>
<li><code>growth()</code> is meant for very simple latent growth curve models, also discussed in a later chapter</li>
</ul>
<p>In this chapter, we will use the <code>sem()</code> function similar to the way we use the <code>lm()</code> function, including how we obtain results from <code>summary()</code>.</p>
</div>
</div>
<div id="comparing-2-group-means-in-glm-and-sem" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Comparing 2 Group Means in GLM and SEM<a href="ch2.html#comparing-2-group-means-in-glm-and-sem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section compares SEM with GLM in the simple case of comparing 2 group means.</p>
<div id="the-glm-approach" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> The GLM Approach<a href="ch2.html#the-glm-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that an independent-samples <em>t</em> test (assuming homoskedasticity across groups) is equivalent to testing the estimated slope of a dummy code in a simple regression model.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="ch2.html#cb95-1" tabindex="-1"></a><span class="fu">t.test</span>(ATT <span class="sc">~</span> mood.f, <span class="at">data =</span> dat, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  ATT by mood.f
## t = -4.3889, df = 98, p-value = 2.876e-05
## alternative hypothesis: true difference in means between group neutral and group positive is not equal to 0
## 95 percent confidence interval:
##  -19.670213  -7.420887
## sample estimates:
##  mean in group neutral mean in group positive 
##              -4.792052               8.753498</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="ch2.html#cb97-1" tabindex="-1"></a><span class="do">## as a regression model</span></span>
<span id="cb97-2"><a href="ch2.html#cb97-2" tabindex="-1"></a>mod.dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(ATT <span class="sc">~</span> mood.f, <span class="at">data =</span> dat)</span>
<span id="cb97-3"><a href="ch2.html#cb97-3" tabindex="-1"></a><span class="fu">summary</span>(mod.dummy) <span class="co"># compare t test for slope to t.test() output</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ATT ~ mood.f, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -52.818  -9.015   1.084  10.423  31.769 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -4.792      2.182  -2.196   0.0305 *  
## mood.fpositive   13.546      3.086   4.389 2.88e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.43 on 98 degrees of freedom
## Multiple R-squared:  0.1643, Adjusted R-squared:  0.1557 
## F-statistic: 19.26 on 1 and 98 DF,  p-value: 2.876e-05</code></pre>
<p>Recall also that the <em>F</em> test at the bottom of the <code>summary.lm()</code> output is an ANOVA comparing the fitted model to an intercept-only model.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="ch2.html#cb99-1" tabindex="-1"></a>mod.int <span class="ot">&lt;-</span> <span class="fu">lm</span>(ATT <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> dat)</span>
<span id="cb99-2"><a href="ch2.html#cb99-2" tabindex="-1"></a><span class="fu">anova</span>(mod.int, mod.dummy)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: ATT ~ 1
## Model 2: ATT ~ mood.f
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     99 27924                                  
## 2     98 23337  1      4587 19.263 2.876e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the case of an <em>F</em> test with 1-<em>df</em> in the numerator, the test result is equivalent to a squared <em>t</em> statistic with the same <em>df</em> as the denominator of the <em>F</em> test.</p>
<p><span class="math display">\[ F_{1, df} = t^2_{df} \]</span></p>
<p>This makes it simpler to test individual parameters (single-<em>df</em> tests) without fitting a separate model that fixes the single parameter to 0 (by dropping it from the GLM). We will see the same relationship between statistics available from SEM.</p>
</div>
<div id="the-sem-approach-single-group-sem" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> The SEM Approach (single-group SEM)<a href="ch2.html#the-sem-approach-single-group-sem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Fitting the same simple-regression model as an SEM is relatively simple: Replace the <code>lm()</code> function with the <code>sem()</code> function, and embed the formula in quotation marks. However, <code>lavaan</code> will not automatically create dummy codes for <code>factor</code> variables as <code>lm()</code> will, so we must first make a dummy code for positive mood.</p>
<ul>
<li>Recall: <code>mod.dummy &lt;- lm(ATT ~ mood.f, data = dat)</code></li>
</ul>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="ch2.html#cb101-1" tabindex="-1"></a>dat<span class="sc">$</span>pos.mood <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dat<span class="sc">$</span>mood.f <span class="sc">==</span> <span class="st">&quot;positive&quot;</span>, <span class="at">yes =</span> <span class="dv">1</span>, <span class="at">no =</span> <span class="dv">0</span>)</span>
<span id="cb101-2"><a href="ch2.html#cb101-2" tabindex="-1"></a><span class="do">## as an SEM</span></span>
<span id="cb101-3"><a href="ch2.html#cb101-3" tabindex="-1"></a>fit.dummy <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ pos.mood &#39;</span>, <span class="at">data =</span> dat)</span>
<span id="cb101-4"><a href="ch2.html#cb101-4" tabindex="-1"></a><span class="fu">summary</span>(fit.dummy) <span class="co"># compare SE and z test for slope to lm() result</span></span></code></pre></div>
<pre><code>## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   ATT ~                                               
##     pos.mood         13.546    3.055    4.433    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .ATT             233.369   33.003    7.071    0.000</code></pre>
<p>The SEM’s ML estimate of the group mean difference is 13.546, which is identical to the <code>lm()</code> result. However, we will focus on some differences.</p>
<div id="why-does-sem-have-a-smaller-se" class="section level4 hasAnchor" number="2.2.2.1">
<h4><span class="header-section-number">2.2.2.1</span> Why Does SEM Have a Smaller <em>SE</em><a href="ch2.html#why-does-sem-have-a-smaller-se" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The SEM has a smaller <em>SE</em> estimate, which in turn makes its Wald <em>z</em> test statistic larger than the <em>t</em> statistic. Note that both statistics are calculated identically as the ratio of the estimate to its <em>SE</em> (i.e., a <a href="https://en.wikipedia.org/wiki/Wald_test#Test_on_a_single_parameter">Wald test</a>). More generally, any <span class="math inline">\(H_0\)</span> can be tested about the parameter <span class="math inline">\(\beta\)</span>, where the null-hypothesized value is represented by <span class="math inline">\(\beta_0\)</span>:</p>
<p><span class="math display">\[t \text{ or } z = \frac{\hat{\beta} - \beta_0}{SE}\]</span></p>
<p>The <code>summary()</code> methods simply set each <span class="math inline">\(\beta_0=0\)</span> by default, so testing a different <span class="math inline">\(H_0\)</span> requires calculating the test and its <em>p</em> value manually.</p>
<p>So, if they are calculated the same way, why are they <em>z</em> instead of <em>t</em> tests? SEM estimators are based on <em>asymptotic</em> (infinite-<em>N</em>) theory, which means MLE assumes <span class="math inline">\(N\)</span> is sufficiently large that the sample covariance matrix <span class="math inline">\(S\)</span> is approximately equivalent to the population covariance matrix <span class="math inline">\(\Sigma\)</span>. The asymptotic assumption yields more power, but inflated Type I error rates when sample size is low (relative to number of estimated parameters). So it would be more robust to interpret the Wald <em>z</em> statistic as a <em>t</em> statistic in small samples; unfortunately, there is no straight-forward way to derive an appropriate <em>df</em> parameter for the <em>t</em> distribution.</p>
</div>
<div id="why-do-residual-variance-estimates-differ" class="section level4 hasAnchor" number="2.2.2.2">
<h4><span class="header-section-number">2.2.2.2</span> Why Do Residual Variance Estimates Differ?<a href="ch2.html#why-do-residual-variance-estimates-differ" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The “Residual standard error” in the lower <code>summary.lm()</code> output is the <em>SD</em> of the residuals, so its square is the estimated variance of the residuals (238.131). The SEM estimate is smaller (233.369), which also follows from using asymptotic theory. The formula for a variance divides the sum of squared residuals by <em>N</em> when the population mean is known, but GLM divides by the model’s <em>df</em> (in this case, <span class="math inline">\(N-2\)</span>). If we rescaled the GLM estimate by <span class="math inline">\(\frac{N-2}{N}\)</span>, we would obtain the same asymptotic estimate that MLE provides from our SEM result:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="ch2.html#cb103-1" tabindex="-1"></a><span class="fu">sigma</span>(mod.dummy)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (N <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">/</span> N</span></code></pre></div>
<pre><code>## [1] 233.3687</code></pre>
<p>The same rescaling by <span class="math inline">\(\frac{N-2}{N}\)</span> is responsible for the smaller <em>SE</em>s in the SEM result, although it is not the <em>SE</em> itself that is rescaled (see previous section).</p>
</div>
<div id="where-is-the-intercept-in-sem" class="section level4 hasAnchor" number="2.2.2.3">
<h4><span class="header-section-number">2.2.2.3</span> Where Is the Intercept in SEM?<a href="ch2.html#where-is-the-intercept-in-sem" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The SEM result had no intercept. This is because we did not specify one in our syntax. Whereas a <code>formula</code> object for <code>lm()</code> automatically adds an intercept (implicitly regressing on a constant: <code>ATT ~ 1 + mood.f</code>), the <code>sem()</code> function will not do so in simple models like this. The previous chapter (section <a href="ch1.html#ch1-3-1">Linear Regression Models</a>) explains why we can omit mean-structure parameters when data are mean-centered (i.e., intercept would be 0 anyway). But SEM doesn’t actually require us mean-center the data to obtain such results, which is convenient when we have no hypotheses about the intercepts.</p>
<p>To add intercepts to the model, we can simply add the argument <code>meanstructure=TRUE</code>, which would be set automatically whenever we explicitly add any intercept parameter to the model syntax.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="ch2.html#cb105-1" tabindex="-1"></a>fit.dummy <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ 1 + pos.mood &#39;</span>, <span class="at">data =</span> dat)</span>
<span id="cb105-2"><a href="ch2.html#cb105-2" tabindex="-1"></a><span class="fu">parameterEstimates</span>(fit.dummy, <span class="at">output =</span> <span class="st">&quot;pretty&quot;</span>, <span class="at">ci =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   ATT ~                                               
##     pos.mood         13.546    3.055    4.433    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .ATT              -4.792    2.160   -2.218    0.027
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .ATT             233.369   33.003    7.071    0.000</code></pre>
<p>As with the estimated slope, the estimated intercept is identical between GLM and SEM, but SEM has a smaller <em>SE</em>, resulting in a larger Wald <em>z</em> statistic.</p>
</div>
<div id="model-comparison-approach-analogous-to-f-test" class="section level4 hasAnchor" number="2.2.2.4">
<h4><span class="header-section-number">2.2.2.4</span> Model-Comparison Approach (Analogous to <em>F</em> Test)<a href="ch2.html#model-comparison-approach-analogous-to-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Comparing nested GLMs provides an <span class="math inline">\(F\)</span> statistic. Analogously, comparing nested SEMs provides a <span class="math inline">\(\chi^2\)</span> statistic, which is also follows from using asymptotic theory. As the denominator <em>df</em> of the <em>F</em> statistic approaches <span class="math inline">\(\infty\)</span>, the <em>F</em> statistic (multiplied by its numerator <em>df</em>) more closely follows a <span class="math inline">\(\chi^2\)</span> distribution with the same (numerator) <em>df</em>.</p>
<p>However, an important caveat follows from the criterion used to find the “best” parameters in SEM. Whereas GLM minimizes <em>casewise</em> residuals, SEM minimizes residuals of <em>summary statistics</em> (review <a href="ch1.html#ch1-1-1">Types of Data Used in SEM</a> for details). In a GLM, it does not matter if we remove a predictor <span class="math inline">\(x\)</span> from a model because the only data we try to reproduce is the outcome <span class="math inline">\(y\)</span> (i.e., both nested models are fitted to the same data). But in SEM, we are fitting models to reproduce the sample means <span class="math inline">\(\bar{y}\)</span> and covariance matrix <span class="math inline">\(\mathbf{S}\)</span>, which include both <code>ATT</code>itude and the positive-<code>MOOD</code> dummy code:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="ch2.html#cb107-1" tabindex="-1"></a><span class="fu">lavInspect</span>(fit.dummy, <span class="st">&quot;sampstat&quot;</span>) <span class="co"># observed sample statistics</span></span></code></pre></div>
<pre><code>## $cov
##              ATT  pos.md
## ATT      279.239        
## pos.mood   3.386   0.250
## 
## $mean
##      ATT pos.mood 
##    1.981    0.500</code></pre>
<p>If we were to “remove” the positive-<code>MOOD</code> dummy code from the SEM, the sample covariance matrix would no longer be a 2 <span class="math inline">\(\times\)</span> 2 matrix, but a 1 <span class="math inline">\(\times\)</span> 1 matrix containing only the variance of the outcome <code>ATT</code>itude.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="ch2.html#cb109-1" tabindex="-1"></a>fit.int <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ 1 &#39;</span>, <span class="at">data =</span> dat)</span>
<span id="cb109-2"><a href="ch2.html#cb109-2" tabindex="-1"></a><span class="fu">lavInspect</span>(fit.int, <span class="st">&quot;sampstat&quot;</span>)</span></code></pre></div>
<pre><code>## $cov
##         ATT
## ATT 279.239
## 
## $mean
##   ATT 
## 1.981</code></pre>
<p>Thus, we would not be fitting both nested SEMs to (all of) the same data. The <code>anova()</code> method would warn us about this if we tried it:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="ch2.html#cb111-1" tabindex="-1"></a><span class="fu">anova</span>(fit.int, fit.dummy)</span></code></pre></div>
<pre><code>## Warning: lavaan-&gt;lavTestLRT():  
##    some models are based on a different set of observed variables</code></pre>
<pre><code>## Warning: lavaan-&gt;lavTestLRT():  
##    some models have the same degrees of freedom</code></pre>
<pre><code>## 
## Chi-Squared Difference Test
## 
##           Df    AIC    BIC Chisq  Chisq diff RMSEA Df diff Pr(&gt;Chisq)
## fit.int    0 850.99 856.20     0                                     
## fit.dummy  0 835.05 842.87     0 -8.8818e-14     0       0</code></pre>
<p>Instead, we need to keep both variables in the model—any models we want to compare must include all the same variables. To represent the <span class="math inline">\(H_0: \beta_0=0\)</span>, we must fix it to 0 instead of freely estimating it (which represents the <span class="math inline">\(H_A: \beta_0 \ne 0\)</span>). This is accomplished in the model syntax by placing a zero in front of the predictor, with an asterisk between the value and the variable (<code>0*pos.mood</code>):</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="ch2.html#cb115-1" tabindex="-1"></a>fit.int <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ 1 + 0*pos.mood &#39;</span>, <span class="at">data =</span> dat)</span>
<span id="cb115-2"><a href="ch2.html#cb115-2" tabindex="-1"></a><span class="fu">anova</span>(fit.int, fit.dummy)</span></code></pre></div>
<pre><code>## 
## Chi-Squared Difference Test
## 
##           Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)    
## fit.dummy  0 835.05 842.87  0.000                                          
## fit.int    1 850.99 856.20 17.945     17.945 0.41164       1  2.274e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although we can use the generic model-comparing <code>anova()</code> method in R, this is not an analysis of variance (ANOVA), but rather an analysis of <em>deviance</em>, more commonly called a likelihood ratio test (LRT).</p>
</div>
</div>
<div id="multigroup-sem-approach" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Multigroup SEM Approach<a href="ch2.html#multigroup-sem-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The previous section demonstrated how to test the <span class="math inline">\(H_0\)</span> that 2 groups have identical means, using either GLM (<em>t</em> test) or an analogous simple-regression in single-group SEM. Like a GLM, this makes the simplifying assumption of homoskedasticity (same residual variance within each group), represented earlier by setting the <code>t.test()</code> argument <code>var.equal=TRUE</code>.</p>
<p>An alternative SEM approach is to fit models separately in each group, using the <code>group=</code> argument. In this case, we would fit an intercept-only model for <code>ATT</code>itude, estimating the parameters separately in each <code>MOOD</code> group: not only the intercept, but also the variance!</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="ch2.html#cb117-1" tabindex="-1"></a>mg.int <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ 1 &#39;</span>, <span class="at">data =</span> dat, <span class="at">group =</span> <span class="st">&quot;mood.f&quot;</span>)</span>
<span id="cb117-2"><a href="ch2.html#cb117-2" tabindex="-1"></a><span class="fu">summary</span>(mg.int, <span class="at">header =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [neutral]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT              -4.792    2.191   -2.187    0.029
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             240.120   48.024    5.000    0.000
## 
## 
## Group 2 [positive]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT               8.753    2.129    4.112    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             226.617   45.323    5.000    0.000</code></pre>
<p>There is an analogous <em>t</em> test that does not assume equal variances (which differ in the output above):</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="ch2.html#cb119-1" tabindex="-1"></a><span class="fu">t.test</span>(ATT <span class="sc">~</span> mood.f, <span class="at">data =</span> dat) <span class="co"># var.equal = FALSE by default</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ATT by mood.f
## t = -4.3889, df = 97.918, p-value = 2.878e-05
## alternative hypothesis: true difference in means between group neutral and group positive is not equal to 0
## 95 percent confidence interval:
##  -19.670277  -7.420823
## sample estimates:
##  mean in group neutral mean in group positive 
##              -4.792052               8.753498</code></pre>
<p>But now that the group-mean-difference is not a distinct SEM parameter (like the slope was in the single-group approach), how do we test the <span class="math inline">\(H_0\)</span> of equivalent means? In SEM, there are two approaches.</p>
<div id="compare-nested-mg-sems" class="section level4 hasAnchor" number="2.2.3.1">
<h4><span class="header-section-number">2.2.3.1</span> Compare Nested MG-SEMs<a href="ch2.html#compare-nested-mg-sems" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To fit a MG-SEM in which the <span class="math inline">\(H_0\)</span> must be true, we must constrain the 2 group means to be the same value. We can do this by giving them the same label in the model syntax. The label is arbitrary (below, we use <code>mu</code> for <span class="math inline">\(\mu\)</span>), as long as the same label is used for the parameter in both groups. As shown in the table above (the <a href="ch2.html#ch2-1-2"><code>lavaan</code> Syntax</a> section), labeling a single parameter works like fixing (or freeing) a parameter to a particular value, but using a character string instead of a number (or NA).</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="ch2.html#cb121-1" tabindex="-1"></a><span class="st">&#39; ATT ~ mu*1 &#39;</span></span></code></pre></div>
<pre><code>## [1] &quot; ATT ~ mu*1 &quot;</code></pre>
<p>In multiple groups, we use the <code>c()</code> function to make a vector of labels, where the first label applies to Group 1’s parameter, the second applies to Group 2, etc.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="ch2.html#cb123-1" tabindex="-1"></a>mg.eq <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; ATT ~ c(mu, mu)*1 &#39;</span>, <span class="at">data =</span> dat,</span>
<span id="cb123-2"><a href="ch2.html#cb123-2" tabindex="-1"></a>             <span class="at">group =</span> <span class="st">&quot;mood.f&quot;</span>) <span class="co"># grouping variable here, not in model</span></span>
<span id="cb123-3"><a href="ch2.html#cb123-3" tabindex="-1"></a><span class="fu">summary</span>(mg.eq, <span class="at">header =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [neutral]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT       (mu)    2.225    1.670    1.332    0.183
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             289.353   57.871    5.000    0.000
## 
## 
## Group 2 [positive]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT       (mu)    2.225    1.670    1.332    0.183
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             269.244   53.849    5.000    0.000</code></pre>
<p>Notice that the estimated mean is the same in both groups. We can compare these nested models because they were fit to the same data (<code>ATT</code> is the only variable in both cases).</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="ch2.html#cb125-1" tabindex="-1"></a><span class="fu">anova</span>(mg.eq, mg.int) <span class="co"># LRT statistic</span></span></code></pre></div>
<pre><code>## 
## Chi-Squared Difference Test
## 
##        Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)    
## mg.int  0 837.01 847.43  0.000                                          
## mg.eq   1 852.95 860.77 17.943     17.943 0.58212       1  2.276e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="define-parameters-to-obtain-wald-test" class="section level4 hasAnchor" number="2.2.3.2">
<h4><span class="header-section-number">2.2.3.2</span> Define Parameters to Obtain Wald Test<a href="ch2.html#define-parameters-to-obtain-wald-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another way to test the same <span class="math inline">\(H_0\)</span> would be to <em>define a new parameter</em> that is a function of estimated parameters. In our case, we want to freely estimate the mean in each group (i.e., no equality constraint), but calculate the difference between means <em>as a user-defined parameter</em>. This is possible using the <code>:=</code> operator in <code>lavaan</code> syntax, which requires labeling the parameter. In this case, the labels must differ so that they are not equal. Because we will have more than one line of model syntax, the example below saves the syntax as an object first, which is the recommended way of specifying a model in <code>lavaan</code>.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="ch2.html#cb127-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">&#39; ATT ~ c(mu1, mu2)*1    # freely estimate 2 means</span></span>
<span id="cb127-2"><a href="ch2.html#cb127-2" tabindex="-1"></a><span class="st">  mean_difference := mu2 - mu1  # calculate difference</span></span>
<span id="cb127-3"><a href="ch2.html#cb127-3" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb127-4"><a href="ch2.html#cb127-4" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> dat, <span class="at">group =</span> <span class="st">&quot;mood.f&quot;</span>)</span>
<span id="cb127-5"><a href="ch2.html#cb127-5" tabindex="-1"></a><span class="fu">summary</span>(fit, <span class="at">header =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [neutral]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT      (mu1)   -4.792    2.191   -2.187    0.029
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             240.120   48.024    5.000    0.000
## 
## 
## Group 2 [positive]:
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT      (mu2)    8.753    2.129    4.112    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ATT             226.617   45.323    5.000    0.000
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     mean_differenc   13.546    3.055    4.433    0.000</code></pre>
<p>This model is equivalent to <code>mg.int</code> in the previous section, but the means are labeled and a <code>mean_difference</code> parameter is defined. <code>lavaan</code> uses the <a href="https://en.wikipedia.org/wiki/Delta_method"></a> to estimate the <em>SE</em> of a function of parameters (here, difference between 2 intercepts) from the <em>SE</em>s of the original parameter estimates. Thus, we can obtain a Wald <em>z</em> statistic in the <code>summary()</code> output. We could also obtain an equivalent Wald <span class="math inline">\(\chi^2\)</span> statistic, which <span class="math inline">\(=z^2\)</span> when testing a single parameter (i.e., 1 <em>df</em>).</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="ch2.html#cb129-1" tabindex="-1"></a><span class="fu">lavTestWald</span>(fit, <span class="at">constraints =</span> <span class="st">&#39;mu1 == mu2&#39;</span>)</span></code></pre></div>
<pre><code>## $stat
## [1] 19.6558
## 
## $df
## [1] 1
## 
## $p.value
## [1] 9.272142e-06
## 
## $se
## [1] &quot;standard&quot;</code></pre>
<p>But the Wald <span class="math inline">\(\chi^2\)</span> test generalizes to the situation where multiple parameters are constrained. So it is useful for the same reason model-comparison with a LRT statistic is useful, but it does not require actually fitting the <span class="math inline">\(H_0\)</span> model.</p>
</div>
<div id="summary-of-advantages-of-multigroup-sem" class="section level4 hasAnchor" number="2.2.3.3">
<h4><span class="header-section-number">2.2.3.3</span> Summary of Advantages of Multigroup SEM<a href="ch2.html#summary-of-advantages-of-multigroup-sem" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Less restrictive assumptions
<ul>
<li>parameters differ by default</li>
<li>could be disadvantageous in small groups (asymptotic/large-<em>N</em> assumption applies to each group)</li>
</ul></li>
<li>More interpretable parameters
<ul>
<li>each group has their own intercept and slopes</li>
</ul></li>
<li>Intuitive to specify <span class="math inline">\(H_0\)</span> as user-defined parameter
<ul>
<li>e.g., the difference between the intercepts in the treatment group (<code>b2</code>) and control group (<code>b1</code>) is zero</li>
</ul></li>
<li>Intuitive to represent assumptions about equality constraints by using the same labels across groups
<ul>
<li>testable by comparing models with(out) constraints</li>
</ul></li>
<li>Can easily test <span class="math inline">\(H_0\)</span> about parameters other than means
<ul>
<li>Are variances or correlations equal across groups?</li>
</ul></li>
</ul>
</div>
</div>
</div>
<div id="fit-an-sem-to-summary-statistics" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Fit an SEM to Summary Statistics<a href="ch2.html#fit-an-sem-to-summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All of the models above were fitted to raw <code>data=</code>. When the data are complete (no missing observations: <code>NA</code>), <code>lavaan</code> automatically calculates summary statistics from <code>data=</code>. Alternatively, summary statistics can be passed directly via the <code>sample.cov=</code> and <code>sample.mean=</code> arguments, which also requires specifying the sample size via the <code>sample.nobs=</code> argument. When assuming normality for complete data, results are identical across data formats:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="ch2.html#cb131-1" tabindex="-1"></a><span class="do">## Raw Data</span></span>
<span id="cb131-2"><a href="ch2.html#cb131-2" tabindex="-1"></a><span class="fu">sem</span>(<span class="st">&#39;ATT ~ MOOD + NFC + POS&#39;</span>, <span class="at">data =</span> dat,</span>
<span id="cb131-3"><a href="ch2.html#cb131-3" tabindex="-1"></a>    <span class="at">meanstructure =</span> <span class="cn">TRUE</span>) <span class="co"># explicitly request intercept</span></span>
<span id="cb131-4"><a href="ch2.html#cb131-4" tabindex="-1"></a><span class="do">## Summary Data</span></span>
<span id="cb131-5"><a href="ch2.html#cb131-5" tabindex="-1"></a><span class="fu">sem</span>(<span class="st">&#39;ATT ~ MOOD + NFC + POS&#39;</span>, <span class="at">sample.nobs =</span> N,</span>
<span id="cb131-6"><a href="ch2.html#cb131-6" tabindex="-1"></a>    <span class="at">sample.cov =</span> S, <span class="at">sample.mean =</span> M)</span></code></pre></div>
<p>When omitting the mean structure (<code>meanstructure=FALSE</code>), also omit the <code>sample.mean=</code> argument. When fitting a multigroup SEM, you must pass a list of (means and) covariance matrices and a vector of sample sizes</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="ch2.html#cb132-1" tabindex="-1"></a>gN <span class="co"># vector of sample sizes</span></span>
<span id="cb132-2"><a href="ch2.html#cb132-2" tabindex="-1"></a>gM <span class="co"># mean vectors</span></span>
<span id="cb132-3"><a href="ch2.html#cb132-3" tabindex="-1"></a>gS <span class="co"># list of covariance matrices</span></span>
<span id="cb132-4"><a href="ch2.html#cb132-4" tabindex="-1"></a><span class="fu">sem</span>(<span class="st">&#39;ATT ~ NFC + POS&#39;</span>, <span class="at">sample.nobs =</span> gN, <span class="co"># &quot;group=&quot; is implied by lists</span></span>
<span id="cb132-5"><a href="ch2.html#cb132-5" tabindex="-1"></a>    <span class="at">sample.mean =</span> gM, <span class="at">sample.cov =</span> gS)</span></code></pre></div>
<div id="advantages-of-analyzing-summary-statistics" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Advantages of Analyzing Summary Statistics<a href="ch2.html#advantages-of-analyzing-summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Maintain privacy</strong>: They do not compromise the privacy of the research participants.</li>
<li><strong>Promote open-science practices</strong>: Summary statistics are easily reported in published empirical research without risking privacy, facilitating replication of results.
<ul>
<li>This enables us to use many published results for instruction in this book.</li>
</ul></li>
<li><strong>Facilitate replication</strong>: Research consumers can fit different models (e.g., that represent a competing theories) to the same summary statistics.</li>
</ul>
<p>However, it is unrealistic to assume data are perfectly normally distributed, and data are frequently incomplete in practice. Raw <code>data=</code> are required to:</p>
<ul>
<li>analyze incomplete data (using full information MLE rather than listwise deletion)</li>
<li>obtain robust statistics (e.g., to account for nonnormality of continuous outcomes)</li>
<li>model discrete (binary or ordinal) outcomes (which require a <em>threshold model</em>, explained later in a chapter about categorical data)</li>
</ul>
</div>
</div>
<div id="moderation-in-sem" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Moderation in SEM<a href="ch2.html#moderation-in-sem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When evaluating moderation using a product term, that product term becomes a new variable in <span class="math inline">\(\bar{y}\)</span> and <span class="math inline">\(S\)</span>. Thus, adding an interaction to an SEM typically requires raw data (see <a href="https://doi.org/10.1080/10705511.2022.2141749">Boker et al., 2023</a>, for an exception).</p>
<p>Consider an example analogous to ANCOVA: We want to test <code>MOOD</code>’s effect on <code>POS</code>itive thoughts, controlling for <code>NFC</code>. Before comparing adjusted group means, we should evaluate the homogeneity-of-slopes assumption.</p>
<p>As in <code>formula</code> objects, <code>lavaan</code> syntax recognizes the colon (<code>:</code>) operator; however, there are caveats:</p>
<ul>
<li>It only applies to a product between 2 numeric variables (which may be dummy codes, but not <code>factor</code> variables), so no 3-way interactions.</li>
<li>It is not possible to specify how the product term covaries with other variables, so it is actually safer to manually calculate the product term as a new variable in your <code>data=</code> so that you can specify parameters flexibly in syntax.</li>
<li>The asterisk (<code>*</code>) is reserved for assigning labels or values to parameters, so we cannot use a <code>formula</code> object’s shortcut to automatically include the interaction and main effects (i.e., <code>POS ~ mood.f * NFC</code>).</li>
</ul>
<p>Instead, we must specify each term explicitly in the <code>lavaan</code> model syntax.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="ch2.html#cb133-1" tabindex="-1"></a>fit.het <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39;POS ~ 1 + pos.mood + NFC + pos.mood:NFC&#39;</span>, <span class="at">data =</span> dat)</span></code></pre></div>
<p>Recall from the simple-regression example above that we could not test the <span class="math inline">\(H_0\)</span> that positive <code>MOOD</code>’s slope = 0 by dropping that dummy code from the SEM. If we did, we would not be fitting both SEMs to the same summary statistics. The same principle applies here to the product-term, which must stay in the nested SEM. The <span class="math inline">\(H_0\)</span> can be represented in the nested model by fixing the parameter to zero.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="ch2.html#cb134-1" tabindex="-1"></a>fit.hom <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39;POS ~ 1 + pos.mood + NFC + 0*pos.mood:NFC&#39;</span>, <span class="at">data =</span> dat)</span>
<span id="cb134-2"><a href="ch2.html#cb134-2" tabindex="-1"></a><span class="fu">anova</span>(fit.hom, fit.het)</span></code></pre></div>
<pre><code>## 
## Chi-Squared Difference Test
## 
##         Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
## fit.het  0 678.01 691.04 0.0000                                        
## fit.hom  1 682.08 692.50 6.0629     6.0629 0.22501       1     0.0138 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can reject <span class="math inline">\(H_0\)</span> of homogeneous <code>NFC</code> slopes across <code>MOOD</code> groups</p>
<div id="moderation-by-groups-using-mg-sem" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Moderation by Groups Using MG-SEM<a href="ch2.html#moderation-by-groups-using-mg-sem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Earlier examples used MG-SEM to estimate means in each group, then test equivalence with model-comparison (LRT) or a Wald test. That was a test of the effect of the grouping variable (<code>MOOD</code>) on the outcome (<code>POS</code>).</p>
<p>When a MG-SEM freely estimates slopes (the effect of one variable on another), that represents moderation by the grouping variable. The <span class="math inline">\(H_0\)</span> of no moderation would be represented by equality constraints (e.g., same label) on <code>NFC</code>’s slope across groups.</p>
<p>Even when the focal predictor is the grouping variable, we can capitalize on the “moderation by group” principle in MG-SEM to test the homogeneity-of-slopes assumption. The syntax below uses model comparison (LRT) to test the assumption.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="ch2.html#cb136-1" tabindex="-1"></a><span class="do">## Heterogeneous slopes</span></span>
<span id="cb136-2"><a href="ch2.html#cb136-2" tabindex="-1"></a>mg.het <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39; POS ~ 1 + NFC &#39;</span>, <span class="at">data =</span> dat, <span class="at">group =</span> <span class="st">&quot;mood.f&quot;</span>)</span>
<span id="cb136-3"><a href="ch2.html#cb136-3" tabindex="-1"></a><span class="do">## Homogenous slopes</span></span>
<span id="cb136-4"><a href="ch2.html#cb136-4" tabindex="-1"></a>mod.hom <span class="ot">&lt;-</span> <span class="st">&#39; POS ~ c(b1, b2)*1    # different intercepts</span></span>
<span id="cb136-5"><a href="ch2.html#cb136-5" tabindex="-1"></a><span class="st">             POS ~ c(b3, b3)*NFC  # same covariate slopes</span></span>
<span id="cb136-6"><a href="ch2.html#cb136-6" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb136-7"><a href="ch2.html#cb136-7" tabindex="-1"></a>mg.hom <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod.hom, <span class="at">data =</span> dat, <span class="at">group =</span> <span class="st">&quot;mood.f&quot;</span>)</span>
<span id="cb136-8"><a href="ch2.html#cb136-8" tabindex="-1"></a><span class="do">## Compare nested models</span></span>
<span id="cb136-9"><a href="ch2.html#cb136-9" tabindex="-1"></a><span class="fu">anova</span>(mg.hom, mg.het)</span></code></pre></div>
<pre><code>## 
## Chi-Squared Difference Test
## 
##        Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
## mg.het  0 680.01 695.64 0.0000                                        
## mg.hom  1 684.05 697.07 6.0369     6.0369 0.31739       1    0.01401 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Again, because MG-SEM does not assume residual homoskedasticity, this test may be more robust, as long as there is no small-sample bias to cancel out that advantage. In this case, the residual variances are nearly identical, so we can expect tests of group-mean differences to be quite similar between single- and multigroup SEM approaches.</p>
<pre><code>## 
## 
## Group 1 []:
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     POS              46.134    9.227    5.000    0.000
## 
## 
## Group 2 []:
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     POS              47.128    9.426    5.000    0.000</code></pre>
</div>
<div id="the-emmeans-package" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> The <code>emmeans</code> Package<a href="ch2.html#the-emmeans-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <a href="https://CRAN.R-project.org/package=emmeans"><code>emmeans</code></a> package greatly simplifies conducting complex pairwise comparisons on <code>lm()</code> output (also <code>glm()</code> or <code>lmer()</code>, etc.), both controlling for covariates and stratifying across moderators to probe interactions, with many options to adjust for multiple testing.
Rather than defining new parameters in model syntax, the same tools in <code>emmeans</code> are made available for <code>lavaan</code> results by the <a href="https://CRAN.R-project.org/package=semTools"><code>semTools</code></a> package.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="ch2.html#cb139-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;emmeans&quot;</span>,<span class="st">&quot;semTools&quot;</span>))</span>
<span id="cb139-2"><a href="ch2.html#cb139-2" tabindex="-1"></a><span class="fu">library</span>(emmeans)  <span class="co"># load first, so semTools knows what to do with it</span></span>
<span id="cb139-3"><a href="ch2.html#cb139-3" tabindex="-1"></a><span class="fu">library</span>(semTools)</span></code></pre></div>
<p>The functionality is available for single-group SEMs that are specified the same way as regressions in <code>lm()</code>.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="ch2.html#cb140-1" tabindex="-1"></a>em1 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(fit.het,</span>
<span id="cb140-2"><a href="ch2.html#cb140-2" tabindex="-1"></a>               <span class="at">specs =</span> <span class="sc">~</span> pos.mood <span class="sc">|</span> NFC, <span class="co"># focal predictor | moderator</span></span>
<span id="cb140-3"><a href="ch2.html#cb140-3" tabindex="-1"></a>               <span class="at">lavaan.DV =</span> <span class="st">&quot;POS&quot;</span>,        <span class="co"># name of outcome</span></span>
<span id="cb140-4"><a href="ch2.html#cb140-4" tabindex="-1"></a>               <span class="do">## probe at the M +/- 1 SD of the moderator</span></span>
<span id="cb140-5"><a href="ch2.html#cb140-5" tabindex="-1"></a>               <span class="at">at =</span> <span class="fu">list</span>(<span class="at">NFC =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.4</span>, <span class="dv">0</span>, <span class="fl">1.4</span>)))</span>
<span id="cb140-6"><a href="ch2.html#cb140-6" tabindex="-1"></a>probe1 <span class="ot">&lt;-</span> <span class="fu">pairs</span>(em1, <span class="at">rev =</span> <span class="cn">TRUE</span>) <span class="co"># so group &quot;1&quot; minus group &quot;0&quot;</span></span>
<span id="cb140-7"><a href="ch2.html#cb140-7" tabindex="-1"></a><span class="fu">rbind</span>(probe1, <span class="at">adjust =</span> <span class="st">&quot;sidak&quot;</span>)  <span class="co"># Sidak-adjusted p values</span></span></code></pre></div>
<pre><code>##  NFC  contrast              estimate   SE  df z.ratio p.value
##  -1.4 pos.mood1 - pos.mood0     5.15 1.96 Inf   2.635  0.0250
##  0    pos.mood1 - pos.mood0     8.67 1.37 Inf   6.348  &lt;.0001
##  1.4  pos.mood1 - pos.mood0    12.19 1.97 Inf   6.198  &lt;.0001
## 
## P value adjustment: sidak method for 3 tests</code></pre>
<p>The functionality is also available for multigroup SEMs, in which case the grouping variable is automatically treated as another predictor that can be specified in the <code>specs=</code> argument. Note that the grouping variable will be the name we passed to the <code>group=</code> argument when we fitted the MG-SEM (i.e., the factor variable <code>mood.f</code> rather than the dummy-coded integer variable <code>pos.mood</code>). When using <code>emmeans()</code> on a multigroup <code>lavaan</code> object, the argument <code>nesting=NULL</code> must be specified.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="ch2.html#cb142-1" tabindex="-1"></a>em2 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mg.het,</span>
<span id="cb142-2"><a href="ch2.html#cb142-2" tabindex="-1"></a>               <span class="at">specs =</span> <span class="sc">~</span> mood.f <span class="sc">|</span> NFC, <span class="co"># focal predictor | moderator</span></span>
<span id="cb142-3"><a href="ch2.html#cb142-3" tabindex="-1"></a>               <span class="at">lavaan.DV =</span> <span class="st">&quot;POS&quot;</span>,      <span class="co"># name of outcome</span></span>
<span id="cb142-4"><a href="ch2.html#cb142-4" tabindex="-1"></a>               <span class="at">nesting =</span> <span class="cn">NULL</span>,         <span class="co"># necessary for MG-SEMs</span></span>
<span id="cb142-5"><a href="ch2.html#cb142-5" tabindex="-1"></a>               <span class="do">## probe at the M +/- 1 SD of the moderator</span></span>
<span id="cb142-6"><a href="ch2.html#cb142-6" tabindex="-1"></a>               <span class="at">at =</span> <span class="fu">list</span>(<span class="at">NFC =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.4</span>, <span class="dv">0</span>, <span class="fl">1.4</span>)))</span>
<span id="cb142-7"><a href="ch2.html#cb142-7" tabindex="-1"></a>probe2 <span class="ot">&lt;-</span> <span class="fu">pairs</span>(em2, <span class="at">rev =</span> <span class="cn">TRUE</span>) <span class="co"># so group &quot;1&quot; minus group &quot;0&quot;</span></span>
<span id="cb142-8"><a href="ch2.html#cb142-8" tabindex="-1"></a><span class="fu">rbind</span>(probe2, <span class="at">adjust =</span> <span class="st">&quot;sidak&quot;</span>)  <span class="co"># Sidak-adjusted p values</span></span></code></pre></div>
<pre><code>##  NFC  contrast           estimate   SE  df z.ratio p.value
##  -1.4 positive - neutral     5.15 1.96 Inf   2.633  0.0251
##  0    positive - neutral     8.67 1.37 Inf   6.348  &lt;.0001
##  1.4  positive - neutral    12.19 1.97 Inf   6.193  &lt;.0001
## 
## P value adjustment: sidak method for 3 tests</code></pre>
<p>As expected, the test statistics are quite similar between single- and multigroup SEM approaches, differing only in the 3rd or 4th decimal place.</p>
</div>
</div>
<div id="summary-1" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Summary<a href="ch2.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter compared GLM and SEM approaches to testing a mean-difference between 2 groups, comparing output to reveal how statistics can differ between GLM and SEM. Both single- and multigroup SEM approaches were used, the latter providing the advantage of robustness to heteroskedasticity across groups. Adding a covariance facilitated demonstrating how to include an interaction term in a SEM, and why it is necessary to fix a variable’s parameter to 0 rather than drop it from the model when testing that <span class="math inline">\(H_0\)</span>. Models were fitted to both raw <code>data=</code> and summary statistics, which can provide some data-sharing advantages but is equivalent under restrictive conditions. The review and comparison both serve as a foundation for upcoming chapters that show how path analysis generalizes normal regression models.</p>
</div>
<div id="references-1" class="section level2 unnumbered hasAnchor">
<h2>References<a href="ch2.html#references-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Rosseel, Y. (2012). <code>lavaan</code>: An R package for structural equation modeling. <em>Journal of Statistical Software, 48</em>(2), 1–36. <a href="http://dx.doi.org/10.18637/jss.v048.i02" class="uri">http://dx.doi.org/10.18637/jss.v048.i02</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
